### ISSUE TITLE
yd-icon的color值设置无效

### ISSUE THREAD

**Issue by jarden-liu** [ydcss/vue-ydui#1]
我引入的是vue-ydui/dist/ydui.px.css px版本的css
<yd-icon name="home" size=".6rem" color="#FF685D"></yd-icon>
但是icon并没有颜色变化为#FF685D

调试之后发现icon的<i>标签的style确实有了color:#FF685D
但是icon还有一个before伪类  伪类的css并没有变化  color:#a6a5a5  

所以图标颜色还是#a6a5a5

**Comment by ydcss** [comment]
你好，请问是用的那个版本？伪类默认是基础父级颜色值的。

**Comment by ydcss** [comment]
麻烦尝试更新最新版本试试。

**Comment by jarden-liu** [comment]
用的0.2.8版本啊

**Comment by jarden-liu** [comment]
对了，在外部使用颜色是正常的，但是我是放在yd-cell-item的icon里面的 color就失效了

![image](https://cloud.githubusercontent.com/assets/11712343/23940766/26146310-09a1-11e7-99b0-65a973a32f98.png)

**Comment by ydcss** [comment]
你好，感谢你提出问题，经核实，确实存在严重BUG，将尽快修复。

**Comment by ydcss** [comment]
你好，该问题已经修复。版本0.2.9，麻烦更新后查看。

**Comment by anglehouse** [comment]
icon图标太少了，作者可以考虑多添加一些，不然有点不实用，望采纳
