### ISSUE TITLE
建议添加多一个css

### ISSUE THREAD

**Issue by jarden-liu** [ydcss/vue-ydui#10]
< yd-cell-item >
         < span slot="left">手机号：< /span>
          < input slot="right" type="number" placeholder="请输入手机号">
 < /yd-cell-item>

  你好，很喜欢这个UI，提点建议。当我使用这个控件做密码输入。我发现type=“password”是没有样式的。我不知道是不是有什么特殊的考虑。如果不影响其他组件的使用。希望能在

.cell-right input[type=date], .cell-right input[type=datetime-local], .cell-right input[type=number], .cell-right input[type=text], .cell-right input[type=time]

这个里面加上input[type=password]

**Comment by ydcss** [comment]
你好，确实是我遗漏了，将尽快修复。

**Comment by ydcss** [comment]
你好，已修复。

**Comment by jarden-liu** [comment]
使用正常了，谢谢~辛苦了
