### ISSUE TITLE
Cannot read property '$emit' of undefined

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#101]
![qq 20170615095158](https://user-images.githubusercontent.com/20693737/27161810-618b9b50-51b0-11e7-86b5-09474c13bcb2.png)
![image](https://user-images.githubusercontent.com/20693737/27161822-769dbce4-51b0-11e7-8b86-7f8db8617291.png)
路由切换，速度稍微快一点就会出现
![qq 20170615095057](https://user-images.githubusercontent.com/20693737/27161773-2b9fdf1a-51b0-11e7-8ccc-b6946c58a2a1.png)

**Comment by ydcss** [comment]
你好，在0.6.2已经解决了这个问题，请更新至最新版本。

**Comment by xcsweb** [comment]
我的版本是"version": "0.6.8",

**Comment by xcsweb** [comment]
路由切换过快，有时候self.$refs.infinitescrollDemo还不存在，
if(self.$refs.infinitescrollDemo){
              self.$refs.infinitescrollDemo.$emit('ydui.infinitescroll.loadedDone');
            }
改成这样，就没有报错信息了
