### ISSUE TITLE
设置自定义遮罩层的z-index在safari浏览器中不起作用

### ISSUE THREAD

**Issue by suclu** [ydcss/vue-ydui#104]
##### 复现步奏

1. 自定义一个遮罩层
.show{
        background-color: rgba(0,0,0,.4);
        position: fixed;
        z-index: 1500;
        bottom: 0;
        right: 0;
        left: 0;
        top: 0;
    }
2.  
遮罩层不能覆盖slot=navbar和slot=tabbar的元素

**Comment by RoseEnd** [comment]
我也遇到这样的情况，本人是做后端的，望解惑，感激不尽

**Comment by RoseEnd** [comment]
我也遇到这样的情况，本人是做后端的，望解惑，感激不尽

**Comment by ydcss** [comment]
你好，是不是用了yd-layout组件？
layout样式使用了-webkit-overflow-scrolling: touch;，在IOS下，使用了overflow-scrolling: touch;设置z-index将会无效。
目前ydui组件的解决办法是，在IOS设备下，弹出遮罩层给容器&lt;section id="scrollView" class="g-scrollview"&gt;添加“g-fix-ios-overflow-scrolling-bug”样式。

.g-fix-ios-overflow-scrolling-bug {<br />  /* 针对IOS 修复 css overflow scroll bug */<br />  -webkit-overflow-scrolling: auto !important;<br />}

**Comment by ydcss** [comment]
还有另外一个方法，遮罩层放置于layout组件外部也是可以的。

**Comment by tingwu55** [comment]
我这边有出现这种情况：弹窗里面设置max-height和overflow:hidden, IOS无法滑动。如果绑定的showSelect初始值为true(弹窗默认显示)，第一次是可以滑动的，但是关闭后再弹出就无法滑动了
代码：
`<yd-popup v-model="showSelect" position="center" width="6rem">
            <div style="max-height: 400px; overflow: auto;">
                <yd-checkbox-group v-model="selectList">
                    <template v-for="item in issueLists">
                        <div v-if="item.title" class="checkbox-title">{{item.title}}</div>
                        <div v-if="!item.title" class="checkbox-list">
                            <yd-checkbox :val="item.val">{{item.val}}</yd-checkbox>
                        </div>
                    </template>
                </yd-checkbox-group>
            </div>
            <p style="text-align: center;margin: .2rem 0">
                <yd-button bgcolor="#6aa4ec" color="#fff" @click.native="showSelect = false">确定</yd-button>
            </p>
        </yd-popup>`
审查了元素，发现第一次和第二次区别就是多加了.g-fix-ios-overflow-scrolling-bug calss。尝试将g-fix-ios-overflow-scrolling-bug样式还原{-webkit-overflow-scrolling: touch !important;} 没有效果
