### ISSUE TITLE
建议增加一个上传图片的功能

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#105]
图像裁剪和图像压缩，我以前做过裁剪，安卓和苹果不一样，苹果还要旋转，建议做下兼容

**Comment by ydcss** [comment]
求PR。

**Comment by xcsweb** [comment]
![image](https://user-images.githubusercontent.com/20693737/27366678-4179e24e-567a-11e7-88e7-51f16fdc7489.png)
这种是上传多个图的，不裁剪，
http://demo.lanrenzhijia.com/2016/pic0706/
这个demo是移动端，裁剪上传的
@ydcss ，还有就是有的图片上传是需要时间的，建议做个loading
