### ISSUE TITLE
输入功能和地区选择建议

### ISSUE THREAD

**Issue by fouao** [ydcss/vue-ydui#106]
输入功能建议新增一个搜索框组件，貌似没找到。
地区选择能够设置选择级别，比如说：
1.配置最大级别，选择时不显示，只显示下面的级别；
2.能够设定级别范围，比如说从省选择到市，不显示也不选择县；
3.自定义地区选择数据集，比如说乡镇街道自己可以维护进去以供选择。
作者辛苦，谢谢查看。

**Comment by ydcss** [comment]
是的，确实需要改进。

**Comment by ydcss** [comment]
你好，组件yd-cityselect现已支持传入自定义数据。省市县数据源将由用户提供，为此 ydui 提供了另外一个项目（[ydui-district](https://github.com/ydcss/ydui-district)）供用户使用，其提供两种数据源8个版本。具体请参看[这里](http://vue.ydui.org/docs/#/iupdate)

**Comment by wysitu** [comment]
你好。
我想知道，组件yd-cityselect会有清空已选的数据的方法吗？有些应用场景，需要复用一个组件，选了一个数值之后，数据清空会体验好一点。

**Comment by ydcss** [comment]
@wysitu 目前没有，过后我想想办法看怎么实现。

**Comment by ydcss** [comment]
@wysitu 已添加自定义方法重置组件。
ref="cityselectDemo"
this.$refs.cityselectDemo.$emit('ydui.cityselect.reset');

**Comment by wysitu** [comment]
@ydcss 
好的，看到了。能用上太棒了。
作者辛苦
