### ISSUE TITLE
字体文件跨域?

### ISSUE THREAD

**Issue by jay0199312** [ydcss/vue-ydui#107]
##### 问题描述 

（简明扼要地描述一下问题）

##### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

##### 复现步奏

1. 打开http://vue.ydui.org/docs/#/icons
2.  
![image](https://user-images.githubusercontent.com/16646655/27414096-be5cc684-5731-11e7-968d-66ac65647577.png)

...

**Comment by ydcss** [comment]
应该是http://www.iconfont.cn/服务器异常啊。现在是正常的哟。

**Comment by jay0199312** [comment]
应该是我本地的问题...我用谷歌不行,火狐就正常...我卸了重装下看看
