### ISSUE TITLE
在ios下滚动popup的时候底层的内容也会跟着滚动，只是在ios下是这样的情况

### ISSUE THREAD

**Issue by RoseEnd** [ydcss/vue-ydui#108]
##### 问题描述 

（简明扼要地描述一下问题）

##### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

##### 复现步奏

1. 
2.  
...

**Comment by ydcss** [comment]
你好，问题收到。

**Comment by ydcss** [comment]
你好问题已经修复。
