### ISSUE TITLE
ActionSheet 回调方法里面，没有参数，没办法获取当前选择的item

### ISSUE THREAD

**Issue by noahlam** [ydcss/vue-ydui#109]
##### 问题描述 

myItems1: [
          {
            label: '身份证',
            method: (item) => {console.log(item.label)}  //这里大部分情况下，应该是需要用到当前item的
          },
          {
            label: '其他证件',
            method: () => {console.log('其他证件')}
          }
        ]

**Comment by ydcss** [comment]
这里的 item.label 不就是你传的“身份证”么？

**Comment by noahlam** [comment]
重点是 获取不到这个item

**Comment by noahlam** [comment]
this.label也不行，报undefined。 label 报 Uncaught ReferenceError: label is not defined

**Comment by ydcss** [comment]
可以这样获取啊！this.myItems1[0].label  =》 ‘身份证’
那我还是加上吧。

**Comment by noahlam** [comment]
this.myItems1[0]应该不是动态的？是固定第一个吧？我现在用event.target.innerHTML是可以获取到，不过不方便，麻烦您加上来一下，辛苦啦，谢谢！

**Comment by ydcss** [comment]
你好，已经添加。

**Comment by noahlam** [comment]
好的，非常感谢！！！！！！！
