### ISSUE TITLE
yd-cell-item  type="link" 路由 :href={name:'XXX',params:{ xx:xx }}  脚本报错

### ISSUE THREAD

**Issue by YaoGuaiWang** [ydcss/vue-ydui#11]
yd-cell-item  type="link"    v-for 绑定数据的时候 路由 :href="{name:'XXX',params:{ xx:xx }} "  报错
  nvalid prop: type check failed for prop "href". Expected String, got Object. 
但是功能上没有错误 这怎么解决啊 是我路由绑定的方法不对？

**Comment by YaoGuaiWang** [comment]
:href="'/xx/xxxx/'+xx.xx"  好像可以

**Comment by ydcss** [comment]
你好，原参数props[href]类型设计存在问题，已经修复。
