### ISSUE TITLE
ios下，popUp中的内容无法触发滚动

### ISSUE THREAD

**Issue by RoseEnd** [ydcss/vue-ydui#110]
##### 问题描述 

（简明扼要地描述一下问题）

##### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

##### 复现步奏

1. 
2.  
...

**Comment by suclu** [comment]
上次更新版本之后就也遇到了这样的问题，很棘手不知如何解决，求解答

**Comment by ydcss** [comment]
@RoseEnd @suclu 已经修复。

**Comment by RoseEnd** [comment]
滚动是可以了，但是如果在popup中使用了layout布局的话，slot=navbar, tabbar, top, bottom这些固定的slot也会跟着滚动

**Comment by ydcss** [comment]
不建议在yd-popup组件使用yd-layout布局啊，可以考试使用yd-flexbox组件。

**Comment by RoseEnd** [comment]
自从解决了ios下滚动popup底层的东西也会滚动之后这个bug之后，popup就出现了各种问题，再解决这个之前在popup中使用layout布局是一点问题都没有的

**Comment by RoseEnd** [comment]
现在很难受啊，目前项目所有的popup都是使用的layout布局，android平台已经试运行，我想吧popup恢复到0.6.8的版本，但最近只能恢复到0.6.9的版本，求助

**Comment by ydcss** [comment]
你好，我正在修复这个问题。

**Comment by RoseEnd** [comment]
好的

**Comment by ydcss** [comment]
你好，最终我还是不打算兼容在popup组件里面使用layout组件。但是在popup组件提供了top和bottom的slot，可以实现layout效果。例如：
&lt;yd-popup v-model="show" position="bottom" height="60%"&gt;<br />&nbsp;&nbsp;&lt;div slot="top" style="height: 30px;"&gt;top&lt;/div&gt;<br />&nbsp;&nbsp;&lt;div&gt;<br />&nbsp;&nbsp;&nbsp;&nbsp;&lt;p style="height: 30px;"&gt;这里会出现滚动条&lt;/p&gt;<br />&nbsp;&nbsp;&nbsp;&nbsp;&lt;p style="height: 30px;"&gt;这里会出现滚动条&lt;/p&gt;<br />&nbsp;&nbsp;&nbsp;&nbsp;&lt;p style="height: 30px;"&gt;这里会出现滚动条&lt;/p&gt;<br />&nbsp;&nbsp;&nbsp;&nbsp; .....<br />&nbsp;&nbsp;&lt;/div&gt;<br />&nbsp;&nbsp;&lt;div slot="bottom" style="height: 30px;"&gt;bottom&lt;/div&gt;<br />&lt;/yd-popup&gt;

![tim 20170627111852](https://user-images.githubusercontent.com/5517400/27569460-5c4fef78-5b2a-11e7-9d68-5f5515038484.jpg)

**Comment by RoseEnd** [comment]
好吧，辛苦了

**Comment by ydcss** [comment]
yd-layout设计的初衷不是干这个事的，这样使用会导致页面有多个重复的ID的。

**Comment by RoseEnd** [comment]
理解理解，辛苦了
