### ISSUE TITLE
能不能把icon 的 font 本地化

### ISSUE THREAD

**Issue by DevilLeven** [ydcss/vue-ydui#111]
需要把 icon  的 font文件本地化，因为编译之后的代码放在phonegap 中做app，但是在phonegap中打开HTML是直接打开的，不会搭建一个服务器，加载服务器地址的字体文件会出错。

我尝试在自己的CSS重新加载过，但是没有效果

@font-face {
  font-family: 'YDUI-INLAY';
  src: url("../font/font_icon.ttf") format('truetype');
}

**Comment by falost** [comment]
我觉得，你可以使用base64的字体
