### ISSUE TITLE
经过反复测试，ios下，滚动popup中的内容的时候，底层的内容依然会跟着滚动，一开始是正常的，多滚动一会儿就会出现

### ISSUE THREAD

**Issue by RoseEnd** [ydcss/vue-ydui#112]
![qq 20170630101731](https://user-images.githubusercontent.com/19225061/27718246-60ce8b54-5d7d-11e7-9e74-d1ab06a67600.png)
以上是测试代码

**Comment by RoseEnd** [comment]
搜集了好多的资料，关于移动端滚动穿透问题，https://github.com/pod4g/tool/wiki/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E6%BB%9A%E5%8A%A8%E7%A9%BF%E9%80%8F%E9%97%AE%E9%A2%98 ，希望能为解决问题提供帮助

**Comment by ydcss** [comment]
恩，你发的文章之前做jQuery版的YDUI就测试过了。

确实是这样的，当拖动内容到底部或者顶部，继续拖动，会出现。

目前YDUI处理这个问题，算是比较完善的了。我也尽力了。

若更好的办法，欢迎提交PR。

**Comment by RoseEnd** [comment]
我发的上面的链接有解决办法，您看一下，是否能起到帮助

**Comment by ydcss** [comment]
网上能找到的方法，我都看过了哟。

**Comment by suclu** [comment]
你好  今天看了新更新的时间组件  在iOS上完全没有滚动穿透的问题   那使用popup的其他页面是不是也可以把这个滚动穿透的问题解决一下

**Comment by ydcss** [comment]
@suclu yd-datetime组件引用了第三方类库scroll.js，通过transform: translate3d实现滚动，采取这样的方式的话相对来说过于庞大。

看了下其他UI，Mint UI目前都没有处理，Vux采用了scroll.js的方式，但最终还是会存在问题。

所以，我个人认为这个问题就不用纠结啦。

一个人力量有限，若发现有什么好办法完美解决这个问题，欢迎new pull request。

**Comment by suclu** [comment]
嗯好的  了解   辛苦了
