### ISSUE TITLE
上拉菜单不能添加标签吗

### ISSUE THREAD

**Issue by colinming** [ydcss/vue-ydui#113]
##### 问题描述 

里面内容只能通过data写入吗 ，单独加个title都加不了

##### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

##### 复现步奏

1. 
2.  
...

**Comment by ydcss** [comment]
是的

**Comment by colinming** [comment]
那局限性太大，加 icon 想办法还是可以加，但是title 就不好加了

**Comment by ydcss** [comment]
title是用来做什么的？

**Comment by colinming** [comment]
就是一个标题啊，像这种 没必要放在 data 中吧

**Comment by ydcss** [comment]
放在data中有什么不好吗？你自己写一个类似的组件你就知道啦！

**Comment by colinming** [comment]
嗯 ，放弃用这个了，，列表动态切换样式实现困难

**Comment by ydcss** [comment]
好的
