### ISSUE TITLE
希望可以优化一下点击后展示slider的逻辑

### ISSUE THREAD

**Issue by yuqichao** [ydcss/vue-ydui#114]
##### 问题描述 

我是将slider作为表情包容器，在点击按钮弹出slider之后，默认显示的是最后一个item，滑动后恢复正常，autoplay设置的是0

##### 产生环境

- 使用版本：0.6.7
- 设备：chrome模拟手机
- 操作系统及版本：win10
- 浏览器及版本：chrome59
- 演示地址：

##### 复现步奏

1. 
2.  
...

**Comment by ydcss** [comment]
不好意思，之前没重现这个问题，不敢出声。最近开发另外一个组件时，发现确实存在这个问题，现已修复，感谢你提出的问题。
