### ISSUE TITLE
弹窗组件能否在弹窗关闭打开的同时触发其他事件呢

### ISSUE THREAD

**Issue by colinming** [ydcss/vue-ydui#115]
##### 问题描述 

（简明扼要地描述一下问题）

##### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

##### 复现步奏

1. 
2.  
...

**Comment by ydcss** [comment]
v-model="aa"   watch => aa

**Comment by colinming** [comment]
好的  试试额
