### ISSUE TITLE
弹窗组件：能否使点击背景层关闭弹窗的功能失效

### ISSUE THREAD

**Issue by colinming** [ydcss/vue-ydui#118]
##### 问题描述 

（简明扼要地描述一下问题）

##### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

##### 复现步奏

1. 
2.  
...

**Comment by ydcss** [comment]
目前不打算加上这样的功能。
