### ISSUE TITLE
form表单中多选

### ISSUE THREAD

**Issue by yajore** [ydcss/vue-ydui#122]
##### 问题描述 
form表单中多选只能放在slot right中（left没生效），我如果想通过这个实现一个购物车全选功能，还需要自己去实现一个checkbox，而且你的组件CheckBox被限定只能接受bool值，我购物车全选会是数组，望改进
  ```
<yd-cell-item type="checkbox">
            <span slot="left">多选一</span>
            <input slot="right" type="checkbox" value="Han MeiMei" v-model="checkedNames"/>
        </yd-cell-item>
```

##### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

##### 复现步奏

1. 
2.  
...

**Comment by ydcss** [comment]
你好，目前不打算在yd-cell组件中支持checkbox或radio放在左边。但是后续将会添加yd-checklist组件。
另外yd-checkbox组件是支持Boolean值和Array的。

**Comment by yajore** [comment]
抱歉，Boolean的问题是另外的问题导致的，没看仔细

**Comment by ydcss** [comment]
你好，多选列表组件已上线。
