### ISSUE TITLE
建议：关于border的实现

### ISSUE THREAD

**Issue by WangJi** [ydcss/vue-ydui#126]
不是bug，就不用模板了。
我看现在的`border-bttom`的使用的是以下代码

    border-bottom: 1px solid #d9d9d9;

在手机上并不好看，显得太粗，鉴于background-image的支持已经蛮好了，mixins里何不用如下代码：

    background-image: linear-gradient(0, @color, @color 50%, transparent 50%);

这样就做出了0.5px宽度的border了。

**Comment by ydcss** [comment]
你好，请问是哪个组件直接写了边框呢？ydui目前是通过transform: scaleY(.5);实现0.5px的边框的。

**Comment by WangJi** [comment]
不好意思，应该是我看错了。
昨天访问[list的demo](http://vue.ydui.org/demo/#/list)发现有个border有点粗，以为用的是1px。


![image](https://user-images.githubusercontent.com/5742670/28093046-49a271a8-66c8-11e7-88ed-5fa0625e13ac.png)

现在看起来应该是`transform-origin`为`0 0`的缘故，下面留出了0.5px的白边，不知道是不是有意为之，如果是`0 100%`的话应该没这个问题了。

**Comment by ydcss** [comment]
是的，设置成0 100%在部分手机的label上会不显示。

**Comment by iFwu** [comment]
边框效果建议用0.5px方案+1px方案做回退，兼容性好点，缺点就是对一些安卓机型不友好。
