### ISSUE TITLE
 KeyBoard 自动关闭问题

### ISSUE THREAD

**Issue by DevilLeven** [ydcss/vue-ydui#127]
可不可以设置KeyBoard 点击背景不关闭。点击背景关闭就不符合支付流程

**Comment by ydcss** [comment]
你好，添加了props，设置 :triggerClose="false" 即可。

**Comment by DevilLeven** [comment]
谢谢 我看到了，但是取消按钮也不存在了，其实只要点击背景遮罩不自动关闭就行了

<template v-if="triggerClose">

<a href="javascript:;" v-if="i == 4" @click.stop="close">取消</a>
  </template>

**Comment by DevilLeven** [comment]
我提个建议吧 咱们提交npm的时候连带源代码一起上传吧，这样我们可以根据自己的需求，去稍微改一改组件代码，这样有小改动就不用麻烦作者来改动。

**Comment by ydcss** [comment]
o(╯□╰)o不能这样的。至于为什么，还请你仔细想想。想在原基础上修改源码，请clone代码到本地自行修改。代码贡献请new pull request。
