### ISSUE TITLE
如何自定义icon

### ISSUE THREAD

**Issue by yaob421123** [ydcss/vue-ydui#128]
怎么自定义使用自己的icon，我看了你的icon.less源码，覆盖了引入 .ttf 也是无效

**Comment by ydcss** [comment]
每个图标的Unicode不一样，覆盖了ttf没有用的呀。自行写css就好了呀。

**Comment by yaob421123** [comment]
`@font-face {
  font-family: 'iconfont' !important;
  src: url('./../font/iconfont.eot');
  src: url('./../font/iconfont.eot?#iefix') format('embedded-opentype'),
  url('./../font/iconfont.woff') format('woff'),
  url('./../font/iconfont.ttf') format('truetype') !important,
  url('./../font/iconfont.svg#iconfont') format('svg');
} 
.iconfont {
  font-family:"iconfont" !important;
  font-size:16px;
  font-style:normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
[class*=" icon-"]:before, [class^=icon-]:before {
    font-family: "iconfont" !important;
    font-size: inherit;
}
.icon-yduijia:before { content: "\e73b"; }
.icon-jian:before { content: "\e73c"; }`

如果是在页面上直接 用Unicode， 图标能正常显示的，自己添加的 无法 正常显示;
参照YDUI的规则，我的用法：
`<yd-icon name="yduijia" slot="icon" size="0.54rem"></yd-icon>`

**Comment by ydcss** [comment]
slot="icon" 是用在cell组件里面吗？

**Comment by yaob421123** [comment]
用在 yd-tabbar 组件里面的

**Comment by yaob421123** [comment]
`<yd-icon name="yduijia" slot="icon" size="0.54rem"></yd-icon> `
这种用法能正常显示 i的伪类 属性的

**Comment by ydcss** [comment]
那是怎么使用不行呢？你这个代码不是跟上面那个一样的吗？
yd-icon其实就是根据name，生成 <i class="icon-name"></i>标签，你看源码也看到了。确保.icon-name样式正确就可以了。

**Comment by yaob421123** [comment]
上面贴出来的就是我修改过的，我这样用 是不行的，我是按照规则来写的，我也不确定是哪里出问题了，我自己覆盖一遍css，是不显示的。
自带的icon标签 在vue 打包后，套壳做成app也是不显示的

**Comment by ydcss** [comment]
控制台看看你的.ttf文件加载进来了吗？

**Comment by WX60666** [comment]
自己写icon的class类名不要跟YDUI的icon的class类名冲突. 比如自己定义的icon类名是

@font-face {
  font-family: 'wx';
  src:  url('fonts/wx.eot?ogzna6');
  src:  url('fonts/wx.eot?ogzna6#iefix') format('embedded-opentype'),
    url('fonts/wx.ttf?ogzna6') format('truetype'),
    url('fonts/wx.woff?ogzna6') format('woff'),
    url('fonts/wx.svg?ogzna6#wx') format('svg');
  font-weight: normal;
  font-style: normal;
}

[class^="wx-"], [class*=" wx-"] {
  font-family: 'wx' !important;
  speak: none;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  /* Better Font Rendering =========== */
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.wx-film:before {
  content: "\e913";
}


//使用 
  <span class="wx-film"></span>即可自定义成功

**Comment by ydcss** [comment]
你好，yd-icon组件新增了custom参数，便于自定义图标。具体请参看[自定义图标](http://vue.ydui.org/docs/#/icons)。
