### ISSUE TITLE
请问 为什么webpack编译不过？

### ISSUE THREAD

**Issue by iclear** [ydcss/vue-ydui#13]
ERROR in ./~/vue-ydui/dist/lib.px/dialog/index.js
Module not found: Error: Cannot resolve module 'Vue' in /xxxxx/xxxx/node_modules/vue-ydui/dist/lib.px/dialog @ ./~/vue-ydui/dist/lib.px/dialog/index.js 2:82-96
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks       Chunk Names
    index.html  1.47 MB       0       
webpack: Failed to compile.

**Comment by ydcss** [comment]
你好，错误信息显示找到文件哟。你是怎么引入的？

**Comment by iclear** [comment]
`import { Confirm, Alert, Toast, Notify, Loading } from 'vue-ydui/dist/lib.px/dialog'
`
但是好像是dialog引用vue的问题？

**Comment by ydcss** [comment]
你好，没排查出问题在哪，本地没重现问题，可否发一份你的项目(不包含node_modules)到我邮箱surging2@qq.com呢，麻烦你了。

**Comment by iclear** [comment]
在ubuntu下会出现，好像在windows下没有问题

**Comment by ydcss** [comment]
你好，我本地没有安装Linux，过后我安装虚拟机后排查问题。

**Comment by chuchur** [comment]
- **使用版本：** v0.6.6
- **设备：**（手机、平板移动设备） 
- **操作系统及版本：** 
- **浏览器及版本：**
- **演示地址：**

##### 复现步奏

1.  
我是这么引用的。
import YDUI from 'vue-ydui'
import {Alert} from 'vue-ydui/dist/lib.rem/dialog'
本地（mac环境）调试和构建都没有问题。  
2. 到服务器构建 编译不过去。上面那2处老是提示缺少 vue 模块。vue当然是不会缺的，我以为是node版本的问题。 把node 从6.4 到8.0 挨个的试了遍。 然后又把ydui 从0.5.5 到0.6.6 挨个试了遍，我想没人像我这样爱折腾。
3. 那么一定就是 ydui的 原因了。 终于找到了。 我发现ydui组件 引入vue 的时候 ，「vue」第一个字母是大写的酱紫：require('Vue') ..,我在想是不是linux 构建的时候大小写敏感了呢， 然后我就把源代码中Vue 改为 vue。果然。成功的构建完成。
4.希望能帮到 卡在这里的人。

**Comment by ydcss** [comment]
你太棒了，这个问题困扰我好久了，一直没解决，太感谢你的“折腾”了。
问题在于使用webpack编译后将vue转成了Vue，%>_<%，尽快修复，再次感谢！
![qq 20170608094047](https://user-images.githubusercontent.com/5517400/26908696-ded5d59e-4c2e-11e7-8ef8-5752eeb3142c.png)

**Comment by ydcss** [comment]
你好，问题已经修复。感谢！！！
