### ISSUE TITLE
请问能否增加多图滚动的功能

### ISSUE THREAD

**Issue by jkaltopp** [ydcss/vue-ydui#133]
#### 问题描述 

幻灯只能滚动一张图片,希望多图滚动也能做到

**Comment by ydcss** [comment]
你好，具体什么需求需要滚动多张图片？

**Comment by jkaltopp** [comment]
比如一排显示N张图片,然后再滚动到下一排N张图片,而不是现在的一张图片滚动的

**Comment by jkaltopp** [comment]
不需要增加了, 这个可以在 <yd-slider-item>  </yd-slider-item>里面增加样式我可以自己定义里面多张图片了.
