### ISSUE TITLE
列表LIST,增加不了自定义事件

### ISSUE THREAD

**Issue by jkaltopp** [ydcss/vue-ydui#137]
#### 问题描述 

比如我想在other加一个,加入购物车按钮,但是点击按钮会跳转到定义的路由上去,因为外层包含了a 链接, 能否在other里面可以添加按钮而不会跳转,因为我只想让图片跳转,而非整块信息

**Comment by ydcss** [comment]
你好，问题收到。确实存在问题。

**Comment by ydcss** [comment]
你好，问题已经修改。type新增div类型。
![111](https://user-images.githubusercontent.com/5517400/28456708-c78ac6e6-6e35-11e7-8167-8f4b8958ba9a.png)

**Comment by jkaltopp** [comment]
谢谢!!!!
