### ISSUE TITLE
checkbox组合循环的时候传值不进val

### ISSUE THREAD

**Issue by jkaltopp** [ydcss/vue-ydui#138]
代码如下,item.id不会生成值
<yd-checkbox-group v-model="checkbox2">
	<li class="" v-for="(item,index) in data">
        <yd-checkbox val="item.id"></yd-checkbox>
        </li>
    </yd-checkbox-group>

**Comment by ydcss** [comment]
小哥，这个是vue很基础的知识啊，val="item.id" => :val="item.id"。
