### ISSUE TITLE
滚动加载bug

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#139]
chome v.61
ydui 0.7.6
已经设置切换页面回到顶部后，滚动加载还是会出现bug
复现步骤
有两个页面，其中外面的页面比较长，当把外面的页面滑动到下面的时候，点击按钮进入子页面，子页面
会请求多次，大概就是页面切换的时候，页面没有回到顶部，滚动加载我用的是一个方法，但是我觉得原因可能是因为切换到子页面的时候，那个分页的高度算的还是外面的页面的高度，导致子页面请求多次
,图片可以看https://github.com/ydcss/vue-ydui/issues/135

**Comment by ydcss** [comment]
你好，是不是在HTML5 history 模式下呢？

**Comment by wakerman** [comment]
http://vue.ydui.org/demo/#/backtop 这个demo在6p plus 上加载和滚动同样也是有问题。拉倒最后，然后点击 top图标，你在滚动的时候会滚动不了（多试几次就重现这个了 :）

**Comment by ydcss** [comment]
@wakerman 你说的是yd-backtop组件的问题，还是yd-infinitescroll组件的问题？
延时是因为有节流操作。

**Comment by xcsweb** [comment]
@ydcss 新的vue-router好像切换路由之后，滑到到某个位置的api不支持了，所以我用的是router.beforeEach((to, from, next) => {
  window.scroll(0, 0);
  setTitle(to.meta.title);
  service.is_config = false;
  next()
})

**Comment by wakerman** [comment]
@ydcss 
手机是 iPhone 6p plus 
系统版本：10.3.3
我录制了一个视频，你可以下载看看 :)

而且好像不是很顺畅的滚动（感觉一闪一闪的）
[bug.mov.zip](https://github.com/ydcss/vue-ydui/files/1172544/bug.mov.zip)

**Comment by ydcss** [comment]
@wakerman 收到。

**Comment by ydcss** [comment]
@xcsweb 问题已修复。

**Comment by ydcss** [comment]
@wakerman 这个是Safari浏览器的特性，拖动除滚动容器的内容，需要等滚动停止后，方可滚动内容。

**Comment by wakerman** [comment]
@ydcss  嗯，这个是在微信里访问的。强迫症的时候，这个特性看着有点蓝瘦 :-)
