### ISSUE TITLE
折叠面板bug

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#142]
chrome v61
ydui 最新版本
如果折叠面板数据比较多，后台想点击一个加载相应的数据，可以快速渲染dom,减小服务器压力，但是我用this.$set改变数据，但是视图没有更新，然后再点击一次折叠面板才有数据
建议：增加一个标记，如果这个折叠面板被请求过，通过这个标记判断不允许再请求

**Comment by xcsweb** [comment]
@ydcss 
用了click.native.once加载新的数据后,依然要再次点击，视图才更新，
直接click.native.once的时候视图是没有更新的

**Comment by ydcss** [comment]
贴上你的代码！！！！！！！

**Comment by xcsweb** [comment]
<template>
  <div class="course">
    <yd-accordion accordion style="" class="list">
        <yd-accordion-item :title="item.codeDisplay" v-for="item,index in courseData" :key="item.id"  @click.native.once="clickGetCourseData(item.codeValue);current=index">
            <div style="padding: .24rem;" class="over_hide">
              <div class="course_content_border" v-for="a in item.teachs">
                <router-link :to="{path:'/course_detail',query:
             { teachModelId:a.teachModelId}}" class="pull_left roster_a">
                    <div class="title">
                      {{a.title}}第{{a.danHour}}课时
                    </div>
                    <div class="pull_right roster_btn">
                      <img class="course_img" src="../../assets/img/right.png">
                    </div>
                </router-link>
              </div>
            </div>
        </yd-accordion-item>
    </yd-accordion>
    <div style="height:80px;"></div>
  </div>
</template>

<script>
export default {
  name:'course',
  data () {
    return {
      courseData:'',
      current:0
    }
  },
  created(){
    this.getCourseData()
  },
  methods:{
    getCourseData(){
      this.http({
        url:commonUrl+"manage/teach",
        success:(res)=>{
          this.courseData=res.data;
        }
      })
    },
    clickGetCourseData(v){
      this.http({
        url:commonUrl+"manage/teach",
        params:{
          codeValue:v
        },
        success:(res)=>{
          for(let i in this.courseData)
          {
            if(this.courseData[i].codeValue==v){
              this.$set(this.courseData[i],'teachs',res.data[0].teachs)
              return
            }
          }
        }
      })
    }
  }
}
</script>


<style lang='scss' scoped>
.list{
  border: 1px solid #eeeeee;
  border-bottom: none;
  margin: 10px 10px;
  img{
    width:13px;
    margin-top: 10px;
  }
  .course_content_border{
    overflow: hidden;
    border-bottom: 1px solid #eeeeee;
    height: 40px;
    line-height: 40px;
    a{
      width: 100%;
      .title{
        float: left;
      }
      .roster_btn{
        line-height: 40px;
        margin-right: 10px;
        .tiao{
          margin-right: 20px;
        }
      }
    }
  }
  .course_content_border:nth-last-child(1){
    border: none;
  }
}
</style>

**Comment by xcsweb** [comment]
![qq 20170727141204](https://user-images.githubusercontent.com/20693737/28656668-d4546720-72d5-11e7-8cfe-3bece0ee2f80.png)
![image](https://user-images.githubusercontent.com/20693737/28656673-db2fc8d2-72d5-11e7-8f92-2674abe997e1.png)

**Comment by ydcss** [comment]
&lt;yd-accordion-item :title="item.codeDisplay" v-for="item,index in courseData" :key="item.id"  @click.native.once="clickGetCourseData(item.codeValue);current=index"&gt;<br /><br />=&gt;<br /><br />&lt;yd-accordion-item :title="item.codeDisplay" v-for="item,index in courseData" :key="item.id"  @click.native.once="clickGetCourseData(item.codeValue, index);current=index" ref="'item' + index"&gt;






![132](https://user-images.githubusercontent.com/5517400/28663559-4cd887a2-72f0-11e7-9105-5c3a6ddbee27.png)

**Comment by xcsweb** [comment]
问个问题，为啥要给div设置高度呢，我把那个高度直接去掉，视图就可以看到呢

**Comment by ydcss** [comment]
为了做展开动画。
