### ISSUE TITLE
选项卡bug

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#144]
<template>
  <div class="chidren_info">
    <yd-tab>
      <yd-tab-panel :label="item.name" v-for="item,index in studentDetail"  :key="item.id" :ref="'item' + index">
        <ul>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">宝贝性别</div>
            <div class="mui-col-xs-8">{{item.sex=="1"?"男":"女"}}</div>
          </li>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">宝贝生日</div>
            <div class="mui-col-xs-8">{{item.birthDate | date}}</div>
          </li>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">宝贝段位</div>
            <div class="mui-col-xs-8">{{item.danLevelDisplay}}</div>
          </li>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">家长姓名</div>
            <div class="mui-col-xs-8">{{item.nickName}}</div>
          </li>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">家长电话</div>
            <div class="mui-col-xs-8">{{item.tel}}</div>
          </li>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">所在班级</div>
            <div class="mui-col-xs-8">{{item.className}}</div>
          </li>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">上课时间</div>
            <div class="mui-col-xs-8">周一、周三</div>
          </li>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">上课道馆</div>
            <div class="mui-col-xs-8">{{item.shopName}}</div>
          </li>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">主教练</div>
            <div class="mui-col-xs-8">{{item.realName}}</div>
          </li>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">学习时效</div>
            <div class="mui-col-xs-8">{{item.courseEndDt | date}} （20节）</div>
          </li>
        </ul>
      </yd-tab-panel>
      <yd-tab-panel label="23432">
        <ul>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">宝贝性别</div>
            <div class="mui-col-xs-8">男</div>
          </li>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">宝贝生日</div>
            <div class="mui-col-xs-8">12112121212</div>
          </li>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">宝贝段位</div>
            <div class="mui-col-xs-8">1212121121</div>
          </li>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">家长姓名</div>
            <div class="mui-col-xs-8">21221</div>
          </li>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">家长电话</div>
            <div class="mui-col-xs-8">212121</div>
          </li>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">所在班级</div>
            <div class="mui-col-xs-8">2112121212</div>
          </li>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">上课时间</div>
            <div class="mui-col-xs-8">周一、周三</div>
          </li>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">上课道馆</div>
            <div class="mui-col-xs-8">2112121211</div>
          </li>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">主教练</div>
            <div class="mui-col-xs-8">ewrewre</div>
          </li>
          <li class="chidren_info_border">
            <div class="mui-col-xs-4">学习时效</div>
            <div class="mui-col-xs-8">ewrewe（20节）</div>
          </li>
        </ul>
      </yd-tab-panel>
    </yd-tab>
    <div style="height:60px;"></div>
  </div>
</template>

<script>
export default {
  name: 'chidren_info',
  data () {
    return {
      rate:5,
      studentDetail:'',
      weekTime:'',
    }
  },
  created(){
    this.getStudentsDetalsData()
  },
  methods:{
    getStudentsDetalsData(){
      this.http({
        url:commonUrl+"user/student_detail",
        success:(res)=>{
          this.studentDetail=res.data;
          this.weekTime=res.data[0].weekTime;
          for(let i=0;i<this.studentDetail.length;i++){
            setTimeout(() => {
              this.$refs['item'+i][0].setHeight()
            },0)
          }

          let week=new Array();
          for(let i=0;i<JSON.parse(this.weekTime).length;i++)
          {
            switch (JSON.parse(this.weekTime)[i].week)
            {
              case 1:
              week.push("周一");
              break;
              case 2:
              week.push("周二");
              break;
              case 3:
              week.push("周三");
              break;
              case 4:
              week.push("周四");
              break;
              case 5:
              week.push("周五");
              break;
              case 6:
              week.push("周六");
              break;
              case 7:
              week.push("周末");
              break;
            }
          }
          this.weekTime=week.toString();
        }
      })
    }
  }
}
</script>

<style lang='scss'>
.chidren_info{
  img{
    width: 37px;;
  }
  .chidren_info_border{
    padding: 10px 0px;
    margin: 0 10px;
    overflow: hidden;
    border-bottom: 1px solid #ddd;
  }
  .chidren_info_content_border{
    overflow: hidden;
    border-bottom: 1px solid #eeeeee;
    box-sizing: border-box;
    height: 40px;
    .chidren_info_img_div{
      margin-right: 10px;
    }
    .appraisal{
      line-height:40px;
      padding-right: 10px;
    }
    .chidren_info_a{
      display: block;
      overflow: hidden;
      .star{
        padding-top: 7px;
      }
    }
    .chidren_info_btn{
      line-height: 40px;
      margin-right: 10px;
      .red{
        color: red;
      }
      .personal_length{
        float: left;
      }
      .chidren_info_btn_img{
        display: block;
        padding-top: 14px;
        float: left;
        margin-left: 10px;
        .appraisals_img{
          width: 8px;
        }
      }
    }
  }
  .chidren_info_content_border:nth-last-child(1){
    border: none;
  }
  .circle{
    width: 7px;
    height: 7px;
    background: red;
    border-radius: 4px;
    position: absolute;
    top: 22px;
    left: 0;
  }
}
</style>

通过循环的没有高度，不通过循环的有高度

**Comment by xcsweb** [comment]
看了下dom 标题没有渲染 :label 动态绑定无效

**Comment by ydcss** [comment]
`<yd-tab ref="tab">`

`getStudentsDetalsData() {
                this.http({
                    url: commonUrl + "user/student_detail",
                    success: (res) => {
                        setTimeout(() => {
                            this.$refs.tab.init(false);
                        }, 0);
                    }
                });
            }`
