### ISSUE TITLE
建议增加多行文本框的验证

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#145]
#### 建议增加多行文本框的验证

必填，
字数限制等

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
目前没有计划加其他验证。
