### ISSUE TITLE
actionsheet

### ISSUE THREAD

**Issue by stq666** [ydcss/vue-ydui#146]
#### 问题描述 

（简明扼要地描述一下问题）

#### 产生环境

- **使用版本：0.7.5
- **设备：手机
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

actionsheet控件，数据超出手机屏幕后，前面的无法显示，是否有个属性设置？

**Comment by stq666** [comment]
actionsheet控件数据超过屏幕后，前面的无法显示

**Comment by ydcss** [comment]
数据过多不建议使用 yd-actionsheet 组件，可以考虑使用 yd-popup 组件。
