### ISSUE TITLE
可否给datetime组件加上datefomat："YYYY-mm-DD HH:mm:ss"的参数

### ISSUE THREAD

**Issue by lutercat** [ydcss/vue-ydui#147]
#### 问题描述 

很多时候，时间都是整个存储的，但是在前端显示可以多样化，可以显示到天，也可以显示到秒
可以用format参数进行前端设置。

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
你好，可以通过设置type=['datetime', 'date', 'time']自定义显示样式呀。

**Comment by MayBeWrong** [comment]
@ydcss 非常感谢！！！
