### ISSUE TITLE
checkbox bug

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#148]
chrome v61
ydui 最新版本
![qq 20170801113932](https://user-images.githubusercontent.com/20693737/28808398-430b6502-76ae-11e7-992c-e14bf3e820ca.png)
  <yd-cell-item type="checkbox">
          <span slot="left">多选一</span>
        <input slot="right" type="checkbox" value="Han MeiMei" v-model="checkedNames"/>
      </yd-cell-item>
      <yd-cell-item type="checkbox">
        <input slot="left" type="checkbox" value="Li Lei" v-model="checkedNames"/>
        <span slot="right">多选二</span>
      </yd-cell-item>
      <yd-cell-item type="checkbox">
          <input slot="left" type="checkbox" value="Jim Green" v-model="checkedNames"/>
          <span slot="right">多选三</span>
      </yd-cell-item>
checkbox居左和居右样式不同

**Comment by ydcss** [comment]
https://github.com/ydcss/vue-ydui/issues/122

**Comment by xcsweb** [comment]
@ydcss 我问的是样式问题

**Comment by ydcss** [comment]
![111111](https://user-images.githubusercontent.com/5517400/28811086-a401fe0a-76bf-11e7-9168-24031ef4aa5a.png)

不支持放在左边，就不会有样式啊。
