### ISSUE TITLE
能否增加横向滚动的选项卡？

### ISSUE THREAD

**Issue by wushaosen** [ydcss/vue-ydui#155]
#### 问题描述 
（简明扼要地描述一下问题）

因为现在大多数开发需要横向拖动的选项卡，看到demo里只有竖向滚动选项卡，能否做横向选项卡？本人小白。。。因为现在大多数开发需要横向拖动的选项卡，看到demo里只有竖向滚动选项卡，能否做横向选项卡？本人小白。。。

**Comment by ydcss** [comment]
是的，后续会加上。

**Comment by i5920** [comment]
还有横向滑动列表

**Comment by ydcss** [comment]
@wushaosen 组件已添加。
