### ISSUE TITLE
spinner 需要监听初始值的变化

### ISSUE THREAD

**Issue by jiangshanmeta** [ydcss/vue-ydui#156]
#### 问题描述 

考虑这么一个场景，prop传递下来的value有个默认值，这个默认值需要ajax向后台请求。所以需要watch value的变化，当value变化时改变counter。

虽然手动调用init方法也是一个解决方案，但是。。。。

希望能watch value变化然后调用init方法

#### 产生环境

- **使用版本：0.8.3

**Comment by ydcss** [comment]
你好，问题收到，尽快修复。

**Comment by ydcss** [comment]
你好，问题已经修复。
