### ISSUE TITLE
用lightbox的时候会提示错误

### ISSUE THREAD

**Issue by jkaltopp** [ydcss/vue-ydui#158]
Invalid prop: type check failed for prop "src". Expected String, got Array.

**Comment by ydcss** [comment]
提示很清楚了啊，src传的是字符串，你传的是数组。

**Comment by jkaltopp** [comment]
可以了,还有个问题就是,滚动选项卡有时候左边的切换不到,是不是我的数据多了才这样,因为右边差不多50多个商品,包含有图片

**Comment by jkaltopp** [comment]
这个问题主要是在打包成APP或者在微信浏览器,切换会造成左边不会切换,或者切换不对

**Comment by xcsweb** [comment]
@jkaltopp 截图，或者把代码发上来

**Comment by jkaltopp** [comment]
![_20170825105058](https://user-images.githubusercontent.com/22128332/29697731-80b2af40-8983-11e7-8538-370fc49ec9fc.png)
![_20170825105324](https://user-images.githubusercontent.com/22128332/29697730-80b29726-8983-11e7-9663-de48bff1cd70.png)

**Comment by jkaltopp** [comment]
@ydcss @xcsweb  已经截图,
