### ISSUE TITLE
关于 cityselect 页面进入时异步请求的数据回写组件默认值地址联动列表不关联问题 

### ISSUE THREAD

**Issue by viphchok** [ydcss/vue-ydui#16]
`<yd-cityselect
                v-model="show2"
                :done="result2"
                provance="optsAddressData.provance"
                city="optsAddressData.provance.city"
                area="optsAddressData.provance.area"
        ></yd-cityselect>`
异步数据获取回写回去，点击展示地址列表但是数据不关联，默认从第一项【请选择】开始，这是什么原因呢？是我回写的方式不对？

**Comment by ydcss** [comment]
你好，问题已修复。请更新至0.4.2版本。给yd-select的props【ready】绑定一个本地变量【false】,获取数据完毕后，将其设置为【true】即可。

**Comment by ila123** [comment]
@ydcss 请问yd-select如何实现多次重复设置provance,city,area的值？使用场景是一个地址列表，修改时需要回显，现在设置ready=true后，就算数据变了，选中的值也没变。谢谢！
