### ISSUE TITLE
this.$refs.datetime.open is not a function

### ISSUE THREAD

**Issue by GEOHOTIOS** [ydcss/vue-ydui#160]
#### 问题描述 
手动打开DateTime
this.$refs.datetime.open is not a function

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：Chrome
- **演示地址：**

#### 提示错误信息

1. this.$refs.datetime.open is not a function
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
ref="datetime" 存在吗？
