### ISSUE TITLE
input组件中银行卡号组件分组优化

### ISSUE THREAD

**Issue by Yee1023** [ydcss/vue-ydui#161]
#### 问题描述 

第一个四位分组加空格没有问题，但是从第二个之后，空格是再第四位加的，并且用户再删除的时候需要删除空格然后才能删除那个数字。
期望的方式是，用户输入第五个数字的时候，再第五和第四位间添加空格，用户删除第五个数字时，同时将空格和数字都删除。

这边我看了源代码，银行卡号使用的正则校验式是：/(.{4})/g，它只是简单的判断了是否输入了4位数，没有判断是否4位数之后有数字，所以导致，只要输入到4位就添加了空格，而不是到5位的时候才添加空格，将上面的正则改成：/(\d{4})(?=\d)/g就不会出现上述问题了，望采纳^_^

**Comment by ydcss** [comment]
你好，确实存在这样的问题，你给出的方法确实也能解决这个问题。下次更新修复。感谢！

**Comment by ydcss** [comment]
你好，已按照你提供的方法修复了yd-input组件。再次感谢。
