### ISSUE TITLE
省市县选择插件问题

### ISSUE THREAD

**Issue by pangao66** [ydcss/vue-ydui#162]
#### 问题描述 

（简明扼要地描述一下问题）
省市县选择插件点开是一个遮罩,滑动里面的内容会造成滑动背景层
#### 产生环境
iphone
- **使用版本：**^0.7.9 
- **设备：**（手机、平板移动设备）iphone
- **操作系统及版本：** 所有
- **浏览器及版本：**
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1.ydui的官方demo打开即存在这个问题,滑动省市县数据某些时候会造成滑动到了背景层

**Comment by ydcss** [comment]
你好，我已经优化了部分情况滚动内容底层跟着滚动的问题，但是还有些情况对我来说真是无解了。

**Comment by pangao66** [comment]
我的项目中采用了你的这个,后来我使用了官方的weui的picker组件自己封装了一下,https://weui.io/weui.js/    weui官方也用js做了这个组件,没有你的这个问题,看了一下,weui是用transform:translate3d来实现滚动的,而你的是用css的overflow:scroll属性来滚动的.   个人表示你这个做的这个做的很好,比vux更加简单

**Comment by ydcss** [comment]
组件 yd-datetime 也是通过transform实现的；之所以 yd-cityselect 组件采用超出隐藏方式实现，主要一个是用户体验（不必滚动至中间才可以选择），另外一个就是性能问题了。个人觉得，像省市县这样多数据的操作最适合这样实现了。
