### ISSUE TITLE
Confirm

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#164]
最新ydui
能加一个参数让确定和取消交换位置吗

**Comment by ydcss** [comment]
自定义按钮！
![123](https://user-images.githubusercontent.com/5517400/29449093-fe4c814a-842b-11e7-984a-684e8a265ce1.jpg)

**Comment by xcsweb** [comment]
主要是基本上所有页面都是，如果自定义的话，太麻烦了

**Comment by ydcss** [comment]
一般操作都是右手操作，确定按钮在右边比较合适。

**Comment by xcsweb** [comment]
因为他们觉得这种做法有点像流弊软件

**Comment by ydcss** [comment]
他们的谁？他们的需求不代表大众的需求。那么多UI，不满足需求，可以用其他的啊，或者自己写都可以的啊！我不会让ydui为了个别需求增加代码的。
