### ISSUE TITLE
关于vue-ydui的建议

### ISSUE THREAD

**Issue by scJingP** [ydcss/vue-ydui#167]
作者：
        你好！非常感谢你创作的vue-ydui，在学习vue-ydui中，我参照http://vue.ydui.org/docs/中的文档，去测试学习，最终也成功了，但经历的过程较为麻烦。作为一个使用者建议 demo中增加使用es5（省去将es6转化为es5的步骤）
        我使用vue-ydui的方式：
    <script src="vue-ydui/dist/lib.rem/button/index.js"></script>
    Vue.component(this.ydui.Button.name, this.ydui.Button);
    Vue.component(this.ydui.ButtonGroup.name, this.ydui.ButtonGroup);
这是我学习时候的麻烦！希望作者你能采纳

**Comment by ydcss** [comment]
你好，换个思维方式，我觉得你应该好好去学习es2015，[得抓紧了](https://babeljs.io/docs/learn-es2015/)。

**Comment by scJingP** [comment]
请问，vue-ydui这个框架 主要在哪些地方使用，我一直有个疑问，就是用ydui这个版本 直接使用样式 就能写出来的界面，为什么要用vue去弄成组件的形式？谢谢

**Comment by ydcss** [comment]
这个问题难倒我了，你还是去看看 [vue.js](http://cn.vuejs.org/v2/guide/) 吧。

**Comment by scJingP** [comment]
ydui touch中的cell样式
<div class="m-cell">
    <div class="cell-item">
        <div class="cell-left">左边内容一</div>
        <div class="cell-right">右边内容一</div>
    </div>
    <div class="cell-item">
        <div class="cell-left">左边内容二</div>
        <div class="cell-right">右边内容二</div>
    </div>
</div>
这是vue版的ydui
import Vue from 'vue';
import {CellGroup, CellItem} from 'vue-ydui/dist/lib.rem/cell';
/* 使用px：import {CellGroup, CellItem} from 'vue-ydui/dist/lib.px/cell'; */

Vue.component(CellGroup.name, CellGroup);
Vue.component(CellItem.name, CellItem);
<yd-cell-group>
	<yd-cell-item>
		<span slot="left">左边内容一</span>
		<span slot="right">右边内容一</span>
	</yd-cell-item>
	<yd-cell-item>
		<span slot="left">左边内容二</span>
		<span slot="right">右边内容二</span>
	</yd-cell-item>
</yd-cell-group>

师兄，就是你在设计vue-ydui的初衷是？ 我有一点不太明白，就是为什么ydui touch与vue-ydui的代码差不多，为什么还要弄成组件式的呢？谢谢！

**Comment by ydcss** [comment]
再多对比一下其他组件吧！相信你可以理解的。

**Comment by scJingP** [comment]
好的，再次感谢！

**Comment by scJingP** [comment]
我在使用vue-ydui的时候，是不是需要基于 npm + webpack + babel 开发，然后将生成的 js 放在我的工程中使用

**Comment by scJingP** [comment]
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Vue-ydui Demo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/zzxedu/public/static/plugin/vue-ydui/dist/ydui.rem.css">
    <script type="application/javascript" src="/zzxedu/public/static/plugin/vue-ydui/dist/ydui.flexible.js"></script>
    <script type="application/javascript" src="/zzxedu/public/static/plugin/vue2/vue.js"></script>
    <script type="application/javascript" src="/zzxedu/public/static/plugin/vue-ydui/dist/ydui.js"></script>
</head>
<body>
<div id="app">
    <yd-button type="primary">primary</yd-button>
    <yd-button type="danger">danger</yd-button>
    <yd-button type="warning">warning</yd-button>
    <yd-button type="hollow">hollow</yd-button>
    <yd-button type="disabled" disabled>disabled</yd-button>
</div>
<div id="list">
    <yd-list theme="3">
        <yd-list-item v-for="item in list">
            <img slot="img" :src="item.img">
            <span slot="title">{{item.title}}</span>
            <yd-list-other slot="other">
                <div>
                    <span class="list-price"><em>¥</em>{{item.price}}</span>
                    <span class="list-del-price">¥{{item.w_price}}</span>
                </div>
                <div>content</div>
            </yd-list-other>
        </yd-list-item>
    </yd-list>
</div>
<script>
    var app = new Vue({
        el : '#app'
    })
    var list = new Vue({
        el : '#list',
        data:{
            list:[
                {text: '1', price: '12.00', w_price : '15.00'},
                {text: '2', price: '12.00', w_price : '15.00'},
                {text: '3', price: '12.00', w_price : '15.00'}
            ]
        }
    })
</script>
</body>
</html>
```
作者，是这样使用对吧！
