### ISSUE TITLE
yd-popup bug

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#169]
ydui 最新版本
chrome v.61
.m-popup-center 里面样式是设置opacity:0,虽然看不见，但是任然可以点击

**Comment by ydcss** [comment]
你好，问题收到，尽快修复。

**Comment by ydcss** [comment]
你好，这个不影响的，点击是没有响应。 
![qq 20170824083149](https://user-images.githubusercontent.com/5517400/29644208-ee71e3d0-88a6-11e7-96f9-47ee6e93d067.jpg)

**Comment by xcsweb** [comment]
![image](https://user-images.githubusercontent.com/20693737/29814524-42561d1c-8ce0-11e7-939c-18b454475c6b.png)
