### ISSUE TITLE
list-item 组件 不能加链接！ 

### ISSUE THREAD

**Issue by iqfu321** [ydcss/vue-ydui#17]
RT

**Comment by ydcss** [comment]
请详细描述！

**Comment by iqfu321** [comment]
https://github.com/ydcss/vue-ydui/blob/master/example/routers/list.infinitescroll.vue
中

**Comment by iqfu321** [comment]
<yd-list theme="1" slot="list">
                <yd-list-item v-for="item in list">
                    <img slot="img" :src="item.img">
                    <span slot="title">{{item.title}}</span>
                    <yd-list-other slot="other">
                        <div>
                            <span class="list-price"><em>¥</em>{{item.marketprice}}</span>
                            <span class="list-del-price">¥{{item.productprice}}</span>
                        </div>
                        <div>content</div>
                    </yd-list-other>
                </yd-list-item>
            </yd-list>  怎么加链接。 自己在yd-list-item内加<a > 吗

**Comment by iqfu321** [comment]
<yd-list-item :href="'#/News/NewsDetail/123123"  arrow > 这样倒是可以

**Comment by iqfu321** [comment]
<yd-list-item type="link" :href="'#/News/NewsDetail'"  arrow >

**Comment by iqfu321** [comment]
<yd-list-item  href="#/News/NewsDetail/" >

**Comment by iqfu321** [comment]
`<yd-list-item  href="#/News/NewsDetail/" >` 这样可以

**Comment by ydcss** [comment]
你好，确实是可以这样。原设计确实存在问题，不能传入动态路由。尽快修复。

**Comment by ydcss** [comment]
你好，问题已经修复。
