### ISSUE TITLE
[feature request] popup 能否增加锚点的功能

### ISSUE THREAD

**Issue by zhengxiansen** [ydcss/vue-ydui#170]
为 popup 增加 锚点（ anchor ），定位到某个节点 ，再通过  position 来定位，可以实现很多效果

比如常用的 列表的筛选条件

**Comment by ydcss** [comment]
没看明白什么意思。

**Comment by zhengxiansen** [comment]
拿element来举例，这种效果可以使用 一个弹窗组件，然后将弹窗组件定位在按钮的下方，再将弹窗内容区域设定为百分百宽度，就可以实现了

```javascript
class Popup {
  /**
   * 弹窗组件
   * @param {Element} anchor 停靠位置, 默认body
   * @param {String} position 停靠方向
   * @param {Boolean} dismissible 点击关闭
   * @param {Number} opacity 背景透明度
   */
  constructor ({ anchor, position, dismissible, opacity }) {
      // ...
  }
}
```

```html
<yd-popup anchor="more_filter_element" position="bottom" width="100%" left="0">
一些筛选条件
</yd-popup>
```

![image](https://user-images.githubusercontent.com/7506913/30111371-eae75f58-933f-11e7-95cc-38e68e1c830f.png)

![image](https://user-images.githubusercontent.com/7506913/30111360-e1be5332-933f-11e7-85cd-7d19f10754e4.png)

**Comment by ydcss** [comment]
你好，像这种太业务性的组件不会做。自己用yd-popup实现就可以了。

**Comment by zhengxiansen** [comment]
其实我自是希望弹窗能自动定位某个节点

谢谢你的答复，后面我自己折腾吧
