### ISSUE TITLE
验证码组件倒计时刷新页面，会被重置，是否可以优化一下

### ISSUE THREAD

**Issue by colinming** [ydcss/vue-ydui#175]
#### 问题描述 

（简明扼要地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
恩，可以的。

**Comment by ydcss** [comment]
你好，已添加参数storageKey，设置不为空后，刷新页面倒计时将继续。

**Comment by zghuan** [comment]
你好，时间倒计时组件能暴露出一个暂停倒计时的方法么
