### ISSUE TITLE
7.1后面更新加载更多出现BUG

### ISSUE THREAD

**Issue by starm328** [ydcss/vue-ydui#176]
问题描述

我使用的7.1版本，后面更新之后，我使用的加载更多组件出现问题，加载更多不行了，没有报错。

产生环境

使用版本：8.7
设备：（所有设备）
操作系统及版本：
浏览器及版本：
演示地址：
复现步奏
还原版本，7.1，
...

**Comment by ydcss** [comment]
你好，发你的代码上来看看吧。

**Comment by starm328** [comment]
<yd-infinitescroll :callback="loadList" ref="infinitescrollDemo" :scrollTop="false" style="width:100%">
			<yd-list theme="1" slot="list">
				<div class="product-item">
					<product-item v-for="product in tagged" :key="product.id" :product="product"></product-item>
				</div>
			</yd-list>

			
			<span slot="doneTip">——— 亲，看完了———</span>
			
			<img slot="loadingTip" src="http://static.ydcss.com/uploads/ydui/loading/loading10.svg"/>

		</yd-infinitescroll>

**Comment by starm328** [comment]
<yd-infinitescroll :callback="loadList" ref="infinitescrollDemo" :scrollTop="false" style="width:100%">
			<yd-list theme="1" slot="list">
				<div class="product-item">
					<product-item v-for="product in tagged" :key="product.id" :product="product"></product-item>
				</div>
			</yd-list>

			
			<span slot="doneTip">——— 亲，看完了———</span>
			
			<img slot="loadingTip" src="http://static.ydcss.com/uploads/ydui/loading/loading10.svg"/>

		</yd-infinitescroll>

**Comment by starm328** [comment]
这个下拉之后没有执行到:callback="loadList"事件

**Comment by ydcss** [comment]
你好，请问你是用的哪个版本的ydui呢？

**Comment by starm328** [comment]
9.1

**Comment by starm328** [comment]
收到了吗

**Comment by ydcss** [comment]
没有，你怎么会有我的邮箱？你发这里来就好了
