### ISSUE TITLE
请问怎么直接打包example的vue项目，在浏览器中运行查看效果

### ISSUE THREAD

**Issue by leixuesong** [ydcss/vue-ydui#177]
请问怎么直接打包example的vue项目，在浏览器中运行查看效果

**Comment by ydcss** [comment]
1. npm install

2. npm run dev

3. http://127.0.0.1:4321

**Comment by leixuesong** [comment]
我的意思是把exmaple的例子，打包成正式项目，在浏览器访问。现在执行npm run build只能在dist生成部分css和js文件。然后想问一下有咩有一个官方群，方便大家交流，加入组织!

**Comment by ydcss** [comment]
1、run `webpack --config build/webpack.dev.conf.js`，请参看这里：http://webpack.github.io/docs/
2、目前没有
