### ISSUE TITLE
几点问题咨询与建议

### ISSUE THREAD

**Issue by i5920** [ydcss/vue-ydui#178]
> 底部tabbar问题

1. 代码

![qq 20170826121440](https://user-images.githubusercontent.com/17754665/29738568-24f328f8-8a58-11e7-914d-168f95701e05.png)

2. 调试

![qq 20170826121636](https://user-images.githubusercontent.com/17754665/29738576-6a14a75e-8a58-11e7-8c9c-0f0da62e3519.png)

![qq 20170826121733](https://user-images.githubusercontent.com/17754665/29738583-8bf9dc18-8a58-11e7-9e2f-1a0f96e7171b.png)

3.问题

 style="color: rgb(151, 151, 151);"  颜色属性覆盖tabbar-active

> 建议

1.是否增加左右滑动列表
2..g-scrollview::-webkit-scrollbar {display:none}  隐藏滚动条会感觉更接近app

>咨询

顶部的空白区域怎么弄掉？我看淘宝就没有这个空白区域，不知道怎么处理的！！

![qq 20170826124233](https://user-images.githubusercontent.com/17754665/29738679-52e60f4c-8a5c-11e7-9e4f-f5c10d2cb712.jpg)

**Comment by ydcss** [comment]
问题：.tabbar-active { color: #F00!important; }; 加上important试试。

建议1：暂时没有这个计划
建议2：如果隐藏，IOS设备也不会出现滚动条。

咨询：只能说不知道，我还没到看一张图片就能看出问题的境界！

**Comment by i5920** [comment]
![qq 20170826154529](https://user-images.githubusercontent.com/17754665/29739650-9665cc8a-8a75-11e7-8953-48468268b12f.png)

发现问题浏览器UC
