### ISSUE TITLE
关于datetime组件默认值的问题

### ISSUE THREAD

**Issue by RoseEnd** [ydcss/vue-ydui#179]
#### 问题描述 

当前组件datetime会有一个默认值返回，有些场景下回带来一些困扰，比如搜索条件，并不希望有默认值返回，当选择之后再返回时间，希望优化改进

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
恩，确实会有这样的问题。尽快改进。

**Comment by ydcss** [comment]
你好，问题已修复。添加 :initEmit="false"即可。

**Comment by RoseEnd** [comment]
好的，非常感谢
