### ISSUE TITLE
yd-popup bug

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#181]
#### 问题描述 

（简明扼要地描述一下问题）

#### 产生环境

- **使用版本：最新版本
- **设备：**（chrome v.61）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

#### 提示错误信息

![image](https://user-images.githubusercontent.com/20693737/29814524-42561d1c-8ce0-11e7-939c-18b454475c6b.png)
yd-popup 隐藏之后里面按钮任然可以点击

**Comment by ydcss** [comment]
建议你去看下vue的生命周期。

**Comment by ydcss** [comment]
看错，不好意思

**Comment by ydcss** [comment]
你好，问题已修复。
