### ISSUE TITLE
下拉刷新能不能提供一个方法，什么可以禁用掉

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#182]
#### 问题描述 

我做的是一个裁剪插件，会有下滑的操作，

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

#### 提示错误信息

1. 
2. ...
![image](https://user-images.githubusercontent.com/20693737/29815052-e7d66372-8ce1-11e7-8503-aac63eb0657f.png)

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
完全看不懂你想表达什么，只能从标题看出建议给yd-infinitescroll组件添加一个方法，“什么可以禁用掉”难以理解。

**Comment by ydcss** [comment]
![qq 20170830094356](https://user-images.githubusercontent.com/5517400/29851627-af8f66e0-8d67-11e7-8fb9-9750e7d98f81.jpg)

http://vue.ydui.org/docs/#/issues
