### ISSUE TITLE
建议增加一个下拉框

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#183]
#### 问题描述 

理由是因为原生select有很多局限，虽然可以选择，但是option :hover的样式不能改变，如果select背景改变,option的样式就没办法处理了，而且原生select在每个手机的样式都不相同

#### 产生环境
![image](https://user-images.githubusercontent.com/20693737/29851928-99d12f9e-8d69-11e7-9e60-270f9a8b87b8.png)
这是浏览器看到的，
如果是在手机上，select的背景应该也改不到吧

**Comment by ydcss** [comment]
这样的组件不通用啊。可以通过给select设置样式【 -webkit-appearance: none;】，自定义样式即可。

**Comment by xcsweb** [comment]
但是会不会有兼容问题

**Comment by ydcss** [comment]
{-webkit-appearance: none;  -moz-appearance: none;} 我测试过的手机都是兼容的。他那里只是说有些属性不兼容。另外你是想选择后，修改select的背景色是吧，用js控制即可。vue很好实现的。
