### ISSUE TITLE
下拉刷新能不能提供两个方法，一个可以禁用掉下拉加载的事件，一个可以重新启用下拉加载

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#184]
#### 问题描述 
下拉刷新能不能提供两个方法，一个可以禁用掉下拉加载的事件，一个可以重新启用下拉加载
（简明扼要地描述一下问题）
![image](https://user-images.githubusercontent.com/20693737/29852143-079d8abc-8d6b-11e7-9061-3d7110e2007e.png)

#### 产生环境
比如说，我有一个裁剪的插件，有一些手势操作，但是手势操作为下滑的时候，会同时触发下拉刷新的事件，能不能提供一个方法可以禁用掉下拉加载，裁剪完成，又可以启用下拉加载呢

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
是的，会有这样的情况。刚刚提交了更新v0.8.9，添加了参数stopDrag，设置:stopDrag="false" 即禁止拖动。
