### ISSUE TITLE
css类命名的建议

### ISSUE THREAD

**Issue by amoydavid** [ydcss/vue-ydui#185]
初次使用，我发现ydui的css类命名没有自己的前缀。而且有一些重写了body这种底层样式。
可能是ydui定位为一个底层框架。

如果不重写body样式，ydui的类的命名有一个ydui-的前缀，比如 .ydui-btn, .ydui-btn-block 这种。对于已经有部分自己框架的项目来说引用就更得心应手一些。

个人觉得类似的 mint-ui 在这方面略好一些。

**Comment by ydcss** [comment]
是的，有道理，本人写样式功底不行(┬＿┬)，尽快修复。

**Comment by ydcss** [comment]
你好，组件类名已添加前缀。
