### ISSUE TITLE
Accordion 建议

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#186]
#### 问题描述 

（简明扼要地描述一下问题）

![qq 20170831131636](https://user-images.githubusercontent.com/20693737/29907637-1c36db6a-8e4f-11e7-8df0-240c73496b13.png)

accordion-title 里面可不可以自定义放置一些图标，不只是标题，或者点击图标不触发accordion的展开
![image](https://user-images.githubusercontent.com/20693737/29907603-f428ed84-8e4e-11e7-9eac-957056e8c185.png)
能不能改成slot

**Comment by ydcss** [comment]
看文档

**Comment by xcsweb** [comment]
![image](https://user-images.githubusercontent.com/20693737/29908052-cfc81872-8e51-11e7-9853-9952f052cf21.png)
不知道怎么用啊

**Comment by xcsweb** [comment]
<yd-accordion-item :title="item.name"> 这个是props，但是slot怎么用啊

**Comment by ydcss** [comment]
```html
<yd-accordion-item>
    <div slot="title">啦啦啦啦 <yd-icon name="home"></yd-icon></div>
    <div style="padding: .24rem;">
        <p>花间一壶酒，独酌无相亲。</p>
    </div>
</yd-accordion-item>
```

**Comment by xcsweb** [comment]
ok
