### ISSUE TITLE
yd-grids-group显示会错位加入按钮后

### ISSUE THREAD

**Issue by qq5045100** [ydcss/vue-ydui#187]
> <yd-grids-group :rows="3">
                    <yd-grids-item v-for="n in 3" :key="n">
                        <span slot="text">{{n+msg}}</span>
                    </yd-grids-item>
                    <yd-grids-item v-for="n in 1" :key="n">
                        <span slot="text">{{n+msg}}</span>
                    </yd-grids-item>
                    <yd-grids-item v-for="n in 1" :key="n">
                        <span slot="text"><yd-button type="hollow">开始抽奖</yd-button></span>
                    </yd-grids-item>
                    <yd-grids-item v-for="n in 1" :key="n">
                        <span slot="text">{{n+msg}}</span>
                    </yd-grids-item>
                    <yd-grids-item v-for="n in 3" :key="n">
                        <span slot="text">{{n+msg}}</span>
                    </yd-grids-item>
                </yd-grids-group>

**Comment by ydcss** [comment]
你好，已更新，通过设置 itemHeight 放置页面错乱，具体请参看文档。感谢
