### ISSUE TITLE
yd-spinner 能否让默认键盘改成数字键盘，或者给一个prop，让我们自己设置

### ISSUE THREAD

**Issue by noahlam** [ydcss/vue-ydui#188]
#### 问题描述 

&lt; yd-spinner max="75" unit="3" v-model="spinner1" &gt; &lt; /yd-spinner&gt;
现在点击文本框的时候，在移动端，默认弹出的是普通的键盘（一般是输入法的默认键盘，比如搜狗的中文键盘）
能否给一个 prop,让我们能把默认键盘 设置成数字键盘？

比如：&lt; yd-spinner   type="number" max="75" unit="3" v-model="spinner1" &gt; &lt; /yd-spinner&gt;

#### 产生环境
所有手机端。

**Comment by noahlam** [comment]
比如  <yd-spinner  type='number' max="75" unit="3" v-model="spinner1"></yd-spinner>

上面不知道为什么，【比如：】   后面的代码不见了。。

**Comment by ydcss** [comment]
是的，确实应该改为数字键盘，尽快修复。

**Comment by ydcss** [comment]
你好，问题已修复。
