### ISSUE TITLE
yd-datetime 组件默认值问题 传入的时间为31号的时候会显示当月1号

### ISSUE THREAD

**Issue by yejiang1015** [ydcss/vue-ydui#190]
#### 问题描述 

传入的时间为31号的时候会显示当月1号

#### 复现步骤

1. 传入时间：2017-01-31
2. 显示时间：2017-01-01

**Comment by ydcss** [comment]
你好， 没能重现，组件还设置有其他限制条件吗？

![123](https://user-images.githubusercontent.com/5517400/30016361-611f8390-9187-11e7-8589-db5ddff52451.jpg)

**Comment by yejiang1015** [comment]
对 yd-datetime的v-model赋值2017-08-31-----》渲染的日期结果为2017-08-01

**Comment by yejiang1015** [comment]
^0.7.6 版本，最新版本已经没有这个问题了
