### ISSUE TITLE
升级7.1版本以上infinitescroll出现问题

### ISSUE THREAD

**Issue by starm328** [ydcss/vue-ydui#194]
升级7.1以上版本之后infinitescroll 无法使用，滚动到底部之后出现空隙，不能加载数据，加载是的动画也没有。在当前页面刷新之后，跳转道下一个页面，返回来的时候就可以了。

**Comment by starm328** [comment]
上次忘记贴出代码。麻烦看看。
<yd-infinitescroll :callback="loadList" ref="infinitescrollDemo" :scrollTop="false" style="width:100%">
			<yd-list theme="1" slot="list">
				<div class="product-item">
					<product-item v-for="product in tagged" :key="product.id" :product="product"></product-item>
				</div>
			</yd-list>

			
			<span slot="doneTip">——— 亲，看完了———</span>
			
			<img slot="loadingTip" src="http://static.ydcss.com/uploads/ydui/loading/loading10.svg"/>

</yd-infinitescroll>



import Vue from 'vue';
import {InfiniteScroll} from 'vue-ydui/dist/lib.px/infinitescroll';
Vue.component(InfiniteScroll.name, InfiniteScroll);
loadList() {
	Ajaxy.get( `${configs.catShop.apiBaseUrl}products/tagged?`, {tag:this.$route.params.id, take:this.pageSize, skip:this.page,})
					.when( 200, response=> {
						const _tagged = response.json;
						this.tagged = [...this.tagged, ..._tagged];
						if (_tagged.length < this.pageSize) {
							/* 所有数据加载完毕 */
							this.$refs.infinitescrollDemo.$emit('ydui.infinitescroll.loadedDone');
							return;
						}
						/* 单次请求数据完毕 */
						this.$refs.infinitescrollDemo.$emit('ydui.infinitescroll.finishLoad');
						this.page = this.page+ this.page
					} )

				;
			}

**Comment by ydcss** [comment]
麻烦整理一份方便重现的代码来，你这些代码看不出什么问题啊。

**Comment by starm328** [comment]
我发你邮件了

**Comment by ydcss** [comment]
(┬＿┬) 你发哪个邮箱了？发来这里就好

**Comment by starm328** [comment]
<template>
	<div class="product-category">
		<div class="st-header" :class="{show: $route.meta.title}">
			<div class="wrap">
				<div class="l" :class="{show: $route.meta.navValue}">
					<mu-icon-button  @click="$router.go(-1)">
						<i class="st-icon icon-back"></i>
					</mu-icon-button>
				</div>
				<div class="c">
					<em>{{$route.params.name}}</em>
				</div>
				<div class="r" :class="{show: $route.meta.selsect}">
					<router-link to="/address"><a class="button"><i class="mu-icon material-icons">border_color</i></a></router-link>
				</div>
			</div>
		</div>
		<div class="header_mar"></div>
		<div v-show="tagged.length === 0" style="width:100%">
			<no-data content="暂无相关数据" :icon="style"/>
		</div>
		<yd-infinitescroll :on-infinite="loadList" ref="infinitescrollDemo" style="width:100%">
			<yd-list theme="1" slot="list">
				<div class="product-item">
					<product-item v-for="product in tagged" :key="product.id" :product="product"></product-item>
				</div>
			</yd-list>

			
			<span slot="doneTip">——— 亲，看完了———</span>
			
			<img slot="loadingTip" src="http://static.ydcss.com/uploads/ydui/loading/loading10.svg"/>

		</yd-infinitescroll>
	</div>
</template>

<script>
	import Vue from 'vue';
	import PriceCalculator from '@/Services/PriceCalculator';
	import {ListTheme, ListItem, ListOther} from 'vue-ydui/dist/lib.px/list';
	import {InfiniteScroll} from 'vue-ydui/dist/lib.px/infinitescroll';
	import ProductItem from '@/components/product/ProductItem';
	import NoData from '@/components/compact/Nodata';
	import configs from '@/configs/app';
	import Ajaxy from 'ajaxy';
	import Data from '@/libs/Data';
	Vue.component(InfiniteScroll.name, InfiniteScroll);
	Vue.component(ListTheme.name, ListTheme);
	export default {
		name: 'product-category',
		components: {
			'product-item': ProductItem,
			'no-data': NoData,
		},
		metaInfo () {
		    const title = this.$route.params.name
		    return {
		        title: title,
		        meta: [{content: title }]
		    }
		},

		data(){
			return Data.createMap( {
				tagged: {
					subject: 'Product',
					entity: 'tagged',
					params: {
						tag: this.$route.params.id,
						take: 6,
					},
				},
			},{
				page: 6,
				pageSize: 6,
				style:'icon-favor'
			});
		},

		methods: {
			loadList() {
				Ajaxy.get( `${configs.catShop.apiBaseUrl}products/tagged?`, {tag:this.$route.params.id, take:this.pageSize, skip:this.page,})
					.when( 200, response=> {
						const _tagged = response.json;
						this.tagged = [...this.tagged, ..._tagged];
						if (_tagged.length < this.pageSize) {
							/* 所有数据加载完毕 */
							this.$refs.infinitescrollDemo.$emit('ydui.infinitescroll.loadedDone');
							return;
						}
						/* 单次请求数据完毕 */
						this.$refs.infinitescrollDemo.$emit('ydui.infinitescroll.finishLoad');
						this.page = this.page+ this.page
					} )

				;
			}
		}
	};
</script>
<style type="text/css">
.product-item{    display: -webkit-box;display: -ms-flexbox;display: flex;-ms-flex-wrap: wrap;flex-wrap: wrap;-webkit-box-align: stretch;-ms-flex-align: stretch;align-items: stretch;padding-right: 5px;padding-bottom: 5px;max-width: 1020px;margin: 0 auto;width: 100%;}
	.product-category::after{clear: both;display: block;content: ''}
	.mkd_main{padding:0 !important;}
	.product-category{
		display: -webkit-box;
		display: -ms-flexbox;
		display: flex;
		-ms-flex-wrap: wrap;
		flex-wrap: wrap;
		-webkit-box-align: stretch;
		-ms-flex-align: stretch;
		align-items: stretch;
		padding-bottom: 5px;
		max-width: 1020px;
		margin: 0 auto;
		width: 100%;
	}
</style>

**Comment by starm328** [comment]
<template>
	<div class="product-category">
		<div class="st-header" :class="{show: $route.meta.title}">
			<div class="wrap">
				<div class="l" :class="{show: $route.meta.navValue}">
					<mu-icon-button  @click="$router.go(-1)">
						<i class="st-icon icon-back"></i>
					</mu-icon-button>
				</div>
				<div class="c">
					<em>{{$route.params.name}}</em>
				</div>
				<div class="r" :class="{show: $route.meta.selsect}">
					<router-link to="/address"><a class="button"><i class="mu-icon material-icons">border_color</i></a></router-link>
				</div>
			</div>
		</div>
		<div class="header_mar"></div>
		<div v-show="tagged.length === 0" style="width:100%">
			<no-data content="暂无相关数据" :icon="style"/>
		</div>
		<yd-infinitescroll :on-infinite="loadList" ref="infinitescrollDemo" style="width:100%">
			<yd-list theme="1" slot="list">
				<div class="product-item">
					<product-item v-for="product in tagged" :key="product.id" :product="product"></product-item>
				</div>
			</yd-list>

			
			<span slot="doneTip">——— 亲，看完了———</span>
			
			<img slot="loadingTip" src="http://static.ydcss.com/uploads/ydui/loading/loading10.svg"/>

		</yd-infinitescroll>
	</div>
</template>

<script>
	import Vue from 'vue';
	import PriceCalculator from '@/Services/PriceCalculator';
	import {ListTheme, ListItem, ListOther} from 'vue-ydui/dist/lib.px/list';
	import {InfiniteScroll} from 'vue-ydui/dist/lib.px/infinitescroll';
	import ProductItem from '@/components/product/ProductItem';
	import NoData from '@/components/compact/Nodata';
	import configs from '@/configs/app';
	import Ajaxy from 'ajaxy';
	import Data from '@/libs/Data';
	Vue.component(InfiniteScroll.name, InfiniteScroll);
	Vue.component(ListTheme.name, ListTheme);
	export default {
		name: 'product-category',
		components: {
			'product-item': ProductItem,
			'no-data': NoData,
		},
		metaInfo () {
		    const title = this.$route.params.name
		    return {
		        title: title,
		        meta: [{content: title }]
		    }
		},

		data(){
			return Data.createMap( {
				tagged: {
					subject: 'Product',
					entity: 'tagged',
					params: {
						tag: this.$route.params.id,
						take: 6,
					},
				},
			},{
				page: 6,
				pageSize: 6,
				style:'icon-favor'
			});
		},

		methods: {
			loadList() {
				Ajaxy.get( `${configs.catShop.apiBaseUrl}products/tagged?`, {tag:this.$route.params.id, take:this.pageSize, skip:this.page,})
					.when( 200, response=> {
						const _tagged = response.json;
						this.tagged = [...this.tagged, ..._tagged];
						if (_tagged.length < this.pageSize) {
							/* 所有数据加载完毕 */
							this.$refs.infinitescrollDemo.$emit('ydui.infinitescroll.loadedDone');
							return;
						}
						/* 单次请求数据完毕 */
						this.$refs.infinitescrollDemo.$emit('ydui.infinitescroll.finishLoad');
						this.page = this.page+ this.page
					} )

				;
			}
		}
	};
</script>
<style type="text/css">
.product-item{    display: -webkit-box;display: -ms-flexbox;display: flex;-ms-flex-wrap: wrap;flex-wrap: wrap;-webkit-box-align: stretch;-ms-flex-align: stretch;align-items: stretch;padding-right: 5px;padding-bottom: 5px;max-width: 1020px;margin: 0 auto;width: 100%;}
	.product-category::after{clear: both;display: block;content: ''}
	.mkd_main{padding:0 !important;}
	.product-category{
		display: -webkit-box;
		display: -ms-flexbox;
		display: flex;
		-ms-flex-wrap: wrap;
		flex-wrap: wrap;
		-webkit-box-align: stretch;
		-ms-flex-align: stretch;
		align-items: stretch;
		padding-bottom: 5px;
		max-width: 1020px;
		margin: 0 auto;
		width: 100%;
	}
</style>

**Comment by ydcss** [comment]
你还是clone代码自己调试吧，一堆业务逻辑在里面，我没法排查错误啊。

**Comment by starm328** [comment]
你那里的9.1 没有问题吗？这里自动升级上去不行？

**Comment by ydcss** [comment]
http://vue.ydui.org/demo/#/list.infinitescroll 这个示例有问题吗？

**Comment by starm328** [comment]
我是升级到9.1然后换成了callback  ，但是不行。

**Comment by starm328** [comment]
这个是没有问题，可能是如果是升级的话，会存在这个问题

**Comment by ydcss** [comment]
麻烦你整理一份可以重现错误，正常运行的代码来，不要夹杂你的业务逻辑在里面。

**Comment by starm328** [comment]
我把项目文件发你了

**Comment by starm328** [comment]
我再一一个版本升级试了试，发现到7.8就不行了7.8以下，都是没有问题的

**Comment by ydcss** [comment]
我压根没收到！！！我就问你，你发哪个邮箱？
另外请看看这里 http://vue.ydui.org/docs/#/issues
