### ISSUE TITLE
countup数字动画这里有个bug

### ISSUE THREAD

**Issue by starm328** [ydcss/vue-ydui#195]
如果吧数字动画放在轮播图slider里面的话，轮播图滚动，第一次进来滚动每个都是好的，如果有两个轮播， 滚动到第二个的时候，返回第一个，第一个的动画就没有了，一直停留在0。还有这里提个个人建议，如果放在轮播组件里面，在轮播的时候，轮播到第二个的时候，第二个的动画才执行。忘采纳。

**Comment by ydcss** [comment]
yd-slider组件提供了callback，yd-countup提供了start参数了啊？
