### ISSUE TITLE
vue-ydui如何在组件内引入 ydui 组件?

### ISSUE THREAD

**Issue by LowLoop** [ydcss/vue-ydui#196]
import {Input} from 'vue-ydui/dist/lib.rem/input';
Vue.component(Input.name, Input);
按需引入除了在main.js里面跟官网文档里写的.这样引入之外没有其它方法了吗?
我之前是用vux做项目的. 习惯了
import Actionsheet from 'vux/src/components/actionsheet/index.vue'
export default {
  components: {
    Actionsheet
  }
}
这样的方式引入 ui 组件. 但是我npm安装ydui之后用上述的方式引入组件. 运行的时候会报错.
请问这是为什么呢?

**Comment by ydcss** [comment]
```js
const components = {};
components[Input.name] = Input;

export default {
   components: components
}
```

**Comment by LowLoop** [comment]
自问自答. 问题解决了.
import {Button, ButtonGroup} from 'vue-ydui/dist/lib.rem/button';
export default {
    components: {
        YdButton:Button,
        YdButtonGroup:ButtonGroup
    }
}
这样子引入.然后正常使用.
<yd-button-group>
      <yd-button size="large" type="primary">button test</yd-button>
    </yd-button-group>

**Comment by LowLoop** [comment]
@ydcss  你可以把这个方式一并写在官网上哈.

**Comment by ydcss** [comment]
这个是基础知识啊。

**Comment by LowLoop** [comment]
@ydcss 不要拦着我,我要去跳河( ⊙o⊙ ).....

**Comment by LowLoop** [comment]
@ydcss  昨天上级找我. 说让我看看ydui.然后今天决定把之前vux写的东西全部换成yuui. 不说了.我要加紧改了.~~(╯﹏╰)

**Comment by ydcss** [comment]
做好跳坑的心里准备。😀😀
