### ISSUE TITLE
InfiniteScroll 滚动加载组件的问题

### ISSUE THREAD

**Issue by RoseEnd** [ydcss/vue-ydui#197]
#### 问题描述 

（更新版本后，on-infinite  props被废除，但是还是提示必传）
![imuwl39rmspviw1 l3w ymu](https://user-images.githubusercontent.com/19225061/30092433-8b78c690-92f1-11e7-9a59-e1d999040daf.png)

#### 产生环境

- **使用版本：0.9.1
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
你好，带来不便，还请谅解。确定代码已升级为0.9.1了么，0.9.1之前的版本on-infinite确实是必填的。

**Comment by RoseEnd** [comment]
是这个版本，
![saip5j bb5h9lfpq57y7pog](https://user-images.githubusercontent.com/19225061/30093012-18a759e8-92f5-11e7-8355-fd30676c1594.png)

**Comment by RoseEnd** [comment]
好吧，重新运行npm run dev又没有问题了
