### ISSUE TITLE
yd-check-list组件问题

### ISSUE THREAD

**Issue by suclu** [ydcss/vue-ydui#200]
#### 问题描述 
![image](https://user-images.githubusercontent.com/20769006/30101696-dd9fc6f2-931f-11e7-81eb-7e98b57d13a4.png)
![image](https://user-images.githubusercontent.com/20769006/30101768-1fc25a86-9320-11e7-9b50-bc4104514ff1.png)

#### 复现步骤

1. 按照官方文档写的

**Comment by ydcss** [comment]
麻烦把代码贴出来。

**Comment by suclu** [comment]
不好意思我弄错了  我重启了下服务好了
