### ISSUE TITLE
npm 不能正常更新到最新版本

### ISSUE THREAD

**Issue by leson1986** [ydcss/vue-ydui#202]
通过npm重新安装，更新不到最新版本，只能更新到"vue-ydui": "^0.8.9"

**Comment by ydcss** [comment]
？？

**Comment by leson1986** [comment]
![image](https://user-images.githubusercontent.com/3852354/30144834-48bea7a0-93c0-11e7-8ff5-63bad3b4ee74.png)

**Comment by ydcss** [comment]
--save

**Comment by leson1986** [comment]
“-save或 --save”一样，都不能更新到最新版本。我是从0.8.7升的，直接就升到0.8.9，但就是升不能最新的，很奇怪。不知道有没有人跟我遇到同样的问题。

**Comment by leson1986** [comment]
@ydcss 如图那样子更新是不成功的，我直接把package.json里的版本号改了，然后直接npm i安装就可以了。奇怪
