### ISSUE TITLE
Slider搭配CountUp第一滑倒最有一个BUG

### ISSUE THREAD

**Issue by starm328** [ydcss/vue-ydui#203]
Slider搭配CountUp使用时，最后一个回到第一个的时候，第一个会一直停留在0，
使用Slider  的回调，实现CountUp  start = true  无效。

**Comment by starm328** [comment]
找到问题所在了，Slider  他渲染出来会默认，第一个和最后一个会复制一个在最前和最后，最后和最前的两个都是0，数字

**Comment by ydcss** [comment]
你好，如果是循环播放的无解。搭配countup使用建议设置yd-slider为不循环，即:loop="false"。:loop为v1.0.3新增。
