### ISSUE TITLE
yd-icon自定义颜色问题

### ISSUE THREAD

**Issue by LowLoop** [ydcss/vue-ydui#204]
<yd-icon color="red" name="error" class="icon-del"></yd-icon>
如上 我按照api文档里说的 加了color
1.页面上有效果.
2.但是console控制台  报错:
[Vue warn]: Invalid prop: custom validator check failed for prop "color".

found in

---> <YdIcon>
       <YdCellGroup.......................................................
这是什么问题?
@ydcss

**Comment by LowLoop** [comment]
<yd-icon color="red" name="error" class="icon-del"></yd-icon>
@ydcss

**Comment by LowLoop** [comment]
yd-icon color="red" name="error" class="icon-del"></yd-icon

**Comment by ydcss** [comment]
小哥，这个句话说得很清楚了啊。
[Vue warn]: Invalid prop: custom validator check failed for prop "color".
color的格式不正确。请填写常规颜色值。例如：#FF0000
