### ISSUE TITLE
 在微信公众号的ios设备上，KeyBoard假如不手动关闭，回退或者跳转到其他页面，新页面将无法滑动

### ISSUE THREAD

**Issue by Channing-Huang** [ydcss/vue-ydui#208]
#### 问题描述 

（简明扼要地描述一下问题）
 在微信公众号的ios设备上，KeyBoard假如不手动关闭，回退或者跳转到其他页面，新页面将无法滑动

#### 产生环境

- **使用版本：**0.8.3
- **设备：**手机

- **操作系统及版本：**微信6.5.14
- **浏览器及版本：**
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 将数字键盘呼叫出来
2. 点击微信自带的回退，新页面将无法滑动。
3.密码输入完毕后跳转到的新页面也无法滑动

**Comment by ydcss** [comment]
你好，问题收到，尽快修复。

**Comment by starm328** [comment]
这个Popup也会有这个问题

**Comment by ydcss** [comment]
@Channing-Huang @starm328 问题已修复。
