### ISSUE TITLE
如何在除了main.js文件之外的 js 文件调用dialog插件

### ISSUE THREAD

**Issue by LowLoop** [ydcss/vue-ydui#210]
我在main.js中这样引入了
```
import { Confirm, Alert, Toast, Notify, Loading } from 'vue-ydui/dist/lib.rem/dialog';

Vue.prototype.$dialog = {
  confirm: Confirm,
  alert: Alert,
  toast: Toast,
  notify: Notify,
  loading: Loading,
};
```
1.在main.js中 Toast({ /* 参数 */ }); 这样调用没问题
2.在各个.vue组件中 this.$dialog.toast({ /* 参数 */ }); 这样调用也没问题.
我现在的问题是. 我有个 fetch.js文件. 里面封装了axios. 需要用到dialog插件.
1.用Toast({ /* 参数 */ });  报错
2.在fetch.js中import Vue from 'vue'.然后 Vue.$dialog.toast({ /* 参数 */ });这样调用也报错.
报错信息类似这样:
TypeError: Cannot read property 'toast' of undefined
    at eval (fetch.js?6a10:38)
    at <anonymous>

**Comment by LowLoop** [comment]
@ydcss

**Comment by ydcss** [comment]
你好，我解决ydui的问题，不解决个人项目问题。建议自己google一下吧。
