### ISSUE TITLE
slider 组件，会在最前和最后添加一个div出现的问题

### ISSUE THREAD

**Issue by starm328** [ydcss/vue-ydui#211]
使用slider组件，渲染出来的页面会在前面后面多添加一个yd-slider-item  
出现BUG ，如果里面放的是子组件，那么他们不会被渲染出来，会出现两个空盒子

**Comment by ydcss** [comment]
是的，如果是循环播放的话，使用子组件无解。可以考虑设置yd-slider为不循环，即:loop="false"。:loop为v1.0.3新增
