### ISSUE TITLE
一个折腾了一阵子的问题。yd-list组件设置click属性

### ISSUE THREAD

**Issue by siguiws** [ydcss/vue-ydui#212]
#### 问题描述 

使用了 list组件所有布局修改均没有问题
唯独要做列表 每一项的点击事件。
点击事件会根据 不同设备发生不同跳转。
仅仅一个href无法满足，多种尝试却又无法给yd-list-item项设置@click属性

#### 产生环境

- **使用版本：v0.9.2
- **设备：Mac Chrome,IPhone7（手机、平板移动设备）
- **操作系统及版本：MacOS，IOS
- **浏览器及版本：**
- **演示地址：**

#### 提示错误信息

1. 无错误提示
2. 

#### 复现步骤

1. 并非代码错误，不知是否没有这种设置支持
2. ...

**Comment by ydcss** [comment]
@click.native
