### ISSUE TITLE
官方文档的单独引入vue-ydui/dist/lib.rem/grids使用说明有误

### ISSUE THREAD

**Issue by sword913** [ydcss/vue-ydui#219]
#### 问题描述 

（简明扼要地描述一下问题）
错误的方式（官方使用手册）：
![image](https://user-images.githubusercontent.com/12130505/30316931-4de92290-97db-11e7-8a5d-9c8b628a9ec4.png)

正确的方式：
![image](https://user-images.githubusercontent.com/12130505/30316948-5802df00-97db-11e7-8a67-59ee13eb9ea4.png)

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
非常感谢你指出的问题，已修正。
