### ISSUE TITLE
选项卡不能用v-for循环

### ISSUE THREAD

**Issue by jkaltopp** [ydcss/vue-ydui#220]
代码如下:
<yd-tab-panel label="标题" v-for="item in data">
</yd-tab-panel>

这样循环不能显示出数据

**Comment by weixisheng** [comment]
选项卡循环的话要setTimeout重新初始化

**Comment by Grewer** [comment]
如果是用 ajax 获取数据,可以在一开始用 v-if 获取完数据后 再显示就行了

**Comment by ydcss** [comment]
@jkaltopp 已修复。
