### ISSUE TITLE
vue2.x官方文档看不到下方内容

### ISSUE THREAD

**Issue by nasaplayer** [ydcss/vue-ydui#222]
#### 问题描述 
1、vue2.x官方文档无法使用向下的滚动条
2、更新日志0.9.1 时间有误~ 今天9.13号 b（￣▽￣）d　
beta
2017-09-20

**Comment by ydcss** [comment]
你好。

1、是无法看到下部分的内容吗（如果是使用高版本的浏览器试试）？还是指滚动条太小了，点击不到（这个是故意这样的<(￣3￣)> ！）。
2、已修正。

谢谢
