### ISSUE TITLE
dialog bug

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#223]
#### 问题描述 

iframe 里面有个video,video不播放没问题，dialog正常显示
video播放之后,dialog会在video下方显示，苹果没问题，安卓异常，

![image](https://user-images.githubusercontent.com/20693737/30363502-01888c70-9893-11e7-8b3f-e90db60de970.png)
按返回键后，才看到弹窗，毕竟不能点击到
![image](https://user-images.githubusercontent.com/20693737/30363576-51ce8eb4-9893-11e7-9f48-6827b5666c57.png)
使用原生alert是这样的，
![image](https://user-images.githubusercontent.com/20693737/30414172-ce79ba3a-9954-11e7-88e1-43c03e0e0733.png)

#### 产生环境

- **使用版本：最新版本
- **设备：**（华为手机6x，微信，）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by xcsweb** [comment]
这个应该是微信视频的bug，播放时是最顶层，播放完成没有还原，我暂时是点击按钮隐藏了视频，不知道你还有没有其他的解决办法

**Comment by xcsweb** [comment]
dialog 也应该按返回键的时候，关闭掉

**Comment by ydcss** [comment]
今天更新的版本已修复。
