### ISSUE TITLE
DateTime只需选择年，月，如何设置

### ISSUE THREAD

**Issue by weison** [ydcss/vue-ydui#224]
#### 问题描述 

我只需要显示年和月份时，该使用怎么样的设置模式呢，尝试过将type设置为data,将dayFormat的style设置为none,解决显示具体日期的问题，但绑定的日期必须是年/月/日都齐全，如何解决

**Comment by ydcss** [comment]
你好，原设计存在缺陷，后期修复。

**Comment by halfPotatoOutlook** [comment]
那问一下，目前有没有什么好的hack技巧，可以在现有的基础上，把最后一栏去掉

**Comment by ydcss** [comment]
你好，问题已修复。
