### ISSUE TITLE
checklist全选问题

### ISSUE THREAD

**Issue by weileaf** [ydcss/vue-ydui#225]
#### 问题描述 

调试模式中切换到手机调试 刷新页面后全选无反应 ，切换回pc调试并刷新页面后正常。
在手机上测试无问题，目前只有浏览器调试模式有这个问题

#### 产生环境

- **使用版本：0.93
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

**Comment by ydcss** [comment]
感谢提出问题。请以手机测试结果为准。
