### ISSUE TITLE
您好，子组件异步调用lightbox，无法显示图片，一直loading

### ISSUE THREAD

**Issue by HoldSkill** [ydcss/vue-ydui#226]
1、如题。
![_20170914182735](https://user-images.githubusercontent.com/25190239/30425120-ba666e32-997a-11e7-887a-54ad1df71dd4.png)
2、查看了源代码，个人觉得应该是slider组件中，数据更新后，没有重新初始化造成。
3、请问lightbox中的num参数是不是用于lightbox的重新初始化呢？

**Comment by ydcss** [comment]
1/2、请发代码。
3、是的。
