### ISSUE TITLE
yd-slider 问题,   手机上 切换的时候,只能 切换 不能上下滚动的问题...

### ISSUE THREAD

**Issue by chuchur** [ydcss/vue-ydui#228]
问题所在: yd-slider 问题,   手机上 切换的时候,只能 切换大图,  不能上下滚动页面.

升级到0.9.3  之后 ,那么问题 就来了...  上一版本好好的, 升级之后突然出现的. .不知道作者去掉了判断,直接换成了监听 是为了解决什么问题.  困扰我很久, 我不想来看你编译后的代码. . 但是没办法, 这个问题储在这里... 

因为我也确切不知道问题是出在哪一个版本,  一个版本一个版本回滚...找到问题了. 

我没有fork,代码, 就不提交了, 再说 你这个我几乎改的面目全非了..
yd-slider  部分 ..

bindEvents: function () { ....}

改成如下 

bindEvents: function () {
          var t = this,
            e = this.touchEvents();  //写在下边....
          this.$el.addEventListener(e.start, this.touchStartHandler), this.$el.addEventListener(e.move, this.touchMoveHandler), this.$el.addEventListener(e.end, this.touchEndHandler), this.$el.addEventListener("click", function (e) { t.touches.allowClick || e.preventDefault() }), window.addEventListener("resize", this.resizeSlides), document.body.addEventListener("touchmove", this.stopDrag)
        },

touchEvents 的判断如下...
///你新版的把这个干掉了. 为啥呢 ... 是为了解决什么问题呢 ..该判断还是要判断的呢...
touchEvents: function () {
          var t = this.supportTouch = window.Modernizr && !!window.Modernizr.touch || function () {
            return !!("ontouchstart" in window || window.DocumentTouch && document instanceof DocumentTouch)
          }();
          return {
            start: t ? "touchstart" : "mousedown",
            move: t ? "touchmove" : "mousemove",
            end: t ? "touchend" : "mouseup"
          }
        },

虽然你这个 还是beta 版本, 但是我这已经用在生产环境了,  
感觉这个问题 , 给用户体验造成问题, 所以还是提给你...

**Comment by ydcss** [comment]
感谢指出问题。确实是因为我删除了 this.supportTouch = 。。。导致不能上下滚动页面问题。现已修复这个问题。
