### ISSUE TITLE
关于折叠面板  Accordion组件的建议

### ISSUE THREAD

**Issue by RoseEnd** [ydcss/vue-ydui#229]
能否给yd-accordion-item添加是否启用点击整行触发选中的props ,这样 在给title   slot添加自定义事件的时候，不会触发yd-accordion-item的折叠与展开

**Comment by ydcss** [comment]
你好，已更新。提供了两个没有事件响应的slot【icon和txt】，感谢。

**Comment by RoseEnd** [comment]
好的，辛苦了!
