### ISSUE TITLE
在header 组件里面 怎么没有返回上一页功能呢？

### ISSUE THREAD

**Issue by xuan1024** [ydcss/vue-ydui#230]
在header 组件里面 怎么没有返回上一页功能呢？  建议加上图片上传的功能，就更完美了，怎么也没有找到loading 的效果 ， 当页面在加载中 会出现的 loading

**Comment by xcsweb** [comment]
建议使用vue-router, this.$router.go(-1)返回上一样，loading也自己写，网上也有很多例子
