### ISSUE TITLE
关于数字加减，添加多个数字加减，获取当前值的问题

### ISSUE THREAD

**Issue by zhanglongjiZLJ** [ydcss/vue-ydui#231]
#### 问题描述 

（简明扼要地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

#### 提示错误信息

1. 无法获取点击计数器的当前值
2. ...

#### 复现步骤

1. 
2. ...

**Comment by zhanglongjiZLJ** [comment]
无法获取点击计数器的当前值，使用起来有点小麻烦

**Comment by xcsweb** [comment]
当前值就是你v-model的那个值啊
