### ISSUE TITLE
yd-checklist  全选在手机环境下全选不了，单选可以选择

### ISSUE THREAD

**Issue by starm328** [ydcss/vue-ydui#233]
完全复制文档里面的demo进行的测试，在谷歌浏览器模拟手机的环境下，全选不了，在苹果6手机上也全选不了。

**Comment by xcsweb** [comment]
我的chrome,v.61是可以的，请问你的chrome版本是多少

**Comment by starm328** [comment]
V61的  

![Uploading image.png…]()
代码和视图是这样的
点击全选没有反应

**Comment by starm328** [comment]
V61的

![Uploading 656.png…]()

代码和视图是这样的
点击全选没有反应

**Comment by ydcss** [comment]
@starm328 打开这个示例，也存在问题吗？
http://vue.ydui.org/demo/#/checklist

**Comment by starm328** [comment]
这个没有问题，但是我复制文档里面的代码，是有问题

**Comment by ydcss** [comment]
@starm328 现已修复。原官网使用方法和组件源码都存在问题。
```html
<yd-checkbox v-model="isCheckAll" shape="circle" @click.native="checkAll">

修改为：

<yd-checkbox v-model="isCheckAll" shape="circle" :change="checkAll">
