### ISSUE TITLE
表单 cell bug

### ISSUE THREAD

**Issue by xuan1024** [ydcss/vue-ydui#235]
有没有遇到当页面第一次进入了的时候页面的样式没有加载， 我用的是这组demo 第一次进入页面， 只有文字显示了， 但是复选框没有显示， 文字也没有行高， 有遇到过的各位 帮忙解释下，是什么原因， 感谢

<yd-cell-group title="多选">
        <yd-cell-item   ##type="checkbox">
            <span slot="left">多选一</span>
            <input slot="right" type="checkbox" value="Han MeiMei" v-model="checkedNames"/>
        </yd-cell-item>

        <yd-cell-item type="checkbox">
            <span slot="left">多选二</span>
            <input slot="right" type="checkbox" value="Li Lei" v-model="checkedNames"/>
        </yd-cell-item>

        <yd-cell-item type="checkbox">
            <span slot="left">多选三</span>
            <input slot="right" type="checkbox" value="Jim Green" v-model="checkedNames"/>
        </yd-cell-item>

        <yd-cell-item>
            <span slot="left">选中的值：</span>
            <span slot="right">{{checkedNames}}</span>
        </yd-cell-item>
 @

**Comment by ydcss** [comment]
你好，你引入ydui的方式是？不排除网络原因。

**Comment by xuan1024** [comment]
好的， 谢谢 我已经找到是什么原因了， 因为我在前一个页面 的 yd-cell-right 隐藏了，  当页面跳入下一个页面的时候， 就会出现这样的情况
