### ISSUE TITLE
省市县级联 这个怎么  改成三级联动选择框？

### ISSUE THREAD

**Issue by changlie** [ydcss/vue-ydui#236]
![image](https://user-images.githubusercontent.com/16432706/30587524-0bfa34a6-9d66-11e7-8ea4-c9b9c6440625.png)

**Comment by ydcss** [comment]
你好。
1、设置“:items”为你的联动数据即可。但是数据格式是有限定的，请参看文档。
2、“所在地区”目前不能修改，原设计存在缺陷。后期修复。

**Comment by changlie** [comment]
好的，感谢百忙中的回复，期待更新

**Comment by ydcss** [comment]
你好，已更新，具体使用请参看文档。感谢
