### ISSUE TITLE
ydui.flexible.js在IOS上，首次打开APP时，出现严重的缩放问题，已在head中引入该文件了

### ISSUE THREAD

**Issue by songGuangHui** [ydcss/vue-ydui#237]
#### 问题描述 

（简明扼要地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by xcsweb** [comment]
麻烦截图

**Comment by songGuangHui** [comment]
偶尔会出现。
感觉是refreshRem ()；这个是在页面初始化完成再执行的，我在
`var recalc = (function refreshRem () {
        var clientWidth = docEl.getBoundingClientRect().width;
        /* 8.55：小于320px不再缩小，11.2：大于420px不再放大 */
        docEl.style.fontSize = Math.max(Math.min(20 * (clientWidth / 750), 11.2), 8.55) * 5 + 'px';
        return refreshRem;
    })();
    **doc.body.style.fontSize = 50 + 'px';`**
缩放的问题，要好点，求教更优的方案

**Comment by ydcss** [comment]
@songGuangHui  请问是使用CDN方式引入会出现严重缩放是吗？

我的方法比较俗。
```html
<div id="app" style="display: none;">
    .............
</div>

<script>
    new Vue({
        el: '#app',
        mounted() {
            this.$el.style.display = 'block';
        }
    })
</script>
````
