### ISSUE TITLE
yd-checkbox 点击事件在谷歌模拟器下会重复执行两次，真机上没问题

### ISSUE THREAD

**Issue by miuqiang** [ydcss/vue-ydui#240]
#### 问题描述 

yd-checkbox   @click.native="checkAll" 点击事件的时候会重复执行两次

#### 测试环境

- **使用版本：0.9.4
- **设备：谷歌模拟器
![qq 20170920141208](https://user-images.githubusercontent.com/19277011/30629303-b4045e9a-9e0d-11e7-877c-d71f26c096c3.png)

**Comment by xcsweb** [comment]
没有重现这个问题，请把代码截完整

**Comment by miuqiang** [comment]
不知道会不会是因为不是全局引入的原因
![qq 20170920153524](https://user-images.githubusercontent.com/19277011/30632099-76c5c42c-9e19-11e7-8505-a9bd96884886.png)

**Comment by xcsweb** [comment]
找到问题了isChecklist3

**Comment by miuqiang** [comment]
不是这个的问题，这个isChecklist3:[]是我拷贝你的demo留下的，原本的代码应该是这样的
![image](https://user-images.githubusercontent.com/19277011/30632633-5d692328-9e1b-11e7-96d9-b14abb5699ca.png)
![qq 20170920155056](https://user-images.githubusercontent.com/19277011/30632670-8c8d8bf8-9e1b-11e7-931e-14c0813234fb.png)

**Comment by ydcss** [comment]
@miuqiang 模拟器调成iPhone试试。
![000](https://user-images.githubusercontent.com/5517400/30633606-dd1432f4-9e1e-11e7-8605-516bbcb2d5b7.png)
![999](https://user-images.githubusercontent.com/5517400/30633611-e37bed8a-9e1e-11e7-8de4-674a104e9da1.png)

**Comment by miuqiang** [comment]
是iPhone，你试了没问题？

**Comment by ydcss** [comment]
@miuqiang 我的浏览器设置成Responsive会出现你说的问题。

**Comment by miuqiang** [comment]
真机上目前没发现
