### ISSUE TITLE
维护者你好，我提问的是用CDN方式安装出现的问题

### ISSUE THREAD

**Issue by JackieZon** [ydcss/vue-ydui#241]
#### 问题描述 

通常使用CDN方式安装的ydui在link标签上已经链接好（ydui.rem.css和ydui.flexible.js）在script链接上（vue.min.js和ydui.js），我使用一般的ydui组件都可以，可我用图片预览的组件就不能正常显示，这是什么原因?

#### 调试环境

pc 谷歌浏览器

**Comment by xcsweb** [comment]
代码请截图

**Comment by ydcss** [comment]
@JackieZon 引入ydui改成这样试试
```html
<link rel="stylesheet" href="https://unpkg.com/vue-ydui@0.9.4/dist/ydui.rem.css">
<script src="https://unpkg.com/vue-ydui@0.9.4/dist/ydui.js"></script>
```

考虑网络原因，建议下载至本地使用哦。
