### ISSUE TITLE
请问下 我用了评分 rate 组件因为active 状态是重后台获取的， 我用循环出来之后报错怎么解决

### ISSUE THREAD

**Issue by xuan1024** [ydcss/vue-ydui#242]
我用了评分 rate 组件因为active 状态是重后台获取的， 我用循环出来之后报错怎么解决：
代码是这样的  
![image](https://user-images.githubusercontent.com/22511126/30641152-8e4ef9b4-9e38-11e7-98f3-a92d2e411b7d.png)

<ul>

<li  v-for="item in detail" >
<yd-cell-item>
<yd-rate slot="left" v-model="item.num" :readonly="true" activeColor="#e36d6d"></yd-rate>
</yd-cell-item>
</li>
</ul>
![image](https://user-images.githubusercontent.com/22511126/30641074-495710bc-9e38-11e7-8278-cb0a4eb235aa.png)

 
效果是出来了，但是报错： 
vue.esm.js?65d7:476 [Vue warn]: Invalid prop: custom validator check failed for prop "value".

found in

---> <YdRate>
       <YdCellItem>
         <YdInfinitescroll>
           <ItemComment> at src\components\itemComment.vue
             <App> at src\App.vue
               <Root>
![image](https://user-images.githubusercontent.com/22511126/30641090-59732d8c-9e38-11e7-8b4c-62fcab3b8508.png)

请问这样改怎么解决。

**Comment by xcsweb** [comment]
页面效果是怎么样的

**Comment by xuan1024** [comment]
![image](https://user-images.githubusercontent.com/22511126/30675602-0ad479d4-9eb4-11e7-8e6c-ed34955daa74.png)

**Comment by ydcss** [comment]
@xuan1024 提示很清楚了啊，v-model绑定的变量格式不正确。/^(([1-9]\d*)|0)$/

**Comment by xuan1024** [comment]
嗯嗯 我知道是v-model 绑定变量不正确，因为我这个地方是要用循环的方式，才能循环出来， 所以想问问有什么方法可以忽略掉这个错误， 或者说还有什么其他的方法可以修正这个错误， 我实在找不到办法了， 试了几种方法都不行， 所以就像问问看看你们有什么解决方案不。

**Comment by ydcss** [comment]
item.num 是怎么值？

**Comment by xuan1024** [comment]
这个是一个数字，  后台传回来的

**Comment by xuan1024** [comment]
item.num 这个是一个数字， 后台传回来的

**Comment by ydcss** [comment]
传回来的“数字” 能通过这个正则吗？ /^(([1-9]\d*)|0)$/

**Comment by xuan1024** [comment]
可以通过这个正则

**Comment by xuan1024** [comment]
这我的项目里， 我所想要的结果出来了， 只是控制台会报错，之前好像没有说清楚， 不好意思

**Comment by xuan1024** [comment]
![image](https://user-images.githubusercontent.com/22511126/30677447-50b9d278-9ebe-11e7-8980-3b5780116e3d.png)
这个是我现在的项目效果， 控制台报错， 效果是出来了的，

**Comment by ydcss** [comment]
item.num确定每个都是数字么？你传个空字符串进去，效果会出来，但是会报错。

**Comment by xuan1024** [comment]
恩恩 这个地方是必填选项 ，但是会有小数，不知道是不是因为这个小数的原因

**Comment by ydcss** [comment]
你的小数可以通过这个正则？/^(([1-9]\d*)|0)$/

**Comment by xuan1024** [comment]
小数也是可以通过这个正则的

**Comment by ydcss** [comment]
这个正则里面连个小数点都没有，怎么可以通过小数的验证呢？

**Comment by xuan1024** [comment]
哦哦  好了 非常感谢， 刚刚让后台改了数据 一下没反应过来， 就回复你了， 太感谢你了，昨晚加班搞了好晚，都没解决， 现在解决了， 太感谢你了
