### ISSUE TITLE
请问下 在使用tab切换里面套了 infinitescroll 滚动加载组件后出现了问题

### ISSUE THREAD

**Issue by xuan1024** [ydcss/vue-ydui#243]
![image](https://user-images.githubusercontent.com/22511126/30682166-126666d6-9edb-11e7-8f2b-e29c71eeb36e.png)
在这个页面上， 我用了tab 切换里面套了 滚动加载组件， 如上图， tab 里面套了两个滚动加载， 需求一个 infinitescroll， 服务一个 infinitescroll， 当我在搜索需求的时候， 滚动加载时，加载到最后一个的时候 loading 并没有消失  如图：

![image](https://user-images.githubusercontent.com/22511126/30682630-e60d539a-9edc-11e7-8e1c-49d3bb7d4690.png)

这个时候当我切换到 服务的时候， 没有进行搜索，直接点进去的时候就显示： 没有更多数据了
![image](https://user-images.githubusercontent.com/22511126/30682786-75eefffe-9edd-11e7-9d2f-1424414c2562.png)

在切换回来的时候：  loading并没有消失，
![image](https://user-images.githubusercontent.com/22511126/30682833-a8029e56-9edd-11e7-9a37-be63af0d93d7.png)

![image](https://user-images.githubusercontent.com/22511126/30682386-138aacd8-9edc-11e7-8eaa-4e3db5ccb70c.png)

我想要的效果是 当我在搜索需求的时候， 滚动加载到最后一个页面时候， 在底部提示 “没有更多数据了”
当我切换到服务的时候，  需求里面的滚动加载不会进来
有没有遇到过这种情况的， 帮忙解决一下， 

![30683221-1a83b4a0-9edf-11e7-8979-aed249f7d889](https://user-images.githubusercontent.com/22511126/30683708-17915552-9ee1-11e7-9f25-b31cc7f59ba8.png)
![30683242-3172af18-9edf-11e7-8202-48ba2f7ad0ac](https://user-images.githubusercontent.com/22511126/30683709-17a42d4e-9ee1-11e7-884f-be179bbf096b.png)

 <yd-tab :callback="togglePanel">
          <yd-tab-panel label="需求" :active="isRequirement">
            <yd-infinitescroll :callback="loadList" ref="infinitescrollDemo">
              <ul class="item-list"  theme="1" slot="list">
                <li v-for="item in requiredData">
                  <router-link   :to="{name: 'detail', query: {id: item.id}}" exact>
                    <div class="list-header">
                      <span class="img-box"><img :src= item.path  alt=""></span>
                      <span class="user-name">{{item.nick_name}}</span>
                      <time>{{item.create_time}}</time>
                    </div>
                    <div class="list-body">
                      <h2>{{item.item_name}}</h2>
                      <p>{{item.item_desc}}</p>
                      <div class="list-footer">
                        <h4><small>赏</small> ￥{{item.item_money}}</h4>
                      </div>
                    </div>
                  </router-link>
                </li>
            </ul>
              
              <span slot="doneTip">没有更多数据了</span>
              
              <img slot="loadingTip" src="http://static.ydcss.com/uploads/ydui/loading/loading10.svg"/>
            </yd-infinitescroll>
          </yd-tab-panel>

          <yd-tab-panel label="服务" :active="isServer">
            <yd-infinitescroll :callback="loadList" ref="infinitescrollDemo">
              <ul class="item-list"  theme="1" slot="list">
                <li v-for="item in requiredData">
                  <router-link to="/serDetail" exact>
                    <div class="list-header">
                      <span class="img-box"><img :src= item.path  alt=""></span>
                      <div class="zx-nick-name zx-clear"><span>{{item.nick_name}}</span><i class="iconfont">&#xe615;</i></div>
                      <time> 成交量：{{item.count}}</time>
                    </div>
                    <div class="list-body">
                      <h2>{{item.service_name}}</h2>
                      <p>{{item.service_desc}}</p>
                      <div class="list-footer">
                        <h4><small></small> {{item.service_money}}</h4>
                      </div>
                    </div>
                  </router-link>
              </li>
            </ul>
            
            <span slot="doneTip">没有更多数据了</span>

            
            <img slot="loadingTip" src="http://static.ydcss.com/uploads/ydui/loading/loading10.svg"/>
            </yd-infinitescroll>
          </yd-tab-panel>

        </yd-tab>

 loadList() {
        this.$http.post(this.GLOBAL.host+ '/public/search', this.option).then(function (response) {
          let list = response.body.data.data;
          this.requiredData = this.requiredData.concat(list);
          if (list.length < this.pageSize || this.option.page == this.total-1) {
            this.$refs.infinitescrollDemo.$emit('ydui.infinitescroll.loadedDone');
            return;
          }
          /* 单次请求数据完毕 */
          this.$refs.infinitescrollDemo.$emit('ydui.infinitescroll.finishLoad');
          this.option.page++;
       
        });
      }

**Comment by xuan1024** [comment]
<yd-tab :callback="togglePanel">
          <yd-tab-panel label="需求" :active="isRequirement">
            <yd-infinitescroll :callback="loadList" ref="infinitescrollDemo">
              <ul class="item-list"  theme="1" slot="list">
                <li v-for="item in requiredData">
                  <router-link   :to="{name: 'detail', query: {id: item.id}}" exact>
                    <div class="list-header">
                      <span class="img-box"><img :src= item.path  alt=""></span>
                      <span class="user-name">{{item.nick_name}}</span>
                      <time>{{item.create_time}}</time>
                    </div>
                    <div class="list-body">
                      <h2>{{item.item_name}}</h2>
                      <p>{{item.item_desc}}</p>
                      <div class="list-footer">
                        <h4><small>赏</small> ￥{{item.item_money}}</h4>
                      </div>
                    </div>
                  </router-link>
                </li>
            </ul>
              
              <span slot="doneTip">没有更多数据了</span>
              
              <img slot="loadingTip" src="http://static.ydcss.com/uploads/ydui/loading/loading10.svg"/>
            </yd-infinitescroll>
          </yd-tab-panel>

          <yd-tab-panel label="服务" :active="isServer">
            <yd-infinitescroll :callback="loadList" ref="infinitescrollDemo">
              <ul class="item-list"  theme="1" slot="list">
                <li v-for="item in requiredData">
                  <router-link to="/serDetail" exact>
                    <div class="list-header">
                      <span class="img-box"><img :src= item.path  alt=""></span>
                      <div class="zx-nick-name zx-clear"><span>{{item.nick_name}}</span><i class="iconfont">&#xe615;</i></div>
                      <time> 成交量：{{item.count}}</time>
                    </div>
                    <div class="list-body">
                      <h2>{{item.service_name}}</h2>
                      <p>{{item.service_desc}}</p>
                      <div class="list-footer">
                        <h4><small></small> {{item.service_money}}</h4>
                      </div>
                    </div>
                  </router-link>
              </li>
            </ul>
            
            <span slot="doneTip">没有更多数据了</span>

            
            <img slot="loadingTip" src="http://static.ydcss.com/uploads/ydui/loading/loading10.svg"/>
            </yd-infinitescroll>
          </yd-tab-panel>

        </yd-tab>


 loadList() {
        this.$http.post(this.GLOBAL.host+ '/public/search', this.option).then(function (response) {
          let list = response.body.data.data;
          this.requiredData = this.requiredData.concat(list);
          if (list.length < this.pageSize || this.option.page == this.total-1) {
            this.$refs.infinitescrollDemo.$emit('ydui.infinitescroll.loadedDone');
            return;
          }
          /* 单次请求数据完毕 */
          this.$refs.infinitescrollDemo.$emit('ydui.infinitescroll.finishLoad');
          this.option.page++;
       
        });
      }

**Comment by xuan1024** [comment]
![image](https://user-images.githubusercontent.com/22511126/30683221-1a83b4a0-9edf-11e7-8979-aed249f7d889.png)

**Comment by xcsweb** [comment]
infinitescroll 滚动组件嵌套在tab的外面

**Comment by xuan1024** [comment]
好的 我试试

**Comment by xuan1024** [comment]
这样套一整个页面都出不来了， 不显示了

**Comment by xcsweb** [comment]
应该是放在tab里面

**Comment by xuan1024** [comment]
现在就是放在tab 里面的呀。yd-tab-panel 里面

**Comment by xcsweb** [comment]
this.$refs.infinitescrollDemo.$emit('ydui.infinitescroll.loadedDone'); 
loading消失是根据这个判断

**Comment by xuan1024** [comment]
嗯嗯 这个我知道， 我在想是不是因为我一个页面出现了两个infinitescrollDemo， 所以它才会跑到第二个tab 里面去显示，而第一个tab  就显示了lodging

**Comment by xcsweb** [comment]
infinitescrollDemo这个命名要不同，对应的js 也是，不能用同一个

**Comment by xuan1024** [comment]
以为我在这里，后台 接口是同一个接口， 所以就写了infinitescrollDemo 两个一样的

**Comment by Zion0707** [comment]
类似楼主发的问题，我也遇到了，就是tab嵌套了两个 不同的滚动加载，就是加入第一个 tab里面的滚动了一页，然后切换到第二个tab那么第二个tab就会一直会出现loading的图标且无法滚动加载了，同时导致另外一边的 滚动加载也无法触发，能否发一个有 tab 两边有滚动加载的案例？

**Comment by Zion0707** [comment]
![image](https://user-images.githubusercontent.com/24251429/36339706-896a2a60-1406-11e8-806c-d5a3190f4612.png)
![image](https://user-images.githubusercontent.com/24251429/36339717-addfa01e-1406-11e8-93c4-bc640d239f27.png)
代码如上图

**Comment by smalllady** [comment]
楼主解决了吗？我遇到了同样的问题

**Comment by smalllady** [comment]
我的是第一个tab下 可以滚动加载，到了第二个向上滑动就不调用这个滚动的方法了！

**Comment by xiaochegnzi0** [comment]
楼主，我想问下，使用infinitescroll，你是怎么自定义布局的？？而不是使用demo里的布局
