### ISSUE TITLE
你好，KeyBoard这个组件上的“输入数字密码”，“取消”，是否可以提供一下这个属性，方便实现i18n。

### ISSUE THREAD

**Issue by liangzhiyuan2015** [ydcss/vue-ydui#246]
#### 问题描述 

（简明扼要地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
你好，已更新，具体使用请参看文档。感谢

**Comment by liangzhiyuan2015** [comment]
好的，谢谢！
