### ISSUE TITLE
请问下 在使用  grids 组件的时候， 当我需要点击的时候，调转到新的页面， 在文档上说是用link，但是我在跳转的同时需要带参数过去，怎么做 

### ISSUE THREAD

**Issue by xuan1024** [ydcss/vue-ydui#247]
请问下 在使用  grids 组件的时候， 当我需要点击的时候，调转到新的页面， 在文档上说是用link，但是我在跳转的同时需要带参数过去，怎么做 ，我试着用 router-link里面的 to 方法 不生效  {name: 'payment', query: {id: this.option.id}} 还报错了，

**Comment by ydcss** [comment]
1、首先我觉得你提issues应该带上具体代码
2、动态参数请用:link
```js 
<yd-grids-item :link="{name: 'payment', query: {id: this.option.id}}">
```

**Comment by xuan1024** [comment]
好的 下次我会注意， 非常感谢您，在百忙之中 解答我的问题，问题解决了， 我本来想用点击事件做了的， 非常感谢

**Comment by xuan1024** [comment]
<yd-grids-item :link="{name: 'apply_payment',query:{id:this.option.id}}">
        <span slot="text">报名参与</span>
      </yd-grids-item>
在使用动态参数时 报错：

![image](https://user-images.githubusercontent.com/22511126/30796673-ac27dc46-a205-11e7-8fa5-e7a3e6b2cf27.png)

this.option.id 是一个数字 后台传回来的

**Comment by ydcss** [comment]
去掉this. 试试。

**Comment by xuan1024** [comment]
还是报错

**Comment by xuan1024** [comment]
一样的错误

**Comment by ydcss** [comment]
不好意思，看错。稍等，我打开项目看看。

**Comment by ydcss** [comment]
是我组件问题，稍后修复。

**Comment by xuan1024** [comment]
好的 非常感谢

**Comment by ydcss** [comment]
你好，问题已修复。 v0.9.5

**Comment by xuan1024** [comment]
嘿嘿，问你个比较low 的问题呀， 希望你不要建议， 我要在本地 npm 在下载更新是吗？

**Comment by ydcss** [comment]
是的呀。

**Comment by xuan1024** [comment]
好的 谢谢

**Comment by ydcss** [comment]
你好，问题解决了吗？

**Comment by xuan1024** [comment]
嗯嗯 刚刚那个问题解决了， 但是我又出现了新的问题
![fy_sgff i zri md](https://user-images.githubusercontent.com/22511126/30799128-635c0092-a20e-11e7-856f-8219215539c9.png)

![qq 20170925162841](https://user-images.githubusercontent.com/22511126/30799189-a2fc7330-a20e-11e7-9325-412a26677313.png)

![image](https://user-images.githubusercontent.com/22511126/30799213-b07ed48a-a20e-11e7-8fd9-4017c46023ae.png)

在刚刚的基础上的这边需求发送了改变， 当我点击报名参与的时候， 要发送一次数据请求， 但是当我发送了数据请求之后，浏览器的url 发生了改变， 我查看了一下组件生成的代码 有一个a标签包裹在yd-grids-txt的最外层，是不是因为这个标签导致了，url发送变化， 如果我不想url 发送变化，我该怎么做？

![image](https://user-images.githubusercontent.com/22511126/30799357-312a9fc4-a20f-11e7-9244-193a68e8f312.png)

**Comment by ydcss** [comment]
1、yd-grids-item不指定link， <span @click="dosomething">报名参与</span>
2、dosomething =》 发送数据请求逻辑不就好了么。

PS：其实这里可以考虑使用yd-flexbox组件（不必使用yd-grids）

**Comment by xuan1024** [comment]
哦哦 好的， 谢谢

**Comment by mzgmail** [comment]
谢谢
