### ISSUE TITLE
当scrolltab左侧的数据过多时， 第二屏的激活状态会失效

### ISSUE THREAD

**Issue by scleean** [ydcss/vue-ydui#250]
我的测试案例中， 左侧为省份， 右侧为城市
第一屏没问题， 滚动右侧， 左侧激活状态是正常和自动切换的。 
但是当左侧被右侧滚动带到第二屏多一点之后，左侧自动切换激活就失效。
请作者检视，看是否是我使用的问题。

**Comment by ydcss** [comment]
你好，现已修复。非常抱歉那么久才修复。
