### ISSUE TITLE
InfiniteScroll加载样式就无法上拉加载,去掉样式就可以

### ISSUE THREAD

**Issue by J3DFox** [ydcss/vue-ydui#251]
![1](https://user-images.githubusercontent.com/29738572/30874094-f00be002-a321-11e7-960c-3aae85342dc6.png)
![2](https://user-images.githubusercontent.com/29738572/30874136-15abb8b4-a322-11e7-99c1-42da0460c05e.png)
直接clone下来一个example也是同样问题。
在线DEMO是正常可以上拉加载的

**Comment by J3DFox** [comment]
顺便补充另外一个问题，当然这个页面也用到了
<yd-backtop></yd-backtop> 返回顶部  一直都是display：none
同样的 不管是克隆的example还是从文档直接copy,也是一样。

**Comment by ydcss** [comment]
使用代码发出来。

**Comment by J3DFox** [comment]
main.js内容如下
`import Vue from 'vue'
import VueRouter from 'vue-router'
import Resource from 'vue-resource';
import VueProgressBar from "vue-progressbar";
import VueLocalStorage from 'vue-localstorage';

import YDUI from 'vue-ydui';
import './vue-ydui/dist/ydui.rem.css';

import Index from './components/index.vue';
import Button from './components/button.vue';
import Dialog from './components/dialog.vue';
import Cell from './components/cell.vue';
import Grids from './components/grids.vue';
import Icons from './components/icons.vue';
import List from './components/list.vue';
import ListTheme from './components/list.theme.vue';
import ListInfinitescroll from './components/list.infinitescroll.vue';
import ListPullRefresh from './components/list.pullrefresh.vue';
import Badge from './components/badge.vue';
import AsideBar from './components/asidebar.vue';
import TabBar from './components/tabbar.vue';
import NavBar from './components/navbar.vue';
import Tabs from './components/tabs.vue';
import Tab from './components/tab.vue';
import ScrollTab from './components/scrolltab.vue';
import ActionSheet from './components/actionsheet.vue';
import SendCode from './components/sendcode.vue';
import ProgressBar from './components/progressbar.vue';
import KeyBoard from './components/keyboard.vue';
import Slider from './components/slider.vue';
import Spinner from './components/spinner.vue';
import CitySelect from './components/cityselect.vue';
import CountDown from './components/countdown.vue';
import Rate from './components/rate.vue';
import Popup from './components/popup.vue';
import CountUp from './components/countup.vue';
import RollNotice from './components/rollnotice.vue';
import Input from './components/input.vue';
import FlexBox from './components/flexbox.vue';
import CR from './components/cr.vue';
import Switch from './components/switch.vue';
import Radio from './components/radio.vue';
import CheckBox from './components/checkbox.vue';
import BackTop from './components/backtop.vue';
import Accordion from './components/accordion.vue';
import DateTime from './components/datetime.vue';
import LightBox from './components/lightbox.vue';
import TimeLine from './components/timeline.vue';
import Step from './components/step.vue';
import CheckList from './components/checklist.vue';

import App from './app.vue';

Vue.use(VueRouter);
Vue.use(Resource);
Vue.use(YDUI);
Vue.use(VueLocalStorage);
Vue.use(VueProgressBar, {
    color: '#ff3366',
    failedColor: 'red',
    thickness: '2px',
});
document.addEventListener('DOMContentLoaded', function() {
    typeof FastClick === 'function' && FastClick.attach(document.body);
}, false);

const router = new VueRouter({
    routes: [
        { path: '/', name: 'index', component: Index },
        { path: '/button', name: 'button', component: Button },
        { path: '/dialog', name: 'dialog', component: Dialog },
        { path: '/cell', name: 'cell', component: Cell },
        { path: '/grids', name: 'grids', component: Grids },
        { path: '/icons', name: 'icons', component: Icons },
        { path: '/list', name: 'list', component: List },
        { path: '/list.theme/:id', name: 'list.theme/:id', component: ListTheme },
        { path: '/list.infinitescroll', name: 'list.infinitescroll', component: ListInfinitescroll },
        { path: '/list.pullrefresh', name: 'list.pullrefresh', component: ListPullRefresh },
        { path: '/badge', name: 'badge', component: Badge },
        { path: '/asidebar', name: 'asidebar', component: AsideBar },
        { path: '/tabbar', name: 'tabbar', component: TabBar },
        { path: '/navbar', name: 'navbar', component: NavBar },
        { path: '/tabs', name: 'tabs', component: Tabs },
        { path: '/tab', name: 'tab', component: Tab },
        { path: '/scrolltab', name: 'scrolltab', component: ScrollTab },
        { path: '/actionsheet', name: 'actionsheet', component: ActionSheet },
        { path: '/sendcode', name: 'sendcode', component: SendCode },
        { path: '/progressbar', name: 'progressbar', component: ProgressBar },
        { path: '/keyboard', name: 'keyboard', component: KeyBoard },
        { path: '/slider', name: 'slider', component: Slider },
        { path: '/spinner', name: 'spinner', component: Spinner },
        { path: '/cityselect', name: 'cityselect', component: CitySelect },
        { path: '/countdown', name: 'countdown', component: CountDown },
        { path: '/rate', name: 'rate', component: Rate },
        { path: '/popup', name: 'popup', component: Popup },
        { path: '/countup', name: 'countup', component: CountUp },
        { path: '/rollnotice', name: 'rollnotice', component: RollNotice },
        { path: '/input', name: 'input', component: Input },
        { path: '/flexbox', name: 'flexbox', component: FlexBox },
        { path: '/cr', name: 'C&R', component: CR },
        { path: '/switch', name: 'switch', component: Switch },
        { path: '/radio', name: 'radio', component: Radio },
        { path: '/checkbox', name: 'checkbox', component: CheckBox },
        { path: '/backtop', name: 'backtop', component: BackTop },
        { path: '/accordion', name: 'accordion', component: Accordion },
        { path: '/datetime', name: 'datetime', component: DateTime },
        { path: '/lightbox', name: 'lightbox', component: LightBox },
        { path: '/timeline', name: 'timeline', component: TimeLine },
        { path: '/step', name: 'step', component: Step },
        { path: '/checklist', name: 'checklist', component: CheckList },
    ]
});

const app = new Vue({
    router: router,
    render: v => v(App)
}).$mount('#app');

let scrollTop = 0;

router.beforeEach((route, redirect, next) => {
    if (redirect.path === '/') {
        scrollTop = document.getElementById('scrollView').scrollTop;
    }
    document.title = 'YDUI Touch - ' + route.name;
    next();
});

router.afterEach(route => {
    if (route.path === '/') {
        Vue.nextTick(() => {
            document.getElementById('scrollView').scrollTop = scrollTop;
        });
    } else {
        document.getElementById('scrollView').scrollTop = 0;
    }
});`

**Comment by J3DFox** [comment]
list.infinitescroll.vue  内容如下
`<template>
    <yd-layout>

        <yd-navbar slot="navbar" title="InfiniteScroll">
            <router-link to="/list" slot="left">
                <yd-navbar-back-icon></yd-navbar-back-icon>
            </router-link>
        </yd-navbar>

        <yd-infinitescroll :callback="loadList" ref="lsdemo">

            <yd-list theme="1" slot="list">
                <yd-list-item v-for="item in list" :key="item.img">

                    <img slot="img" :src="item.img">
                    <span slot="title">{{item.title}}</span>
                    <yd-list-other slot="other">
                        <div>
                            <span class="list-price"><em>¥</em>{{item.marketprice}}</span>
                            <span class="list-del-price">¥{{item.productprice}}</span>
                        </div>
                        <div>content</div>
                    </yd-list-other>
                </yd-list-item>
            </yd-list>

            
            <span slot="doneTip">啦啦啦，啦啦啦，没有数据啦~~</span>

        </yd-infinitescroll>

        <yd-backtop></yd-backtop>
    </yd-layout>
</template>

<script type="text/babel">
    export default {
        data() {
            return {
                page: 1,
                pageSize: 10,
                list: [
                    {
                        img: "http://img1.shikee.com/try/2016/06/23/14381920926024616259.jpg",
                        title: "标题标题标题标题标题",
                        marketprice: 56.23,
                        productprice: 89.36
                    },
                    {
                        img: "http://img1.shikee.com/try/2016/06/21/10172020923917672923.jpg",
                        title: "骆驼男装2016夏装男士短袖T恤 圆领衣服 印花男装体恤 半袖打底衫",
                        marketprice: 56.23,
                        productprice: 89.36
                    },
                    {
                        img: "http://img1.shikee.com/try/2016/06/23/15395220917905380014.jpg",
                        title: "条纹短袖T恤男士韩版衣服大码潮流男装夏季圆领体恤2016新款半袖",
                        marketprice: 56.23,
                        productprice: 89.36
                    },
                    {
                        img: "http://img1.shikee.com/try/2016/06/25/14244120933639105658.jpg",
                        title: "夏季青少年衣服男生潮牌t恤 男士 夏秋学生 日系棉短袖半袖男小衫",
                        marketprice: 56.23,
                        productprice: 89.36
                    },
                    {
                        img: "http://img1.shikee.com/try/2016/06/26/12365720933909085511.jpg",
                        title: "2016夏装新款时尚潮流短袖T恤男纯棉V领日系青少年韩版夏季上衣服",
                        marketprice: 56.23,
                        productprice: 89.36
                    },
                    {
                        img: "http://img1.shikee.com/try/2016/06/19/09430120929215230041.jpg",
                        title: "男装衣服男夏t恤 男士短袖t恤圆领夏季潮牌宽松原宿风半截袖男",
                        marketprice: 56.23,
                        productprice: 89.36
                    },
                    {
                        img: "http://img1.shikee.com/try/2016/06/03/12173920932544716516.jpg",
                        title: "superman短袖t恤日潮牌男士日韩夏装水洗做旧修身个性短袖t恤衣服",
                        marketprice: 56.23,
                        productprice: 89.36
                    },
                    {
                        img: "http://img1.shikee.com/try/2016/09/28/14575020926479478831.jpg",
                        title: "买一送二新款青少年潮男大码T恤 学生字半袖修身款衣服半截袖青年",
                        marketprice: 56.23,
                        productprice: 89.36
                    }
                ]
            }
        },
        methods: {
            loadList() {
                console.log('下拉加载');
                this.$http.jsonp('http://list.ydui.org/getdata.php?type=backposition', {
                    params: {
                        page: this.page,
                        pagesize: this.pageSize
                    }
                }).then(function (response) {
                    setTimeout(() => { // 请求太快了，延迟一下方便看效果！
                        const _list = response.body;

                        this.list = [...this.list, ..._list];

                        if (_list.length < this.pageSize || this.page >= 4) {
                            // 所有数据加载完毕
                            this.$refs.lsdemo.$emit('ydui.infinitescroll.loadedDone');
                            return;
                        }

                        // 单次请求数据完毕
                        this.$refs.lsdemo.$emit('ydui.infinitescroll.finishLoad');

                        this.page++;
                    }, 1000);
                });
            }
        }
    }
</script>
`

**Comment by J3DFox** [comment]
APP.VUE内容如下
`<template>
    <div id="app">
        <vue-progress-bar></vue-progress-bar>
        <router-view></router-view>
    </div>
</template>

<script>
export default {
    name: 'app',
    mounted() {
        //  [App.vue specific] When App.vue is finish loading finish the progress bar
        this.$Progress.finish()
    },
    created() {
        //  [App.vue specific] When App.vue is first loaded start the progress bar
        this.$Progress.start()
        //  hook the progress bar to start before we move router-view
        this.$router.beforeEach((to, from, next) => {
            //  does the page we want to go to have a meta.progress object
            if (to.meta.progress !== undefined) {
                let meta = to.meta.progress
                // parse meta tags
                this.$Progress.parseMeta(meta)
            }
            //  start the progress bar
            this.$Progress.start()
            //  continue to next page
            next()
        })
        //  hook the progress bar to finish after we've finished moving router-view
        this.$router.afterEach((to, from) => {
            //  finish the progress bar
            this.$Progress.finish()
        })
    }
}
</script>

<style lang="less">
    @import "assets/demo.less";
    @import "assets/style.less";
</style></script>
`

**Comment by J3DFox** [comment]
代码除了node_modules部分 都在https://github.com/J3DFox/ydui_issue.git

**Comment by J3DFox** [comment]
代码都是从example复制出来的 但是找不到原因导致 “返回顶部”无法显示出来，“上拉加载” 无法触发
main.js 有 scrollTop

**Comment by J3DFox** [comment]
解决了。

**Comment by J3DFox** [comment]
``<div id="app">
        <vue-progress-bar></vue-progress-bar>
        <router-view></router-view>
    </div>``
假设需要添加一个进度条的时候，就会有问题了

**Comment by ydcss** [comment]
```html
<div id="app" style="height: 100%;"> ... </div>
```
