### ISSUE TITLE
使用ydDatetime时，报错

### ISSUE THREAD

**Issue by leson1986** [ydcss/vue-ydui#252]
![image](https://user-images.githubusercontent.com/3852354/30901001-bc53f6c4-a398-11e7-95eb-8aaca81087ce.png)
![image](https://user-images.githubusercontent.com/3852354/30901025-d2bd6490-a398-11e7-9ec3-7740038fcca7.png)
如上图，图1：
v-model设置了变量名为datetimes，然后设计initEmit=false
图2：
datetimes在声明时，如果设置为空或设置为“2017-01-01 00:00”格式，则正常。但根据需求，这里需要先展示的不是默认某个时间，而是一段提示的内容（如“请输入期望预约时间”），当是其他字符串时，则报错。
**建议作者优化一下。谢谢**
![image](https://user-images.githubusercontent.com/3852354/30901229-7f4b71de-a399-11e7-9529-45ec86e1989f.png)

**Comment by leson1986** [comment]
前端显示效果：
![image](https://user-images.githubusercontent.com/3852354/30901269-ac2f91a8-a399-11e7-9365-6978a5120af6.png)

**Comment by ydcss** [comment]
确实存在缺陷，临时解决可以这样：

```html
<yd-datetime ref="datetime" :initEmit="false" v-model="datetime" style="display: none;"></yd-datetime>

<input type="text" placeholder="请输入期望预约时间" v-model="datetime" readonly @click="open">

open() {
    this.$refs.datetime.open();
}
```

**Comment by leson1986** [comment]
好的，谢谢
