### ISSUE TITLE
省市县级联 设置默认地址的问题

### ISSUE THREAD

**Issue by miuqiang** [ydcss/vue-ydui#254]
请问这样设置为啥无效呢
![image](https://user-images.githubusercontent.com/19277011/30951257-7a05b3ae-a454-11e7-89dd-63fd353894ca.png)

![image](https://user-images.githubusercontent.com/19277011/30951173-1ebe11b2-a454-11e7-990f-61d3a4ed7efd.png)

**Comment by ydcss** [comment]
```html
<yd-cityselect :ready="ready" ...

data() {
   return {
     ready: false
   }
}

this.prpvance = obj.province;
this.city = obj.city;
this.area = obj.district;

this.ready  = true;
```

**Comment by miuqiang** [comment]
谢谢 ，解决了
