### ISSUE TITLE
直接cdn引入ydui.js时 router-link不编译

### ISSUE THREAD

**Issue by weileaf** [ydcss/vue-ydui#259]
<router-link to="#" slot="left">
    <yd-icon name="home" size="25px" color="#777"></yd-icon>
</router-link>
像这个yd-icon正常编译 外层的router-link不编译

**Comment by ydcss** [comment]
去掉 slot="left"

**Comment by ydcss** [comment]
你这里是单独使用，还是使用了其他组件？用到了slot

**Comment by ydcss** [comment]
引入了vue-router吗？

**Comment by ydcss** [comment]
https://router.vuejs.org/zh-cn/essentials/getting-started.html

**Comment by weileaf** [comment]
我自己的问题 打扰了
