### ISSUE TITLE
vue 2.2.6  infinitescroll 组件报错

### ISSUE THREAD

**Issue by ymjdev** [ydcss/vue-ydui#26]
[vue-devtools] Ready. Detected Vue v2.2.6
toConsumableArray.js?1825:19 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at from (native)
    at exports.default (eval at 348 (http://localhost:8080/1.js:218:1), <anonymous>:19:31)
    at eval (eval at 341 (http://localhost:8080/1.js:203:1), <anonymous>:52:206)

**Comment by ydcss** [comment]
请贴出代码。

**Comment by ymjdev** [comment]
this.axios.get(url + '?page=' + this.page + '&size=' + this.pageSize).then((response) => {
          const _list = response.data.result.content;
          this.list = [...this.list, ..._list];
          if (_list.length < this.pageSize || this.page == 5) {
                        // 所有数据加载完毕
                        window.$yduiBus.$emit('ydui.infinitescroll.loadedDone');
                        return;
                    }
                    // 单次请求数据完毕
                    window.$yduiBus.$emit('ydui.infinitescroll.finishLoad');
                    this.page++;
                });
            }

this.page == 5 当this.page 大于5的时候就报上面的错

**Comment by ymjdev** [comment]
我这这边接口到第六页正好没数据就直接报错了

**Comment by ydcss** [comment]
问题不在组件，在于你的方法。请检查 =》 this.list = [...this.list, ..._list];

**Comment by ymjdev** [comment]
接口数据只有5页，如果写 this.page == 6 就会报第一个问题

**Comment by ydcss** [comment]
请问第六页的时候_list=？？？ ，然后[...this.list, ...null]不会报错？？？

**Comment by ymjdev** [comment]
不是很懂，请问怎么解决？感谢

**Comment by ydcss** [comment]
this.list = [...this.list, ...(_list || [])];

**Comment by ymjdev** [comment]
感谢，
