### ISSUE TITLE
datetime组件建议

### ISSUE THREAD

**Issue by Grewer** [ydcss/vue-ydui#260]
现在的 datetime 组件有一个 type属性是控制显示的格式的
type | 时间类型 | String | datetime, date, time | datetime
但是我今天碰到了一个需求是只需要年和月的,其他的不需要;

所以希望作者能修改一下这个字段,比如将 type属性值改成 yyyy/mm/dd这种格式
或者添加最小属性值,比如 min="month"这样, type="date"显示的时间是月以上的;

end;

**Comment by ydcss** [comment]
你好，已修复。
