### ISSUE TITLE
在使用 lightbox 组件的时候 使用用官方demo ，控制弹出警告信息， 怎么去掉，

### ISSUE THREAD

**Issue by xuan1024** [ydcss/vue-ydui#263]
![qq 20171012101405](https://user-images.githubusercontent.com/22511126/31475998-911e7854-af36-11e7-913b-075bd8c9e157.png)

控制台打印：
[HMR] bundle has 1 warnings
147:176 ./~/vue-loader/lib/template-compiler?{"id":"data-v-6a9b7b76","hasScoped":false,"transformToRequire":{"video":"src","source":"src","img":"src","image":"xlink:href"}}!./~/vue-loader/lib/selector.js?type=template&index=0!./src/components/detail.vue
(Emitted value instead of an instance of Error) <yd-lightbox-img v-for="item in detail.pictures">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.
 @ ./src/components/detail.vue 10:0-320
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

使用原路径怎么实现图片预览

**Comment by ydcss** [comment]
v-for should have explicit keys.  https://vuejs.org/guide/list.html#key

![qq 20171012105256](https://user-images.githubusercontent.com/5517400/31476907-88390646-af3b-11e7-93c3-379d8c9bdb69.png)

**Comment by xuan1024** [comment]
哦哦 好的， 我刚刚改了下，控制台警告消除了， 但是实现不了预览的效果 ： 如图， 这个在官网 demo 的截图
![image](https://user-images.githubusercontent.com/22511126/31476971-e36db246-af3b-11e7-93c0-c247c3f73b22.png)

**Comment by ydcss** [comment]
发你的使用代码出来。

**Comment by xuan1024** [comment]
<yd-lightbox class="img-list">
        <span>
          <yd-lightbox-img v-for="(item,index) in detail.pictures" :src="item.url" key="item.index" original></yd-lightbox-img>
        </span>
      </yd-lightbox>

**Comment by ydcss** [comment]
detail.pictures 是异步的数据吗？

**Comment by xuan1024** [comment]
嗯嗯， 页面初始化的时候 加载进来的

**Comment by ydcss** [comment]
注意：若图片数据为异步时，需出入num 的props。

**Comment by xuan1024** [comment]
哦哦  我刚刚看文档 理解为 当预览的图片路径跟缩略图不是同一张图片 才需要输入num,  谢谢 ， 现在解决了

**Comment by xuan1024** [comment]
怎么避免掉， 当后台没有返回数据的时候报错，[Vue warn]: Error in render function: "TypeError: Cannot read property 'length' of undefined"

found in

---> <Detail> at src\components\detail.vue
       <App> at src\App.vue
         <Root>
warn @ 2:477
handleError @ 2:560
Vue._render @ 2:4198
updateComponent @ 2:2575
get @ 2:2918
Watcher @ 2:2907
mountComponent @ 2:2579
Vue$3.$mount @ 2:7982
Vue$3.$mount @ 2:10172
init @ 2:3564
createComponent @ 2:5213
createElm @ 2:5156
createChildren @ 2:5284
createElm @ 2:5189
patch @ 2:5662
Vue._update @ 2:2451
updateComponent @ 2:2575
get @ 2:2918
Watcher @ 2:2907
mountComponent @ 2:2579
Vue$3.$mount @ 2:7982
Vue$3.$mount @ 2:10172
init @ 2:3564
createComponent @ 2:5213
createElm @ 2:5156
patch @ 2:5698
Vue._update @ 2:2451
updateComponent @ 2:2575
get @ 2:2918
Watcher @ 2:2907
mountComponent @ 2:2579
Vue$3.$mount @ 2:7982
Vue$3.$mount @ 2:10172
Vue._init @ 2:4304
Vue$3 @ 2:4389
(anonymous) @ 38:50
(anonymous) @ app.js:946
__webpack_require__ @ app.js:660
fn @ app.js:86
(anonymous) @ app.js:1700
__webpack_require__ @ app.js:660
(anonymous) @ app.js:709
(anonymous) @ app.js:712
2:564 TypeError: Cannot read property 'length' of undefined
    at Proxy.render (111:120)
    at VueComponent.Vue._render (2:4196)
    at VueComponent.updateComponent (2:2575)
    at Watcher.get (2:2918)
    at new Watcher (2:2907)
    at mountComponent (2:2579)
    at VueComponent.Vue$3.$mount (2:7982)
    at VueComponent.Vue$3.$mount (2:10172)
    at init (2:3564)
    at createComponent (2:5213)  代码 还是上面的代码，  当数据库没有图片返回的时候就报错了

<div v-if="detail.pictures!=''">
        <yd-lightbox class="img-list" :num="detail.pictures.length">
        <span>
          <yd-lightbox-img v-for="(item,index) in detail.pictures" :src="item.url" key="item.index" original></yd-lightbox-img>
        </span>
        </yd-lightbox>
      </div>  
我在lightbox 的外层给了一个判断 但是没有用

**Comment by xuan1024** [comment]
![image](https://user-images.githubusercontent.com/22511126/31478093-73030ccc-af40-11e7-814e-af12a417edb1.png)

**Comment by ydcss** [comment]
```html
<yd-listbox class="img-list" :num="detail.pictures ? detail.pictures.length : 0">
```

**Comment by xuan1024** [comment]
好的  谢谢
