### ISSUE TITLE
建议给 slider 组件增加一个 loop 参数

### ISSUE THREAD

**Issue by BarryZhan** [ydcss/vue-ydui#265]
某些场景下，slider 不需要循环，建议增加一个 loop 来自行选择。

**Comment by ydcss** [comment]
你好，已添加loop参数。

**Comment by xjy2016** [comment]
loop参数好像也没用，还是能循环添加，还有就是那个show-pagination这个属性好像不能直接写在组件里面中间有个连接线。

**Comment by xjy2016** [comment]
![Uploading image.png…]()
