### ISSUE TITLE
在使用scrolltab  组件的时候， 不能做循环操作， 

### ISSUE THREAD

**Issue by xuan1024** [ydcss/vue-ydui#267]
![image](https://user-images.githubusercontent.com/22511126/31502502-d7df4da4-af9f-11e7-8801-e5f01d047897.png)

 如图我的左侧菜单是从后台获取的， 是一个动态数据， 我在scrolltab 标签上进行循环， 然后控制台就抛出警告，实现不了循环

 <yd-scrolltab v-for="int in classifylist" :num="int.length">
      <yd-scrolltab-panel :label='int.title 'icon="demo-icons-category1">

[HMR] bundle has 1 warnings
client.js?2c64:176 ./node_modules/_vue-loader@13.2.1@vue-loader/lib/template-compiler?{"id":"data-v-96d4bccc","hasScoped":false,"transformToRequire":{"video":"src","source":"src","img":"src","image":"xlink:href"},"buble":{"transforms":{}}}!./node_modules/_vue-loader@13.2.1@vue-loader/lib/selector.js?type=template&index=0&bustCache!./src/components/HelloWorld.vue
(Emitted value instead of an instance of Error) <yd-scrolltab v-for="int in classifylist">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.
 @ ./src/components/HelloWorld.vue 10:0-402
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by ydcss** [comment]
https://github.com/ydcss/vue-ydui/issues/263
