### ISSUE TITLE
更新到VUE2.5版本后Checkbox的绑定失效

### ISSUE THREAD

**Issue by yundmb** [ydcss/vue-ydui#268]
#### 问题描述 

**1. Checkbox的v-model绑定失效，现在目前只发现这个。**

#### 产生环境

使用版本：VUE2.5 YDUI0.9.7
设备：Iphone 6s
操作系统及版本：**
浏览器及版本：**
演示地址：http://runjs.cn/code/gommxqro

**Comment by yundmb** [comment]
@xmllein

**Comment by yundmb** [comment]
@ydcss

**Comment by ydcss** [comment]
无法重现

**Comment by yundmb** [comment]
http://runjs.cn/code/gommxqro
@ydcss

**Comment by ydcss** [comment]
你好，v0.9.7采用CDN的方式引入确实是有问题。检查了一下，提交到npm出现了问题。我已经重新提交了一次，现已修复。感谢

**Comment by ydcss** [comment]
搞错，问题未解决。

**Comment by ydcss** [comment]
你好，问题已修复。

**Comment by yundmb** [comment]
@ydcss 感谢作者
