### ISSUE TITLE
在Nuxt中引入失败，直接死循环卡死

### ISSUE THREAD

**Issue by zuley** [ydcss/vue-ydui#269]
在Nuxt中以插件的方式引入死循环失败。
## plugins/vue-ydui.js
```
import Vue from 'vue'

import YDUI from 'vue-ydui'
import 'vue-ydui/dist/ydui.rem.css'

Vue.use(YDUI)
```
## nuxt.config.js
```
plugins: [ '~plugins/vue-ydui']
```

**Comment by ydcss** [comment]
(/ □ \) 这个东西没接触过。你可以帮找下问题吗？

**Comment by zuley** [comment]
@ydcss 我知道了，，，Nuxt是会先做一次服务端预编译，有不属于服务端的方法都会报错的。这个需要框架单独做支持，我试了很多其他的UI框架，基本都是不支持。。。

**Comment by cocbin** [comment]
在Nuxt环境下只能判断下是浏览器环境还是服务器环境，然后在引入服务器无法执行的包，如下：
``` js
import Vue from 'vue'
import 'vue-ydui/dist/ydui.rem.css'
if (process.browser) {
  const YDUI = require('vue-ydui')
  Vue.use(YDUI)
}
```

目前只能如此，但是相应的，会报一个服务端和客户端渲染不一致的警告。
如果不需要SEO的话，直接将Nuxt的mode改成spa就行了。
