### ISSUE TITLE
关于省市县级联插件的建议

### ISSUE THREAD

**Issue by yajore** [ydcss/vue-ydui#27]
目前使用的省市区楼主做的用户体验还是很赞的，但是美中不足
比如：这个插件是不是可以扩展为级联选择控件（类似iview的同类插件），比如我其实需要一个车牌地区的级联选择省-市（浙F）这种，没办法扩展了

**Comment by iqfu321** [comment]
拷贝一份自己再改改, 再建一个组件就OK了!

**Comment by ydcss** [comment]
@yajore 组件yd-cityselect现已支持传入自定义数据。
