### ISSUE TITLE
可否解决下 滑动图片的 警告

### ISSUE THREAD

**Issue by wslw** [ydcss/vue-ydui#274]
#### 问题描述 
 在chrome 移动端模式,滑动轮播图组件的时候 ,控制台会报出 
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080
虽然不影响使用,不知道能否屏蔽下这个警告

**Comment by xcsweb** [comment]
console.clear()

**Comment by ydcss** [comment]
@wslw 我也想解决这个问题，但是一直没找到很好的解决办法。

**Comment by wslw** [comment]
我暂时的解决办法就是 把控制台的 warnings 去掉 🙂

**Comment by SupaFan** [comment]
作者能把addEventListener优化下吗 passive: false
