### ISSUE TITLE
在使用 grids 组件的时候， 在组件里面写入a标签做下载功能， 下载功能实现不了

### ISSUE THREAD

**Issue by xuan1024** [ydcss/vue-ydui#276]
因为我这个地方样式跟grids组件的布局一样所以用了这个组件里面套标签

代码如下：  
 <yd-grids-group :rows="3" if="item.contract!= ''" style="padding: .3rem 0;">
                  <yd-grids-item v-for="(n,index) in item.contract" key="n.index">
                    <div slot="else" class="relative upload-file">
                        <a :href="n.real_path" :download="n.file_name" > </a>
                        <img :src="n.img_path" alt="">

                      <p v-if="n.file_type==2">{{n.file_name}}</p>
                    </div>
                  </yd-grids-item>
                </yd-grids-group>
![image](https://user-images.githubusercontent.com/22511126/31652306-3bc60b8c-b351-11e7-84f0-70a277582953.png)

然后用手机浏览器打开， 没反应，

然后我就把代码换了标签

<div class="relative upload-file" v-for="(n,index) in item.contract" key="n.index">
                  <a :href="n.real_path" :download="n.file_name" > </a>
                  <img :src="n.img_path" alt="">
                </div>

![image](https://user-images.githubusercontent.com/22511126/31652355-64ca3490-b351-11e7-9254-1cc9b58c9506.png)

这样才能实现下载功能， 希望能修改一个这个组件

**Comment by ydcss** [comment]
因为yd-grids-item渲染后默认是一个A标签。A标签内部是不能放置A标签的。你可以考虑把你代码中的A标签换成其他标签，通过js触发跳转下载。

**Comment by xuan1024** [comment]
哦哦 ， 谢谢
