### ISSUE TITLE
yd-input不能添加焦点事件

### ISSUE THREAD

**Issue by qingyang117** [ydcss/vue-ydui#278]
#### 问题描述 

引入并应用了yd-input，如果想实现当输入框获得或者失去焦点时执行一系列事件，通过@focus="fn1" @blur="fn2"无法实现，在父级元素上加也不行，添加修饰符也不行

#### 产生环境

 chorme或手机上都无法实现

#### 提示错误信息

无

#### 复现步骤

必现

**Comment by ydcss** [comment]
问题收到。

**Comment by ydcss** [comment]
你好，已添加两个props（onFocus和onBlur）。
