### ISSUE TITLE
网页星形评分组件

### ISSUE THREAD

**Issue by immustard** [ydcss/vue-ydui#280]
yd-rate
activeColor 属性，设置没有效果

**Comment by ydcss** [comment]
代码呢？你这样发谁懂错误在哪？

**Comment by immustard** [comment]
实在不好意思
```<yd-rate slot="left" v-model="rate6" :readonly="true" activeColor="#2172ED" size="0.3rem"></yd-rate>```
已经设置了activeColor，但是没有效果，还是默认色

**Comment by ydcss** [comment]
无法重现你说的。rate6绑定的值是多少？activeColor设置的是选中的颜色，代码不全，所以我猜测你设置了只读，无法修改，也就看不到你设置的activeColor的颜色。修改默认未选中颜色请用color。

**Comment by immustard** [comment]
值绑定的是4，我把只读去掉了默认的红色还是没有改变。
这个是代码：
```
<yd-rate class="rate" slot="left" v-model="rate6" activeColor="#2172ED"></yd-rate>
```
是不是我的写法有问题。。。😅

**Comment by ydcss** [comment]
待我检查下我的代码。你是通过CDN方式引入js的吗？

**Comment by immustard** [comment]
不是。。是直接在github上下载的源码然后导入的。

**Comment by ydcss** [comment]
那我知道了，你用的是新版的vue吧。你改成active-color试试。

**Comment by immustard** [comment]
果然是这个原因。谢谢谢谢！🙏
