### ISSUE TITLE
图片轮播

### ISSUE THREAD

**Issue by immustard** [ydcss/vue-ydui#281]
yd-slider
showPagination="false"
这个属性没有效果

**Comment by ydcss** [comment]
代码呢？你这样发谁懂错误在哪？

**Comment by immustard** [comment]
实在不好意思
<yd-rate slot="left" v-model="rate6" :readonly="true" activeColor="#2172ED" size="0.3rem"></yd-rate>
已经设置了activeColor，但是没有效果，还是默认色

**Comment by immustard** [comment]
sorry sorry
```
<yd-slider autoplay="3000" showPagination="false">
        <yd-slider-item v-for="item in imglist">
          
        </yd-slider-item>
    </yd-slider>
```

**Comment by ydcss** [comment]
showPagination接收的Boolean的值，你这样传的是字符串。你看看你的控制台是不是报错了。
:showPagination="false"

**Comment by immustard** [comment]
哦哦。
已经解决了～
谢谢大神！！
