### ISSUE TITLE
老铁，我怎么感觉你的滚动加载实现的机制是，通过列表距离顶部的距离来判断是否调用loadList方法的啊

### ISSUE THREAD

**Issue by songGuangHui** [ydcss/vue-ydui#286]

**Comment by ydcss** [comment]
准确来说是，列表底部有个元素，根据其判断是否调用loadList。这样实现会有什么问题么？

**Comment by songGuangHui** [comment]
我有个列表，希望当列表一滚动到底部就调用loadList，我这边发现只有当这个列表的顶部距离页面顶部<0时才触发，并不是距离底部的。是不是我写错了？

**Comment by ydcss** [comment]
发你代码来

**Comment by songGuangHui** [comment]
`<yd-infinitescroll :callback="loadList" ref="infinitescrollDemo" class="list-wrap">
	        <yd-list theme="2" slot="list">
	            <a v-for="item, key in list" :key="key" @click="$router.push({path: '/SaleGoodsDetails'})" class="goods-list">
	            	<img slot="img" :src="item.img" class="goods-img">
	            	<div class="right-info">
	            		<div class="top">
	            			<span class="goods-name">{{item.goodsName}}</span>
	            			<span class="distance">{{item.distance}}</span>
	            		</div>
	            		<p class="mid">溯源费：¥{{item.tracePrice}}</p>
	            		<p class="bot">
	            			<i class="address-icon"></i>
	            			<span class="address">{{item.address}}</span>
	            		</p>
	            	</div>
	            </a>
	        </yd-list>
	        
	        <span slot="doneTip">没有更多了</span>
	
	        
	        <img slot="loadingTip" src="http://static.ydcss.com/uploads/ydui/loading/loading10.svg"/>
	    </yd-infinitescroll>`
`<script>
    export default {
    	name: 'SaleGoods',
        data() {
            return {
                page: 1,
                pageSize: 10,
                list: [{
                    img: "/static/images/test/pic-1@3x.png",
                    goodsName: "现摘现卖新鲜梨现摘现卖新鲜梨现摘现卖新鲜梨现摘现卖新鲜梨",
                    distance: "500m",
                    tracePrice: "3",
					address: "余杭区仓前街道海帮园12栋鲜丰水果店余杭区仓前街道海帮园12栋鲜丰水果店"
               	},{
                    img: "/static/images/test/pic-2@3x.png",
                    goodsName: "杭州特产竹笋",
                    distance: "500m",
                    tracePrice: "3",
					address: "余杭区文艺路西西北园农贸市场蔬菜园"
               	},{
                    img: "/static/images/test/pic-3@3x.png",
                    goodsName: "砀山梨",
                    distance: "500m",
                    tracePrice: "3",
					address: "余杭区向往街欧美中心10栋鲜丰水果店"
               	},{
                    img: "/static/images/test/pic-3@3x.png",
                    goodsName: "砀山梨",
                    distance: "500m",
                    tracePrice: "3",
					address: "余杭区向往街欧美中心10栋鲜丰水果店"
               	},{
                    img: "/static/images/test/pic-3@3x.png",
                    goodsName: "砀山梨",
                    distance: "500m",
                    tracePrice: "3",
					address: "余杭区向往街欧美中心10栋鲜丰水果店"
               	},{
                    img: "/static/images/test/pic-3@3x.png",
                    goodsName: "砀山梨",
                    distance: "500m",
                    tracePrice: "3",
					address: "余杭区向往街欧美中心10栋鲜丰水果店"
               	}]
            }
        },
        created(){
        	this.func1();
        },
        methods: {
            loadList() {
                this.func1();
            },
            func1(){
            	console.log(1);
            }
        }
    }
</script>`

**Comment by songGuangHui** [comment]
``<yd-infinitescroll :callback="loadList" ref="infinitescrollDemo" class="list-wrap">
    <yd-list theme="2" slot="list">
        <a v-for="item, key in list" :key="key" @click="$router.push({path: '/SaleGoodsDetails'})" class="goods-list">
        	<img slot="img" :src="item.img" class="goods-img">
        	<div class="right-info">
        		<div class="top">
        			<span class="goods-name">{{item.goodsName}}</span>
        			<span class="distance">{{item.distance}}</span>
        		</div>
        		<p class="mid">溯源费：¥{{item.tracePrice}}</p>
        		<p class="bot">
        			<i class="address-icon"></i>
        			<span class="address">{{item.address}}</span>
        		</p>
        	</div>
        </a>
    </yd-list>
    
    <span slot="doneTip">没有更多了</span>

    
    <img slot="loadingTip" src="http://static.ydcss.com/uploads/ydui/loading/loading10.svg"/>
</yd-infinitescroll>


``<script>
    export default {
    	name: 'SaleGoods',
        data() {
            return {
                page: 1,
                pageSize: 10,
                list: [{
                    img: "/static/images/test/pic-1@3x.png",
                    goodsName: "现摘现卖新鲜梨现摘现卖新鲜梨现摘现卖新鲜梨现摘现卖新鲜梨",
                    distance: "500m",
                    tracePrice: "3",
					address: "余杭区仓前街道海帮园12栋鲜丰水果店余杭区仓前街道海帮园12栋鲜丰水果店"
               	},{
                    img: "/static/images/test/pic-2@3x.png",
                    goodsName: "杭州特产竹笋",
                    distance: "500m",
                    tracePrice: "3",
					address: "余杭区文艺路西西北园农贸市场蔬菜园"
               	},{
                    img: "/static/images/test/pic-3@3x.png",
                    goodsName: "砀山梨",
                    distance: "500m",
                    tracePrice: "3",
					address: "余杭区向往街欧美中心10栋鲜丰水果店"
               	},{
                    img: "/static/images/test/pic-3@3x.png",
                    goodsName: "砀山梨",
                    distance: "500m",
                    tracePrice: "3",
					address: "余杭区向往街欧美中心10栋鲜丰水果店"
               	},{
                    img: "/static/images/test/pic-3@3x.png",
                    goodsName: "砀山梨",
                    distance: "500m",
                    tracePrice: "3",
					address: "余杭区向往街欧美中心10栋鲜丰水果店"
               	},{
                    img: "/static/images/test/pic-3@3x.png",
                    goodsName: "砀山梨",
                    distance: "500m",
                    tracePrice: "3",
					address: "余杭区向往街欧美中心10栋鲜丰水果店"
               	}]
            }
        },
        created(){
        	this.func1();
        },
        methods: {
            loadList() {
                this.func1();
            },
            func1(){
            	console.log(1);
            }
        }
    }
</script>

**Comment by ydcss** [comment]
正常啊 你的代码

**Comment by songGuangHui** [comment]
恩但是只有当list足够多到列表组件，能够滚动到页面顶部才会触发loadList，就算列表已经滚到到底部

**Comment by songGuangHui** [comment]
你是需要滚动区域超过一屏才能调用loadList？

**Comment by ydcss** [comment]
默认列表底部滚动到窗口9/10时就出触发。你看看你的内容满足条件没有？

**Comment by songGuangHui** [comment]
恩好的，应该是没满足，这个可以通过参数设置？

**Comment by ydcss** [comment]
1、第一屏都不满，还有必要加载第二屏？
2、看文档

**Comment by songGuangHui** [comment]
恩好的，多谢了
