### ISSUE TITLE
你这个全选的组件问题

### ISSUE THREAD

**Issue by zhangjun620** [ydcss/vue-ydui#287]
#### 问题描述 

直接复制用的话 好像有bug 在你的demo上操作是正常的 但是代码过来后全选那个按钮 点不了 假如有三个选项 你选了两个 这时候点全选就应该剩下的一个也亮 但是按了全是全部取消。 三个全亮按全选的话正常来说应该是取消全选 但是按了没有反应

#### 产生环境

- **使用版本：npm安装
- **设备：**（手机、平板移动设备）pc，移动
- **操作系统及版本：** win7
- **浏览器及版本：** chrome60
- **演示地址：** 

#### 提示错误信息

1. 没有报错
2. ...

#### 复现步骤

1.  就是源代码 而且没有用其他任何东西 
2. ...

**Comment by ydcss** [comment]
已修复。原官网确实使用和源码都存在问题。
```html
<yd-checkbox v-model="isCheckAll" shape="circle" @click.native="checkAll">

修改为：

<yd-checkbox v-model="isCheckAll" shape="circle" :change="checkAll">
