### ISSUE TITLE
下拉刷新组件bug

### ISSUE THREAD

**Issue by zengzuozuo** [ydcss/vue-ydui#289]
当页面有滚动调时 下拉出刷新图标后不松开手指向上滑将滑动整个页面而下拉图标不会还原，导致再次滑回顶部时刷新图标还保持在原位  chrome调试及安卓真机测试都存在这个问题  ios暂未测试

**Comment by xcsweb** [comment]
这个以前版本修复过，但是新版本又出来了

**Comment by ydcss** [comment]
http://vue.ydui.org/demo/#/list.pullrefresh 这个示例正常吗？
