### ISSUE TITLE
spinner组件是添加一个@change的事件?

### ISSUE THREAD

**Issue by zuoyanart** [ydcss/vue-ydui#29]
现在在做购物车，所以价格会随着数量的变化而变化， 请问作者是怎么考虑这个问题的？如果有必要我可以pull request一份代码过来

**Comment by ydcss** [comment]
监听v-model绑定的变量不就好了？

**Comment by zuoyanart** [comment]
现在的替代方案用的是computed，谢谢作者

**Comment by li9269391** [comment]
v-model 绑定的变量，键盘输入的时候 wacth 监听不到变化，没有 change 事件

**Comment by EverSpring** [comment]
@zuoyanart computed的方法是怎样的，能否给个样例？我用了watch、computed两种方法，但因为返回的json是多层，监听不到里面的变化

**Comment by zuoyanart** [comment]
computed应该不会啊， watch的话需要加参数：deep:true
