### ISSUE TITLE
yd-grids-item里，图片不同宽度，一样会错乱

### ISSUE THREAD

**Issue by leson1986** [ydcss/vue-ydui#294]
代码如下：
 <yd-grids-group :rows="4"  class="yd-ls-ind-grids-group" >
      <yd-grids-item v-for="(items, index) in recommend"
                     :key="items.drug_id"
                     @click.native="medicine(items.drug_id)">
        <img slot="icon" :src="items.drug_pic">
        <span slot="text" v-text="items.drug_name"></span>
      </yd-grids-item>
    </yd-grids-group>
当我上传不同宽高的（即长方形图片）图片时，一样会错乱，我目前的解决方案是在.yd-grids-icon里添加固定宽度，并调整左右空隔。
不知作者有没有更好的解决方案？

**Comment by ydcss** [comment]
http://vue.ydui.org/docs/#/grids
