### ISSUE TITLE
一个问题 一个bug

### ISSUE THREAD

**Issue by zhangjun620** [ydcss/vue-ydui#298]
#### 问题描述 
问题 ： 滚动选项卡的那个可不可以自己改样式换成一个标签一个页面 而不是滚动下去切换标签
bug： checklist 切换 false true的问题 网址：http://vue.ydui.org/demo/#/checklist 点击全选选不了 全部点中倒是变成true了

**Comment by ydcss** [comment]
1、建议自己实现。
2、已修复。原官网确实使用和源码都存在问题。
```html
<yd-checkbox v-model="isCheckAll" shape="circle" @click.native="checkAll">

修改为：

<yd-checkbox v-model="isCheckAll" shape="circle" :change="checkAll">
```

**Comment by zhangjun620** [comment]
感觉没修复完 单独点击全选 下面三个按钮不会被绑定成勾选状态

**Comment by ydcss** [comment]
http://vue.ydui.org/demo/#/checklist 这个示例你看是正常的吗？

**Comment by zhangjun620** [comment]
不正常 有错误 全绿之后想取消不行

**Comment by ydcss** [comment]
这就有点尴尬了。我四个测试机，浏览器均正常。你是用什么版本的浏览器？另外:change在v1.0.5才添加的props。

**Comment by zhangjun620** [comment]
嗯 是正确的 我当时是的时候 没有更新到1.0.5 我浏览器是最新的 现在好了
