### ISSUE TITLE
tabbar 底部点击选中时如何添加激活状态？

### ISSUE THREAD

**Issue by sasonhe** [ydcss/vue-ydui#302]
#### 问题描述 
tabbar 底部点击选中时如何添加激活状态？（作为路由）

**Comment by ydcss** [comment]
设置active-class。

**Comment by sasonhe** [comment]
谢谢，已决绝

**Comment by pyang30** [comment]
怎么解决的啊？            
<yd-tabbar-item title="购物车" type="link" link="/user-add" active-class>
                <yd-icon name="shopcart-outline" slot="icon"></yd-icon>
            </yd-tabbar-item>
这样可以吗？
