### ISSUE TITLE
yd-slider  show-pagination 属性设置false vue报错

### ISSUE THREAD

**Issue by gaohuijuan** [ydcss/vue-ydui#305]
#### 问题描述 

（简明扼要地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
没猜错的话，报错信息是这个吧。“Invalid prop: type check failed for prop "showPagination". Expected Boolean, got String.”

**Comment by gaohuijuan** [comment]
是的，现在问题已经解决了，之前Boolean属性绑定错误了，正确的方式应该是 :show-pagination="false"
