### ISSUE TITLE
datetime

### ISSUE THREAD

**Issue by zjc0828** [ydcss/vue-ydui#306]
能否开发个datetime点击 确定的回调方法，像vux一样，因为在选择日期点击确定时需要计算出天数

**Comment by ydcss** [comment]
监听v-model绑定的变量不就好了么？

**Comment by zjc0828** [comment]
不行吧，我这个选择date完还要选上下午。需要有个方法来调用。

**Comment by zjc0828** [comment]
因为我点击确定后要回调个方法，里面是计算开始跟结束时间，比如3.1,3.2这样

**Comment by zjc0828** [comment]
大神如果知道怎么处理，请指点指点
