### ISSUE TITLE
字体图标

### ISSUE THREAD

**Issue by gaohuijuan** [ydcss/vue-ydui#309]
#### 问题描述 
使用的字体图标，打包在本地运行，默认协议是file://xxx.xx 然后图标就不显示，原来是字体文件没有找到，这种应该怎么解决?
可以将ydui样式里面的字体下载到本地吗，这样的话引用的路径怎么写？查看源码默认的是这种：font-family:YDUI-ICONS;src:url("//at.alicdn.com/t/font_1461139240_0312312.ttf")

**Comment by ydcss** [comment]
http://blog.csdn.net/yaoyyl/article/details/72818971

**Comment by gaohuijuan** [comment]
我自己的字体图标是这样配置的，没有问题，但是有些图标使用的YDUI里面的，这里面的有问题，我是全局的方式引入的 YDUI，ydui.rem.css是在node_modules文件夹下面，此时应该怎么修改路径

**Comment by ydcss** [comment]
你是指只用浏览器直接打开（非服务器的方式打开）你打包后的html，出现“ ERR_FILE_NOT_FOUND: file://at.alicdn.com.....”吗？

**Comment by gaohuijuan** [comment]
是的，就是报的这个错误，因为这个移动端的项目打包转成app之后，打开的文件都是file://xxx开头的，所以导致找不到该文件，有解决的办法吗

**Comment by ydcss** [comment]
建议架设到服务器上预览。

**Comment by huaSoftware** [comment]
@gaohuijuan  指定协议头http。 @ydcss 作者为啥弃更了，很好的一个UI库
