### ISSUE TITLE
请问 是否应该添加单独的checkbox和radiobox组件？

### ISSUE THREAD

**Issue by zuoyanart** [ydcss/vue-ydui#31]
现在单独添加checkbox原生，因为css的原因并不显示， 显示了也不好看。算上一些操作，不如封装一个组件来的方便，请问作者是如何考虑这个问题的？

**Comment by ydcss** [comment]
目前checkbox有yd-switch组件（仅一种样式）。radio和switch其他样式已在规划中。

**Comment by zuoyanart** [comment]
目前觉的ydui很不错，能否把计划中的组件公布出来，然后弄个规范，大家一起参与开发？

**Comment by ydcss** [comment]
你好，组件已添加。
