### ISSUE TITLE
[请教] 请问search组件全屏模式怎么能传递 数据的 id 呢? 

### ISSUE THREAD

**Issue by wslw** [ydcss/vue-ydui#311]
需求描述:
 ydui搜索组件全屏模式,搜索关键字,在下方列出搜索出的关键字列表(此列表我想应该是相关商品的列表),点击某条记录的时候,获取点击记录的 id 进行传递,再次通过 id 查询相关产品信息.

我的现状:
现在搜索后下半部的列表,只能实现文字数组的展示,如果传递 json 数组形式,将显示为json 格式.
希望:
搜索后下半部分显示搜索后的指定字段,比如说名称,点击后传递 id ,希望能给予提示.

**Comment by ydcss** [comment]
设计缺陷，一会修复。

**Comment by ydcss** [comment]
你好，已修复。
result 以对象数组形式传入，其包含label属性即可。
![qq 20171031145314](https://user-images.githubusercontent.com/5517400/32212124-7e2060e0-be50-11e7-912f-0bceb4860cfc.png)
