### ISSUE TITLE
底部导航active-class不生效

### ISSUE THREAD

**Issue by callmesoul** [ydcss/vue-ydui#312]
底部导航active-class不生效一直都是router-link-active，
在vue-router全局配置吧active class改成active，也是还是router-link-active

**Comment by ydcss** [comment]
使用代码发上来！

**Comment by callmesoul** [comment]
@ydcss  
` <yd-tabbar>
      <yd-tabbar-item title="首页" link="/" type="link" active-class="yd-tabbar-active">
        <yd-icon name="home" slot="icon" size="0.54rem"></yd-icon>
      </yd-tabbar-item>
      <yd-tabbar-item title="分类" link="/class" type="link" active-class="yd-tabbar-active">
        <yd-icon name="shopcart" slot="icon" size="0.54rem" link="class" type="link"></yd-icon>
      </yd-tabbar-item>
      <yd-tabbar-item title="书桌" link="/desktop" type="link" active-class="yd-tabbar-active">
        <yd-icon name="shopcart" slot="icon" size="0.54rem"></yd-icon>
      </yd-tabbar-item>
      <yd-tabbar-item title="个人中心" link="/user" type="link" active-class="yd-tabbar-active">
        <yd-icon name="ucenter-outline" slot="icon" size="0.54rem"></yd-icon>
      </yd-tabbar-item>
    </yd-tabbar>`

**Comment by ydcss** [comment]
yd-tabbar-item 没有active-class的props。
