### ISSUE TITLE
rem有问题

### ISSUE THREAD

**Issue by callmesoul** [ydcss/vue-ydui#313]
在chrom下调试，可以发现
选375的ipone6 是html 的font-size为50px.
这是对的，看的出作者是基于750px的设计开发的，html为100px；这样0.12rem=12px
但是我把屏幕改为750px时发现，html并不是100px，而是56px，明显有问题，估计是rem的那个js有问题

**Comment by ydcss** [comment]
为何你不把“那个js”认真看一下？
