### ISSUE TITLE
日期时间插件月底最后一天有点问题

### ISSUE THREAD

**Issue by qingyang117** [ydcss/vue-ydui#314]
每月最后一天的日期有点问题！

`<yd-datetime id="selectDate" v-bind:startDate="当前日期时间" v-bind:endDate="三年后的日期时间" v-model="当前日期后一天的日期时间" :change="writeout(datetime)"></yd-datetime>`
![iss1](https://user-images.githubusercontent.com/25574586/32217733-e3393962-be63-11e7-9ef3-9445a400f467.png)
![iss2](https://user-images.githubusercontent.com/25574586/32217744-eca5eafe-be63-11e7-95ad-62e134964959.png)

今天的日期是2017-10-31，所以v-model绑定的是2017-11-01，但在组件中显示的是2017-11-31，点击弹出的滚动选择栏中默认选中的日期是正确的2017-11-01

请问有什么方法可以解决这个问题

**Comment by ydcss** [comment]
设置 :init-emit="false" 试试。

**Comment by ydcss** [comment]
组件存在问题，尽快修复。

**Comment by ydcss** [comment]
你好，问题已修复。
