### ISSUE TITLE
【建议】省市县级联可以增加到第四级

### ISSUE THREAD

**Issue by foxhunter** [ydcss/vue-ydui#315]
因为业务需要到街道这一个级别，所以跟着说明文档 看到了 ydui-district 这个项目。后来看到这个项目是3个月前更新的。今天研究了下，发现京东提供的数据其实可以到达第四级联动，自己也重新生成了一个含4级的数据js文件。希望作者可以考虑增强一下当前的地址联动组件。

ps：京东现在的接口地址已经变更了，原接口地址获取不到数据了的。

后来想想，甚至可以依据c数组长度 实现无限极选择器，这样可以自主提供ydui-district 这样的结构数据，应用领域就不再只是地址选择了，还可以是具有层级筛选的类别选择等

**Comment by ydcss** [comment]
1、暂时不考虑添加第四级数据，主要原因是yd-cityselect目前是直接引用整个数据文件，包含四级数据文件大小过大，如果将数据文件分开保存，使用又会相对麻烦。

2、很久没维护ydui-district了，待核查。

3、建议你可以自己实现。

**Comment by ydcss** [comment]
京东接口没有变啊。

**Comment by foxhunter** [comment]
抱歉，我是在试图抓第四级的时候 看到xhr 请求地址是https://p.m.jd.com/norder/selectTown.action?idArea=3187，然后网上看以前的请求都是p.m.jd.com, 所以就以为他改变了接口地址。抱歉！
