### ISSUE TITLE
【建议】是否可以去掉yd-grids-item组件中的router-link

### ISSUE THREAD

**Issue by mkgsac** [ydcss/vue-ydui#318]
#### 问题描述 

yd-grids-item组件中用到了router-link，这就要求项目必须使用 vue-router。
可是在有些场景中，项目可能比较小，甚至只有一个页面，没有引入vue-router的必要。
#### 建议
所以，是否可以去掉yd-grids-item组件对router-link的依赖？

**Comment by ydcss** [comment]
是的。你说的非常对。vue-ydui共有5个组件使用了router-link，个别组件使用route-link确实是方便很多，但是也会存在你说的问题。贸然去掉依赖，可能影响较大。相比下，个人觉得暂时不去掉依赖。另外，如果只有一个页面或者项目较小，使用ydui可能不是一个很好的解决方案。

**Comment by mkgsac** [comment]
明白了，非常感谢作者提供这么优秀的框架。👍
