### ISSUE TITLE
在手机APP上，单选列表路由跳转失败

### ISSUE THREAD

**Issue by weixisheng** [ydcss/vue-ydui#319]
#### 问题描述 
有一个cell单选列表，如果存在需要跳转的地方，chrome调试没问题，放到手机无法跳转

#### 产生环境

- **使用版本：1.0.6**
- **设备：安卓模拟器**（手机、平板移动设备）
- **操作系统及版本：win10**
- **浏览器及版本：chrome 63**

#### 提示错误信息
无报错
#### 演示代码
```html
    <yd-cell-item type="radio">
       <div slot="left">
           <p>会员余额 
             <router-link :to="{name:'PwdManage'}"  style="margin-left:.2rem;">设置支付密码</router-link>
            </p>
            <span>(余额支付需要额外支付10%税费)</span>
          </div>
        <input slot="right" type="radio" value="0" v-model="payType" />
      </yd-cell-item>
      <yd-cell-item type="radio">
          <span slot="left">微信支付</span>
          <input slot="right" type="radio" value="1" v-model="payType" />
       </yd-cell-item>
```
![qq 20171101161739](https://user-images.githubusercontent.com/16042305/32265935-3612ea68-bf20-11e7-953e-9733008cdb20.png)

**Comment by ydcss** [comment]
你好，我的几个测试机子都正常。可以考虑将“设置支持密码”可点击区域放大。比如加个padding什么的。

**Comment by weixisheng** [comment]
我试过小米、魅族、安卓模拟器，都不行。但是谷歌调试模式很容易就跳转了。:sob:
加了padding撑的很大了，也不行

**Comment by weixisheng** [comment]
单独判断跳转
