### ISSUE TITLE
0.4.4版本以后 yd-navbar 样式有误

### ISSUE THREAD

**Issue by jarden-liu** [ydcss/vue-ydui#32]
升级0.4.4版本以后  yd-navbar 高度很小
审查元素后发现

header 里面多出了style="background-color: rgb(255, 255, 255); height: 0.9rem;"（0.4.3之前版本没有）

我引入的css是px版本   所以此处style应该使用css样式代替比较好

**Comment by jarden-liu** [comment]
![bug](https://cloud.githubusercontent.com/assets/11712343/24945853/7efa25e8-1f93-11e7-954b-362be02c7d92.png)

**Comment by jarden-liu** [comment]
![bug2](https://cloud.githubusercontent.com/assets/11712343/24946064/396dbbe2-1f94-11e7-866f-018adb36a900.png)

**Comment by ydcss** [comment]
你好，设置style是为了自定义高度。平时开发用的是rem，px是根据rem生成出来的版本。0.4.4之后版本因打包错误导致未能将rem正确转为px。现已修复。

**Comment by jarden-liu** [comment]
0.4.6也还是一样，rem没转换成px

**Comment by ydcss** [comment]
![bug2](http://static.ydcss.com/www/111.png)
