### ISSUE TITLE
CDN引入方式接入，使用js组件(返回顶部)时，js事件调用需要再单独写吗

### ISSUE THREAD

**Issue by adntian** [ydcss/vue-ydui#320]
#### 问题描述 

使用“返回顶部(BackTop)”组件时，`<yd-backtop></yd-backtop>`已经解析为`<div class="yd-backtop"></div>`，可以在滚动后自动显示与隐藏，**但点击不会自动跳转到页面顶部，是否需要自己写函数跳转**

#### 产生环境

- 使用版本：1.0.6   //unpkg.com/vue-ydui/dist/ydui.js
- 设备：微信web开发者工具

#### 代码

```
<div` id="container">
    <yd-cell-group>
        <yd-cell-item>
        </yd-cell-item>
    </yd-cell-group>
    <yd-backtop></yd-backtop>
</div>
```

js代码

```
new Vue({
    el: '#container',
    data: {
        list: res
    }
});
```

> 我使用的是CDN引入方式；没有使用推荐的 npm 来安装动刀太大..
>其它朋友知道的可以帮忙回复一下，谢谢开源的作者和各位朋友

**Comment by ydcss** [comment]
你好，是组件本身问题。现已修复。

**Comment by adntian** [comment]
我也刚发现可以了，本来还想自己去源码里面找出代码提取函数来着，哈哈，谢谢你了
