### ISSUE TITLE
vue-router  改成组件按需加载之后，ydui里面有些按需加载的组件，会有错误

### ISSUE THREAD

**Issue by starm328** [ydcss/vue-ydui#321]
![image](https://user-images.githubusercontent.com/17894731/32317894-6c3e38e2-bff0-11e7-9956-1ad5868d57e7.png)

![image](https://user-images.githubusercontent.com/17894731/32317915-7a6afd56-bff0-11e7-9c09-1927878cb817.png)

这里是表单 在页面中ye-cell-item渲染不出来，还有Popu组件，

**Comment by yajore** [comment]
你看下你的全部流程
main.js需要引用 重置样式 import 'vue-ydui/dist/ydui.base.css';
如果是rem适配还需要引用 <script src="//unpkg.com/vue-ydui/dist/ydui.flexible.js"></script>
然后vue文件中以轮播为例
```javascript
  import {Slider, SliderItem} from 'vue-ydui/dist/lib.rem/slider';

    components: {
      [Slider.name]: Slider,
      [SliderItem.name]: SliderItem
    },

```
