### ISSUE TITLE
我试了一下午了 。。slider的callback 切换后没反应啊。。只有在打开页面时出现

### ISSUE THREAD

**Issue by zhangbird** [ydcss/vue-ydui#324]
#### 问题描述 

（简明扼要地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
使用代码呢？

**Comment by zhangbird** [comment]
<template>
    <div id="goodsinfo">
        <div v-title>商品详情</div>
       
        <div class="sliderbox">
            <yd-slider autoplay="3000" :callback="slider()">
                <yd-slider-item>
                    <a href="#">
                        <img src="./banner@3x.png" class="sliderpic" >
                    </a>
                </yd-slider-item>
                 <yd-slider-item>
                    <a href="#">
                        <img src="./banner@3x.png" class="sliderpic" >
                    </a>
                </yd-slider-item>
                 <yd-slider-item>
                    <a href="#">
                        <img src="./banner@3x.png" class="sliderpic" >
                    </a>
                </yd-slider-item>
                 <yd-slider-item>
                    <a href="#">
                        <img src="./banner@3x.png" class="sliderpic" >
                    </a>
                </yd-slider-item>
            </yd-slider>
        </div>
    </div>
</template>
<script>
export default {
  name:'goodsinfo',
  data(){
    return{

    }
  },
  methods: {
    slider(){
        console.log("11")
    }
  }
};
</script>
<style lang="stylus" rel="stylesheet/stylus">
@import "../../common/stylus/index.styl";


</style>

**Comment by zhangbird** [comment]
<div class="sliderbox">
            <yd-slider autoplay="3000" :callback="slider()">
                <yd-slider-item>
                    <a href="#">
                        <img src="./banner@3x.png" class="sliderpic" >
                    </a>
                </yd-slider-item>
                 <yd-slider-item>
                    <a href="#">
                        <img src="./banner@3x.png" class="sliderpic" >
                    </a>
                </yd-slider-item>
                 <yd-slider-item>
                    <a href="#">
                        <img src="./banner@3x.png" class="sliderpic" >
                    </a>
                </yd-slider-item>
                 <yd-slider-item>
                    <a href="#">
                        <img src="./banner@3x.png" class="sliderpic" >
                    </a>
                </yd-slider-item>
            </yd-slider>
        </div>

**Comment by zhangbird** [comment]
<template>
    <div id="goodsinfo">
        <div v-title>商品详情</div>
       
        <div class="sliderbox">
            <yd-slider autoplay="3000" :callback="slider()">
                <yd-slider-item>
                    <a href="#">
                        <img src="./banner@3x.png" class="sliderpic" >
                    </a>
                </yd-slider-item>
                 <yd-slider-item>
                    <a href="#">
                        <img src="./banner@3x.png" class="sliderpic" >
                    </a>
                </yd-slider-item>
                 <yd-slider-item>
                    <a href="#">
                        <img src="./banner@3x.png" class="sliderpic" >
                    </a>
                </yd-slider-item>
                 <yd-slider-item>
                    <a href="#">
                        <img src="./banner@3x.png" class="sliderpic" >
                    </a>
                </yd-slider-item>
            </yd-slider>
        </div>
    </div>
</template>
<script>
export default {
  name:'goodsinfo',
  data(){
    return{

    }
  },
  methods: {
    slider(){
        console.log("11")
    }
  }
};
</script>
<style lang="stylus" rel="stylesheet/stylus">
@import "../../common/stylus/index.styl";


</style>

**Comment by zhangbird** [comment]
<template>
    <div id="goodsinfo">
        <div v-title>商品详情</div>
        <div class="sliderbox">
            <yd-slider autoplay="3000" :callback="slider()">
                <yd-slider-item>
                    <a href="#">
                        <img src="./banner@3x.png" class="sliderpic" >
                    </a>
                </yd-slider-item>
                 <yd-slider-item>
                    <a href="#">
                        <img src="./banner@3x.png" class="sliderpic" >
                    </a>
                </yd-slider-item>
                 <yd-slider-item>
                    <a href="#">
                        <img src="./banner@3x.png" class="sliderpic" >
                    </a>
                </yd-slider-item>
                 <yd-slider-item>
                    <a href="#">
                        <img src="./banner@3x.png" class="sliderpic" >
                    </a>
                </yd-slider-item>
            </yd-slider>
        </div>
    </div>
</template>
<script>
export default {
  name:'goodsinfo',
  data(){
    return{

    }
  },
  methods: {
    slider(){
        console.log("11")
    }
  }
};
</script>
<style lang="stylus" rel="stylesheet/stylus">
@import "../../common/stylus/index.styl";


</style>

**Comment by zhangbird** [comment]
没怎么用过git 尴尬

**Comment by ydcss** [comment]
没事，我编辑可以看到你的代码。
callback接收的是一个函数，你这样传是函数的返回值啊。改为：
```js
<yd-slider autoplay="3000" :callback="slider">
```

**Comment by zhangbird** [comment]
谢谢了 可以了 
callback的描述是 切换后回调（返回当前页码）
怎么返回当前页码呢 这样写又不能传参 index又不是双向绑定的。。

**Comment by zhangbird** [comment]
额 好像不用 脑子有点乱 我写个循环就行了

**Comment by AlexPeng19** [comment]
@ydcss 我如果想每次滚动图片的时候触发一个事件，是不是不能用这个callback，知道怎么实现吗，求指教。
