### ISSUE TITLE
关于cityselect和actionsheet在IOS上的bug

### ISSUE THREAD

**Issue by yisuo2015** [ydcss/vue-ydui#326]
#### 问题描述 

问题一：CitySelect组件在苹果6上使用有bug（亲测两台I6）。选择“省”时不能向下拖动，没反应。安卓和浏览器测试没有问题。项目建立在企业微信上使用，不知是不是ios版的企业微信的某些脚本限制。

问题二：Actionsheet的效果在苹果上显示也不完美，向下拖动记录时会看得见隐藏的actionsheet div。不过不知道是不是企业微信上使用才是这样子

**Comment by yundmb** [comment]
@ydcss 我也想反馈这个问题，citySelect，在YDUI1.0.8版本下无法滑动，测试在1.0.3可以滑动！1.0.6也不行！希望修复！

**Comment by lishewen** [comment]
也遇到同样的问题

**Comment by ydcss** [comment]
@yisuo2015 @yundmb @lishewen 问题已修复。
