### ISSUE TITLE
选项卡建议

### ISSUE THREAD

**Issue by i5920** [ydcss/vue-ydui#328]
https://detail.m.tmall.com/item.htm?spm=0.0.0.0.bHNz60&id=16202285237&abtest=15&rn=2bdc33aee5deccb9f4f927ce3dee9482&sid=f1f2f3c09b0258d64200fe4c43c7ab66
#### 问题描述 

选中焦点可以选上下

如淘宝这个页面

**Comment by ydcss** [comment]
谢谢你的建议。
