### ISSUE TITLE
下拉刷新和上拉加载可以一起使用吗

### ISSUE THREAD

**Issue by gaohuijuan** [ydcss/vue-ydui#331]
#### 问题描述 
查看官网代码这两个是分开写的，可以一起使用吗?一个列表页面同时支持下拉和上拉
<yd-pullrefresh :callback="loadList" ref="pullrefreshDemo">
        <yd-list theme="4">
         ..........
        </yd-list>
</yd-pullrefresh>

<yd-infinitescroll :callback="loadList" ref="infinitescrollDemo">
        <yd-list theme="1" slot="list">
          ..................
        </yd-list>
</yd-infinitescroll>

**Comment by xcsweb** [comment]
可以

**Comment by gaohuijuan** [comment]
@xcsweb  您好，请问具体怎么结合到一起使用呢？有代码可以参考吗

**Comment by ydcss** [comment]
@gaohuijuan 这样试试。
```html
<yd-pullrefresh :callback="loadList1" ref="prdemo">
    <yd-infinitescroll :callback="loadList2" ref="lsdemo">
        <yd-list slot="list">
            <yd-list-item v-for="item in listData">
                <!-- 两个组件共用 listData -->
            </yd-list-item>
        </yd-list>
    </yd-infinitescroll>
</yd-pullrefresh>
```

**Comment by main2017** [comment]
> ydcss
这样还是行

**Comment by main2017** [comment]
@ydcss 不行耶

**Comment by ydcss** [comment]
@main2017 http://vue.ydui.org/demo/#/list 最下面

**Comment by main2017** [comment]
@ydcss 
我是这样写的，下拉刷新可以，滚动加载不行
<yd-pullrefresh :callback="loadList1" ref="prdemo">

      <yd-infinitescroll :callback="loadList2" ref="lsdemo">
        <yd-list theme="1" slot="list">
          <yd-list-item v-for="item in list">
            <img slot="img" :src="item.img">
            <span slot="title">{{item.title}}</span>
            <yd-list-other slot="other">
              <div>
                <span class="list-price"><em>¥</em>{{item.marketprice}}</span>
                <span class="list-del-price">¥{{item.productprice}}</span>
              </div>
              <div>content</div>
            </yd-list-other>
          </yd-list-item>
        </yd-list>
        <span slot="doneTip">啦啦啦，啦啦啦，没有数据啦~~</span>

      </yd-infinitescroll>
    </yd-pullrefresh>
![td bs5bzq6ofgmk jldwj](https://user-images.githubusercontent.com/28427901/34554392-952a7240-f167-11e7-99b5-463f42138dad.png)

**Comment by ydcss** [comment]
@main2017 新建一个issues，然后把完整代码发来。

**Comment by main2017** [comment]
@ydcss 
就是你这里的代码https://github.com/ydcss/vue-ydui/blob/master/example/routers/list.combination.vue

**Comment by ydcss** [comment]
@main2017 示例也不正常？请自己找问题

**Comment by main2017** [comment]
@ydcss 
好的，谢谢，麻烦了(#^.^#)
