### ISSUE TITLE
图片轮播组件，设置index分页器的样式并没有动态改变

### ISSUE THREAD

**Issue by songGuangHui** [ydcss/vue-ydui#332]
`<yd-slider :index="currentImgIndex" :loop="loop">
	        <yd-slider-item v-for="item in previewImgUrls" :key="item">
	            <img :src="item">
	        </yd-slider-item>
	    </yd-slider>`
`computed: mapState(['previewImgUrls','currentImgIndex']),`
loop： 设置的false

**Comment by ydcss** [comment]
你好，问题已修复。
