### ISSUE TITLE
希望进度条可以支持字体大小，字体颜色等参数

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#339]
#### 问题描述 

希望进度条可以支持字体大小，字体颜色等参数,进度条里面的font-size,color可以修改

- **使用版本：v.9.9
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

**Comment by ydcss** [comment]
自己设置样式不就好了吗？

**Comment by xcsweb** [comment]
临时是这样解决的

**Comment by ydcss** [comment]
yd-progressbar组件提供了slot，可根据实际情况放置相应内容。
示例中的数字，是另外一个组件yd-countup，跟yd-progressbar组件没有关系，yd-progressbar没有文字，所以也就不存在字体大小，字体颜色。
