### ISSUE TITLE
省市县级联  items数据改变不能同步?

### ISSUE THREAD

**Issue by i5920** [ydcss/vue-ydui#340]
District 城市列表我保存到数据库了。异步调用后 数据不能同步到组件上

**Comment by ydcss** [comment]
你好，items目前是不能异步的。

**Comment by ydcss** [comment]
可以尝试通过ready参数实现。初始设置为false，获取列表数据后设置为true即可。

**Comment by i5920** [comment]
那样的话就没法处理地区数据了，想把地址信息用ID 保存是没戏了

**Comment by ydcss** [comment]
你有兴趣的话欢迎帮忙实现。

**Comment by i5920** [comment]
使用ready也没用

**Comment by ydcss** [comment]
更新至最新版，昨天我已经修复了。

**Comment by i5920** [comment]
非常感谢

**Comment by i5920** [comment]
更新后发现使用ready属性依然不能实现
异步加载地区数据，数据没有绑定

**Comment by ydcss** [comment]
我试了是正常的啊。代码如下：
![qq 20171115140306](https://user-images.githubusercontent.com/5517400/32821322-b0e458ec-ca0d-11e7-89b7-66160d7b6721.png)

**Comment by i5920** [comment]
我已经解决了我的问题了.我的请求时间太长了,组件已经渲染了，数据后到的，你的组件没有双向绑定所以一直没法渲染;我在组件上加了v-if判断是否获取到数据，获取到加载组件就解决了问题!!!!!!!!
