### ISSUE TITLE
请问一下 高度是如何使用rem适配呢

### ISSUE THREAD

**Issue by IsSwm** [ydcss/vue-ydui#344]
#### 问题描述 

请问一下 高度是如何使用rem适配呢
来自于[flexible.js的思考](http://vue.ydui.org/docs/#/flexible)

**Comment by IsSwm** [comment]
解决了，高度使用vh~

**Comment by lanrain** [comment]
@IsSwm 能否详细说下高度的vh使用方式，十分感谢
