### ISSUE TITLE
yd-cell-group  --- title传值后台会报错

### ISSUE THREAD

**Issue by leson1986** [ydcss/vue-ydui#348]
#### 问题描述 
如题：在yd-cell-group中，当title直接赋值（传字符串）时，后台不会报错，一切正常
当title赋变量（如-》 :title="newVal")时，前台看好像没影响，但后台报错

**Comment by leson1986** [comment]
图片一直传不上来，有劳大神抽空测试重现

**Comment by ydcss** [comment]
你好，newVal是不是非字符串的值？title只支持String

下面则会报错：
```html
:title="newVal"

data() {
   return { newVal: 555 }
}
```
改为即可：
```html
return { newVal: '555' }
```

**Comment by leson1986** [comment]
好的，谢谢！
