### ISSUE TITLE
使用发送验证码组件时候不能设置按钮的disabled属性

### ISSUE THREAD

**Issue by YuppyChen** [ydcss/vue-ydui#350]
#### 问题描述 

需求：输入完正确的手机号，发送验证码按钮disabled才设置为false，默认设置为true

代码：

<yd-sendcode slot="right"
                       v-model="sendCode"
                       second="10"
                       init-str="获取验证码"
                       run-str="{%s}秒后"
                       reset-str="重新发送"
                       :disabled="disabled"
                       @click.native="sendCode1"
          ></yd-sendcode>

这时候我设置了disabled为true的时候。发送验证码按钮事件还是能执行

**Comment by YuppyChen** [comment]
使用type=“disabled”即可禁用掉发送验证码按钮事件

**Comment by ydcss** [comment]
是的，感谢提出疑问。
