### ISSUE TITLE
滚动选项卡的label问题

### ISSUE THREAD

**Issue by zhangjun620** [ydcss/vue-ydui#352]
#### 问题描述 
里面的label我这里需要v-for出来 但是我试了好像报错的
（尽可能详细地描述一下问题）

#### 产生环境

- **使用版本：** 最新
- **设备：**（手机、平板移动设备） window
- **演示地址：** 

#### 提示错误信息

1. 
![image](https://user-images.githubusercontent.com/24204540/32940218-061b24a2-cbbd-11e7-9e63-f7ac09b401c4.png)

2. ...

#### 复现步骤

1. 
2. ...

**Comment by weixisheng** [comment]
:label="list.gc_name"就行了。这跟YDUI没关系.....

**Comment by zhangjun620** [comment]
哎呀我真的脑子抽了。。问这问题 关了关了
