### ISSUE TITLE
建议Slider组件增加activeItem，这样可以切换到指定的slider-item

### ISSUE THREAD

**Issue by GeekBlue** [ydcss/vue-ydui#356]
#### 问题描述 

当前版本的yd-slider组件并不能切换到指定的slider-item，希望加上这一功能

**Comment by ydcss** [comment]
不是提供了index参数了？

**Comment by AlexPeng19** [comment]
@ydcss 我想问下怎么获取当前图片的索引呢，我想通过程序获取当前显示的是哪张图片。也就是哪个slider-item.
