### ISSUE TITLE
yd-pullrefresh组件下拉行为与手机QQ浏览器默认行为冲突

### ISSUE THREAD

**Issue by GeekBlue** [ydcss/vue-ydui#357]
#### 问题描述 

yd-pullrefresh组件下拉行为与手机QQ浏览器默认行为冲突
建议在组件中阻止浏览器的默认下拉行为

#### 产生环境

- **使用版本：1.1.0-beta-1
- **设备：三星s7 edge
- **演示地址：

**Comment by ydcss** [comment]
你好，问题收到。

**Comment by ydcss** [comment]
你好，问题已修复。
