### ISSUE TITLE
发送验证码，会触发提交按钮

### ISSUE THREAD

**Issue by starm328** [ydcss/vue-ydui#358]
发送验证码按钮，会触发我的form表单，这里能不能吧button  type定义为成Button

**Comment by ydcss** [comment]
你好，问题已修复。通过action-type指定按钮类型。现默认类型为button.

**Comment by starm328** [comment]
yd-sendcode  上面增加action-type  无效
<yd-sendcode	v-model="start1"
	@click.native="sendCode1"
	init-str="获取"
	run-str="{%s}秒后获取"
	reset-str="获取"
	action-type="button"
></yd-sendcode>

**Comment by ydcss** [comment]
你好，我这里使用正常啊。

![qq 20171123152541](https://user-images.githubusercontent.com/5517400/33162111-af4020a6-d062-11e7-9a8b-19b721e7d6ed.png)

![qq 20171123152606](https://user-images.githubusercontent.com/5517400/33162115-b3adff5a-d062-11e7-9d42-8bcd85343329.png)

**Comment by starm328** [comment]
那就奇怪了，我也更新了呀，更新到1.1.0 ，我再看看吧，謝謝
