### ISSUE TITLE
苹果手机在https下无法显示icon图标

### ISSUE THREAD

**Issue by lishewen** [ydcss/vue-ydui#361]
#### 问题描述 

网站采用https时候苹果手机微信内置浏览器无法显示icon图标，在http状态下也可以显示图标，安卓手机和微信开发者工具都不存在此问题

![_201711221431091](https://user-images.githubusercontent.com/837067/33113338-d749ae14-cf4f-11e7-9ff7-10be85bfd456.jpg)

#### 产生环境

- **使用版本：1.1.0
- **设备：iphone6（手机、平板移动设备）
- **演示地址：https://mnh.lishewen.com/#/  

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
搭了一个站点，是正常的。请确认你的服务器配置哦。
https://qwd.ydui.org/lalala#/icons
