### ISSUE TITLE
建议添加Picker

### ISSUE THREAD

**Issue by suyuja** [ydcss/vue-ydui#366]
UI组件写的很好，代码风格很喜欢。
现在好像只有datetime组件不太方便，可以多个picker组件
建议参考https://didi.github.io/cube-ui/#/zh-CN/docs/picker
滚动用better-scroll替换infinitescroll应该更好点 
https://github.com/ustbhuangyi/better-scroll

下拉刷新，目前效果有点丑

**Comment by ydcss** [comment]
谢谢你的建议。
