### ISSUE TITLE
滚动加载

### ISSUE THREAD

**Issue by yaob421123** [ydcss/vue-ydui#367]
#### 问题描述 

当初始数据容器高度小于浏览器高度的时候（数据太少的时候）， `slot="doneTip" ` 无法触发

**Comment by yaob421123** [comment]
小于窗口高度的时候加上这句话是无法触发的，直接 `'$emit' of undefined`， 如果大于当前窗口触发才不会出现问题

**Comment by weixisheng** [comment]
![qq 20171128152719](https://user-images.githubusercontent.com/16042305/33311530-02242fc8-d460-11e7-9aa9-b9e3081e4e46.png)
不至于吧，我这边没出现，估计是你逻辑判断问题

**Comment by ydcss** [comment]
恩，确实是可以的。

```js
//数据加载完毕调用（需要注意的是在 DOM 更新循环之后执行）：
this.$nextTick(() => {
    this.$refs.xxxx.$emit('ydui.infinitescroll.loadedDone');
})
```
