### ISSUE TITLE
关于tab和layout嵌套的问题

### ISSUE THREAD

**Issue by RoseEnd** [ydcss/vue-ydui#37]
你好，现在有这样一个需求，我们希望使用yd-tab的时候有类似layout的布局，选项卡的标题类似navbar, 选项卡内容的一部分类似tabbar请问我该如何实现，谢谢，辛苦了

**Comment by ydcss** [comment]
flex布局不是很好搞定吗？

**Comment by ydcss** [comment]
![bug2](http://static.ydcss.com/www/222.png)

**Comment by RoseEnd** [comment]
你好，我原样尝试过还是不行，而且我是在layout 里面使用yd-tab,选项卡作为layout的内容，其结构类似与layout,选项卡的标题类似navbar, 选项卡内容的一部分类似tabbar

**Comment by ydcss** [comment]
还请你自行尝试，我不解决业务问题。

**Comment by RoseEnd** [comment]
![2](https://cloud.githubusercontent.com/assets/19225061/24998055/6fc37010-206b-11e7-99cf-f7e79264353d.png)
