### ISSUE TITLE
关于ydui.flexible.js，是否可以设置大于420px的手机？

### ISSUE THREAD

**Issue by wujingshi** [ydcss/vue-ydui#371]
使用ydui.flexible.js，很好的适配了手机，但是存在一些问题，就是当用户横向使用手机，或者使用ipad等平板进行访问手机端页面的时候，布局全乱掉了。。。。。

**Comment by ydcss** [comment]
请问页面怎么个乱法？理论上文档宽度不会影响页面布局的。

**Comment by wujingshi** [comment]
图片在横屏下是没办法自动放大的，其他控件可以，切换到ipad整个布局就出现有些适应有些不适应的

**Comment by ydcss** [comment]
有图么？

**Comment by ydcss** [comment]
图片的话，可以考虑使用百分百宽度试试哦。

**Comment by ydcss** [comment]
如要修改 ydui.flexible.js 当然也是可以的哦，将
```js
 docEl.style.fontSize = Math.max(Math.min(20 * (clientWidth / docWidth), 11.2), 8.55) * 5 + 'px';
```
改为：
```js
docEl.style.fontSize = Math.max(20 * (clientWidth / docWidth), 8.55) * 5 + 'px';
```
就不会有限制啦。

![123](https://user-images.githubusercontent.com/5517400/33410286-7ce513d4-d5ba-11e7-853d-a53ef39ffba8.png)

**Comment by wujingshi** [comment]
![2](https://user-images.githubusercontent.com/30532540/33413161-df5ff0a0-d5ca-11e7-922f-dea9c1610baa.png)

但是这样子比例就全乱了，比如我定义了padding20px，但是在实际显示中，就不是20px了。
文档里面写的是100PX=1rem，原型图是750px的，所以实在想不出是哪里问题了。

**Comment by wujingshi** [comment]
已解决
