### ISSUE TITLE
折叠面板点三角符号不会展开啊 事件难道不是哪一整行可点

### ISSUE THREAD

**Issue by ZhaoyangRao** [ydcss/vue-ydui#372]
#### 问题描述 

（尽可能详细地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ZhaoyangRao** [comment]
谷歌上面调试的 折叠面板 点后面的小三角是没反应的 不会触发折叠

**Comment by ydcss** [comment]
你好，问题已修复。
