### ISSUE TITLE
非编译版调用yd-tabbar出错

### ISSUE THREAD

**Issue by neatstudio** [ydcss/vue-ydui#378]
#### 问题描述 

非编译版，直接引用JS，引用的JS是参考本页的：http://vue.ydui.org/docs/demo.html
然后调用其他页面没问题（比如例子里的Dialog，list，等都没有问题）
但是在调用：yd-tabbar 的时候，报错【虽然报错，但内容还是显示出来了】

```
    vue.js:580 [Vue warn]: Unknown custom element: <router-link> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

    found in

    ---> <YdTabbarItem>
           <YdTabbar>
             <Root>
```

#### 产生环境

- **因为是直接使用，所以应该是最新版**
- **设备：** chrome
- **演示地址：** 无

#### 提示错误信息

可能的问题是：
1、因为我不是编译版，而是直接引用了js文件。所以，所有的链接都不可能是 *< route-link >*，所以会报错
2、我应该如何写一个链接呢？

#### 复现步骤
代码结构是从：http://vue.ydui.org/docs/#/tabbar 复制而来？

**Comment by ydcss** [comment]
你好，vue-ydui依赖vue-router，所以需额外引入vue-router。
