### ISSUE TITLE
cell组件的设计是否过于耦合？

### ISSUE THREAD

**Issue by zuoyanart** [ydcss/vue-ydui#38]
单选等的颜色过于耦合cell的样式，比如我想把单选放到left上，则显示不出来了。作者的关于cell的设计思路是什么呢？

**Comment by ydcss** [comment]
你怎么那么喜欢问的我的设计思路或者是怎么考虑的？

**Comment by ydcss** [comment]
好的。之前你问的“请问 是否应该添加单独的checkbox和radiobox组件？”已经有了。以后有什么建议就直接说好了，合理的我自然会改的啊，平时工作也很忙，关于怎么想的，为什么这样设计就不要问啦。我也是一个普普通通的前端，肯定会有设计不合理的。

**Comment by zuoyanart** [comment]
谢谢作者
