### ISSUE TITLE
popup弹窗在苹果手机上 超出内容没有滚动啊  安卓上是正常滚动的 

### ISSUE THREAD

**Issue by ZhaoyangRao** [ydcss/vue-ydui#380]
#### 问题描述 

（尽可能详细地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤
<yd-popup v-model="showpopup" position="center" width="90%" >
          <div class='popup_content'>....</div>
       </yd-popup>

.popup_content{  
     height:10rem;
     background-color:#F5F5F5;     
     border-radius: 2px; 
}
overflow:scroll设置这个也没反应 安卓手机不用设置overflow:scroll应该是继承了滚动
1. 
2. ...

**Comment by ydcss** [comment]
你好，问题已经修复了。忘记说了。
