### ISSUE TITLE
滚动选项卡

### ISSUE THREAD

**Issue by zouru** [ydcss/vue-ydui#382]
![_20171206110718](https://user-images.githubusercontent.com/29558597/33642681-ea65144e-da75-11e7-99a8-43854a2169f0.png)
##

 滚动选项卡没有点击事件

#### 产生环境

- **使用版本：**
- **设备： 谷歌浏览器、手机（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 

2. ...

**Comment by lwl8855** [comment]
请问，左边栏里面的数据是渲染出来的吗，为社么我在:label=“(())”里面的变量渲染不出来

**Comment by zouru** [comment]
是渲染出来的，但是没有事件

**Comment by ydcss** [comment]
是的，目前确实是没有事件响应的，后期修复。

**Comment by zouru** [comment]
嗯

**Comment by anjia0532** [comment]
@ydcss 请问 tabbar 是不是也没有事件？看了一下源码好像是不支持

**Comment by ydcss** [comment]
@zouru 已修复。使用callback解决。
