### ISSUE TITLE
yd-pullrefresh组件，第一次打开APP时，在真机上会有下拉刷新的小手提示，这个怎么禁用掉？

### ISSUE THREAD

**Issue by songGuangHui** [ydcss/vue-ydui#384]
#### 问题描述 

（尽可能详细地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
你好，更新至1.1.4，设置:show-init-tip="false"即可。
