### ISSUE TITLE
滚动加载无法触发回掉函数的问题

### ISSUE THREAD

**Issue by gong135** [ydcss/vue-ydui#386]
#### 问题描述 
引入的<yd-infinitescroll :callback='loadList2' ref='lsdemo'> 这个组件 ，这个回掉函数loadList2无法触发。
（尽可能详细地描述一下问题）

- **设备：**（手机、平板移动设备）

#### 提示错误信息
木有错误提示
#### 复现步骤
<yd-infinitescroll :callback='loadList2' ref='lsdemo'>
        <yd-list theme='1' slot='list'>
          <yd-list-item v-for='item in list'>
            <img slot='img' :src='item.img'>
            <span slot='title'>{{item.title}}</span>
            <yd-list-other slot='other'>
              <div>
                <span class='list-price'>
                  <em>¥</em>{{item.marketprice}}</span>
                <span class='list-del-price'>¥{{item.productprice}}</span>
              </div>
              <div>content</div>
            </yd-list-other>
          </yd-list-item>
        </yd-list>
        <span slot='doneTip'>啦啦啦，啦啦啦，没有数据啦~~</span>
 </yd-infinitescroll>
export default {
  data() {
    return {
      page1: 1,
      page2: 1,
      pageSize: 10,
      list: ['很多数据'],
    };
  },
  methods: {
    loadList2() {
       console.log('滚动到底部触发');
    },
  },
};

**Comment by ydcss** [comment]
你好，请尝试查看yd-infinitescroll父级元素，有没有高度不是100%的。

**Comment by ydcss** [comment]
或者是yd-layout 组件的父级包含了高度不是100%的元素，需手动将其高度设置为100%，否则页面将不能正常滚动。

**Comment by ydcss** [comment]
http://vue.ydui.org/docs/#/layout

**Comment by gong135** [comment]
我没有使用您的 布局方式， 但是我的yd-infinitescroll  其上所有父级元素和祖级元素都都是有高度的！但是父级高度和自己高度一致。 后来我尝试父级高度变成看100vh也没有触发这个回调

**Comment by ydcss** [comment]
你的滚动容器是window还是其他哪个？何不发完整代码更好理解？

**Comment by gong135** [comment]
<template>
  <div>
    <yd-infinitescroll :callback="loadList" ref="infinitescrollDemo">
      <xm-tab class="main-marin" :tabs="tablist" slot="list">
        <div slot="0" class='tab-content'>
          <div v-for="item in 100">{{item}}这是一个div占位</div>
        </div>
      </xm-tab>
      
      <span slot="doneTip">啦啦啦，啦啦啦，没有数据啦~~</span>

      
      <img slot="loadingTip" src="http://static.ydcss.com/uploads/ydui/loading/loading10.svg" />

    </yd-infinitescroll>
  </div>
</template>
<script>
import xmTab from '../../components/tab/tab';

export default {
  data() {
    return {
      tablist: ['我供应', '我需求'],
    };
  },
  components: {
    xmTab,
  },
  methods: {
    loadList() {
      console.log(1);
    },
  },
};
</script>
<style>
.miantop {
  height: 100vh;
}
</style>


容器是window

**Comment by gong135** [comment]
发全部 好像无法显示哟

**Comment by ydcss** [comment]
![qq 20171208135405](https://user-images.githubusercontent.com/5517400/33752880-404fda56-dc1f-11e7-9ad1-e5dc280e3c8f.png)

![qq 20171208135333](https://user-images.githubusercontent.com/5517400/33752889-46aff76e-dc1f-11e7-8b5c-9c11f911dfca.png)

你的代码运行正常。你是哪个版本的vue-ydui?

**Comment by gong135** [comment]
![image](https://user-images.githubusercontent.com/22310462/33752965-cd04ea0e-dc1f-11e7-912b-a05a29049ad7.png)
嗯！ 我这边没有触发。 
我觉得有可能是我布局的问题

**Comment by ydcss** [comment]
把项目托管到github上，帮你调试下。

**Comment by gong135** [comment]
删除这部分代码了！ 自定义成分页了！ 等我修改下

**Comment by gong135** [comment]
https://github.com/gong135/vue-yd.git

**Comment by ydcss** [comment]
恩，调试了好久，是样式设置问题。src\assets\style\index.less 中html和body不可以同时加超出隐藏的，只能加到body，不然滚动事件会没有响应的。例如：
```html
<style>
    html, body {
        height: 100%;
        overflow-x: hidden;
    }
</style>
```
这样是滚动事件是没有响应的。

**Comment by ydcss** [comment]
你可以这样试试（不会有事件响应）：
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        html, body {
            height: 100%;
            overflow-x: hidden;
        }
    </style>
</head>
<body>
<div>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
    <h1>fdsfdsf</h1>
</div>
<script>
    !function () {
        window.addEventListener('scroll', function () {
            console.log('fsjdklfjkslajf');
        })
    }();
</script>
</body>
</html>

```

**Comment by gong135** [comment]
谢谢

**Comment by gong135** [comment]
老师您写的这个demo 有事件响应
![image](https://user-images.githubusercontent.com/22310462/33763937-5845f770-dc4d-11e7-9aeb-30547e6575d2.png)

**Comment by ydcss** [comment]
是的，我写的不严谨。你不要切换手机模式，就可以看清楚了。滚动最底或者最顶会有响应，是因为内部容器触发了body的滚动，但是实际上滚动不是这样的。

你加上这个样式就没事件响应了。
```css
* {
    margin: 0;
    padding: 0;
}
```

**Comment by ydcss** [comment]
![qq 20171208210933](https://user-images.githubusercontent.com/5517400/33767563-0be17188-dc5d-11e7-9285-9535a9e489c9.jpg)
