### ISSUE TITLE
自定义图标无法使用阿里图库的字符编码

### ISSUE THREAD

**Issue by zx107532** [ydcss/vue-ydui#387]
#### 问题描述 

通过自定义图标引入阿里图库的图标后根据阿里图库给的字符编码找不到对应图标，该怎样找啊

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
请问使用代码是什么？

**Comment by zx107532** [comment]
@ydcss 问题找到了，是阿里图库字符编码的问题，但我在VUE里面没法给组件传的值绑定变量

**Comment by zx107532** [comment]
@ydcss 使用底部导航的时候，没办法绑定事件，我如果在外面或里面再套一层标签的话，底部导航里面的Icon会全部失效，不会显示出来

**Comment by ydcss** [comment]
绑定事件用 @click.native。在Vue2.x中，为自定义组件绑定原生事件必须使用修饰符。
