### ISSUE TITLE
弹窗问题，当弹窗大于屏幕，出现滑动，当你滑动到底补取消弹窗，第二次进来就保留了那个位置，这个感觉应该优化一下，进来还是从头显示才符合用户逻辑

### ISSUE THREAD

**Issue by ZhaoyangRao** [ydcss/vue-ydui#388]
#### 问题描述 

（尽可能详细地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
弹窗里面内容是自定义的，yd-popup不会控制其内容。关闭移除DOM，自然会滑动至顶部，这样个人认为是不值得的。

自定义的内容可以考虑自己控制。

另外，提issues，模板有一定规范。
