### ISSUE TITLE
ScrollTab 里面的laber值设置成变量的问题

### ISSUE THREAD

**Issue by lwl8855** [ydcss/vue-ydui#389]
#### 问题描述 

（尽可能详细地描述一下问题）
我在手机端用ScrollTab组件，里面的laber值可以设置为变量值吗 

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
可以的。:label="xxx"

**Comment by lwl8855** [comment]
不行啊，在双大括号里面的变量渲染不出来啊，（（））

**Comment by lwl8855** [comment]
请问，，为社么我在:label=“(())”里面的变量渲染不出来

**Comment by ydcss** [comment]
请问，，为社么不把代码贴出来？

**Comment by lwl8855** [comment]
<li v-for="list in hp.serverlist">
                  <yd-scrolltab-panel  label="{{list.listname}}">
                    <ul v-if="list.pettype">
                      <li class="server-list" v-for="item_l in list.pettype">
                        <div style="height: 100px;background-color: #7e8c8d;">
                          <div @click="show1">
                            <span>{{item_l.petname}}</span><br>
                            <span>星{{item_l.petstar}}</span><br>
                            <span>已服务{{item_l.pserverNum}}次数</span><br>
                            <span>价格{{item_l.price}}</span>
                          </div>
                          <span @click="show2" class="buy">购买</span>
                        </div>
                      </li>
                    </ul>
                  </yd-scrolltab-panel>
                </li>
这里label="{{list.listname}}"，渲染不出来

**Comment by lwl8855** [comment]
ok  已经好了   我自己的问题    谢谢
