### ISSUE TITLE
SendCode组件引用后，点击获取短信的问题

### ISSUE THREAD

**Issue by lwl8855** [ydcss/vue-ydui#390]
#### 问题描述 

（尽可能详细地描述一下问题）
谷歌浏览器调试时，点击获取短信后，控制台报“Cannot read property 'loading' of undefined”

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
是单独引用了yd-sendcode？示例中的$dialog.loading需额外引入dialog组件。
