### ISSUE TITLE
横向nav滚动

### ISSUE THREAD

**Issue by struggle-fish** [ydcss/vue-ydui#391]
大神后期会有横向nav滚动的组件吗。点击nav  nav高亮同时在可视区显示。滚动页面到相应的内容区，nav跟着联动高亮。

**Comment by ydcss** [comment]
确实计划中包含了这个组件。由于最近工作需求缠身，你懂的。。。

**Comment by struggle-fish** [comment]
@ydcss 懂得懂得。大神都注意休息。期待后续。。

**Comment by ydcss** [comment]
@struggle-fish 组件已添加。
