### ISSUE TITLE
为什么总是莫名奇妙的添加一个底部边框?

### ISSUE THREAD

**Issue by leeziiAtCn** [ydcss/vue-ydui#392]
#### 问题描述 

header grid组件等等 会出现一个莫名其妙的底部边框
把相对定位的属性去掉这个边框就没了 请问这是功能还是bug?

#### 产生环境

- **使用版本：*1.1.3*
- **设备：* chrome*（手机、平板移动设备）
- **演示地址：*暂无*

![jietu20171208-153334](https://user-images.githubusercontent.com/22995117/33755734-300e5c86-dc2d-11e7-9804-dfc2ed09d160.png)

**Comment by ydcss** [comment]
http://vue.ydui.org/docs/#/navbar
这个是默认导航的底部边框。文档最下方有说明。

**Comment by leeziiAtCn** [comment]
额 不好意思  找了半天 才给这个边框找到

**Comment by ydcss** [comment]
我看你下方还用到了yd-grids也有边框，建议使用yd-flebox组件。

**Comment by spacecn** [comment]
yd-grids和yd-list也是有边框，建议加一个参数控制是否显示
