### ISSUE TITLE
图片预览插件按要求生成页面比较乱

### ISSUE THREAD

**Issue by zhenlei520** [ydcss/vue-ydui#393]
#### 问题描述 

（尽可能详细地描述一下问题）

#### 产生环境

- **使用版本：1.1.3
- **设备：**iphone6

页面乱了：
图片地址:
http://img.niwotui.cn/test1.jpg
http://img.niwotui.cn/test2.jpg

**Comment by ydcss** [comment]
什么意思？看不懂
