### ISSUE TITLE
YDUI 以前的官网哪去了 几天没上都成了vue的了 ？

### ISSUE THREAD

**Issue by yufengkz** [ydcss/vue-ydui#394]
如题！！1

**Comment by ydcss** [comment]
停掉了。

**Comment by Cirunger** [comment]
额。。。vue还没看     jquery版本不见了。。这就很尴尬了。 。用了一半。。。

**Comment by yufengkz** [comment]
能不能把以前的版本也开一下啊，以前很多项目都用着，停掉感觉不太好啊！
希望开两个版本！

**Comment by Cirunger** [comment]
是啊 旧版可以不更新了。 但是文档要留着呀。

**Comment by ydcss** [comment]
使用方法在示例和源码里面都有。

**Comment by ydcss** [comment]
@Cirunger @yufengkz 已恢复。

**Comment by yufengkz** [comment]
666, 威武大气！！  
很喜欢这个框架！
