### ISSUE TITLE
引入自定义图标，图标无效

### ISSUE THREAD

**Issue by zx107532** [ydcss/vue-ydui#397]
#### 问题描述 

我在vue组件里引入icon时，icon无法显示

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 没有报错，识别了<i>标签，<i data-v-b7c54e72="" class="icon-custom-release" slot="icon" style="font-size: 0.6rem;"></i><i>标签里面为空
2. 

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
代码呢？

**Comment by zx107532** [comment]
@ydcss <template>
  <div class="release" :style="{height:height}">
    <ye-icon name="release" custom slot="icon"></ye-icon>
  </div>
</template>

**Comment by zx107532** [comment]
<template>
  <div class="release" :style="{height:height}">
    <ye-icon name="release" custom slot="icon"></ye-icon>
  </div>
</template>

**Comment by zx107532** [comment]
@ydcss 我邮件发你，你邮箱多少

**Comment by zx107532** [comment]
@ydcss 粘贴出来的代码全部被吃了

**Comment by zx107532** [comment]
@ydcss 跟你在文档里一样，我在我的首页里都还能看到icon，在这个组件里就不能读取了

**Comment by ydcss** [comment]
样式怎么定义的？

**Comment by zx107532** [comment]
@ydcss 
![tim 20171211102011](https://user-images.githubusercontent.com/29188065/33813095-e6e4d170-de5c-11e7-9557-a24047f3154c.png)

**Comment by zx107532** [comment]
@ydcss 
![tim 20171211102110](https://user-images.githubusercontent.com/29188065/33813134-099f23dc-de5d-11e7-9560-ae2da41010d4.png)

**Comment by zx107532** [comment]
@ydcss 我这样引咎识别不到了
![tim 20171211102214](https://user-images.githubusercontent.com/29188065/33813166-2c0cc550-de5d-11e7-99b9-b412e1dfa3ad.png)

**Comment by ydcss** [comment]
这个样式你定义了吗？
```css
.icon-custom-release:before {
     content: '\E606';
}
```

**Comment by zx107532** [comment]
@ydcss 定义了，我试过在我的首页引入这个icon，没问题

**Comment by zx107532** [comment]
@ydcss 
![image](https://user-images.githubusercontent.com/29188065/33813227-77e2c466-de5d-11e7-86b0-9d3137073349.png)

**Comment by ydcss** [comment]
另外 ye-icon 什么鬼？

**Comment by zx107532** [comment]
@ydcss 我改了下名字
![tim 20171211102644](https://user-images.githubusercontent.com/29188065/33813314-cee90fd6-de5d-11e7-9d4b-25e89b4642ac.png)

**Comment by ydcss** [comment]
你使用ye-icon定义的name是release，但是你发的没看见定义的样式啊。
意思是没见你的代码有这个：
```css
.icon-custom-release:before {
     content: '\E606';
}
```

**Comment by zx107532** [comment]
@ydcss 在这里啊
![tim 20171211103022](https://user-images.githubusercontent.com/29188065/33813380-538b0762-de5e-11e7-9675-79c9851021e8.png)

**Comment by ydcss** [comment]
.icon-custom-release 和 .icon-custom-chat 是一样的吗？

**Comment by zx107532** [comment]
@ydcss 嗯嗯，

**Comment by zx107532** [comment]
@ydcss 我试过在底部导航里引入这个iocn，是没有问题的

**Comment by ydcss** [comment]
.icon-custom-release 中的release 要和```html<ye-icon name="release" custom slot="icon"></ye-icon>```中的name值相同

**Comment by zx107532** [comment]
@ydcss 相同的
![tim 20171211103520](https://user-images.githubusercontent.com/29188065/33813491-0315b95c-de5f-11e7-9359-a00d775a7bf2.png)

**Comment by ydcss** [comment]
![qq 20171211103812](https://user-images.githubusercontent.com/5517400/33813535-61fe391c-de5f-11e7-8ad1-e515ae91a88b.png)

**Comment by zx107532** [comment]
@ydcss 不是这个样式，是我刚刚发出来的那个样式

**Comment by zx107532** [comment]
@ydcss 要不你加下我QQ347683567 控屏看下

**Comment by zx107532** [comment]
@ydcss 

![image](https://user-images.githubusercontent.com/29188065/33813715-9f4f3144-de60-11e7-9c27-2bf7f1d525cc.png)

**Comment by ydcss** [comment]
```html
<style>
@font-face {
  font-family: 'XXXXXX';
  src: url('//at.alicdn.com/t/font_500764_0h564cug9kucv7vi.ttf') format('truetype');
}

[class^="icon-custom-"]:before, [class*=" icon-custom-"]:before {
  font-family: 'XXXXXX';
}

.icon-custom-release:before {
  content: '\E65C';
}
</style>

<yd-icon custom name="release"></yd-icon>
```
![qq 20171211104552](https://user-images.githubusercontent.com/5517400/33813722-ad7ad368-de60-11e7-9e3d-393930d656d1.png)

**Comment by ydcss** [comment]
请自己排查错误。

**Comment by zx107532** [comment]
@ydcss 是啊，我在别的地方也能行，就是这不识别了

**Comment by ydcss** [comment]
把 slot="icon"去掉。

**Comment by zx107532** [comment]
@ydcss 还是不行

**Comment by ydcss** [comment]
![123](https://user-images.githubusercontent.com/5517400/33814089-d3a50a48-de62-11e7-9d28-19bfa0bcaca0.png)
![234](https://user-images.githubusercontent.com/5517400/33814092-d96a5654-de62-11e7-83c1-b23046219b5c.png)

请你自己排查，已经花了我近一个小时了。

**Comment by zx107532** [comment]
@ydcss 好吧，谢谢了
