### ISSUE TITLE
发送短信组件 按钮 兼容性问题

### ISSUE THREAD

**Issue by leeziiAtCn** [ydcss/vue-ydui#398]
#### 问题描述 

在ios 9 以上 ip7p 上 按钮显示正常
以上华为全系 按钮均显示异常(uc 微信 等)
oppo uc 正常 原厂浏览器显示异常

#### 产生环境

- **使用版本：*1.1.3*
- **设备：*华为p10 mate 9 10 荣耀xxx  oppo x9*（手机、平板移动设备）
- **演示地址：*暂无*

#### 提示错误信息
无
#### 复现步骤
组件代码是直接复制文档中的 chorme for mac 调试不出来 打包后真机出现此问题

![wechatimg27](https://user-images.githubusercontent.com/22995117/33818961-d206c134-de82-11e7-914a-89162e872d41.jpeg)

**Comment by ydcss** [comment]
可以帮调试下么？没有这些设备。加上这个样式试试。
```css
.yd-btn {
    white-space: nowrap;
}
```

**Comment by leeziiAtCn** [comment]
@ydcss ok
经测试
oppo没问题了
华为uc 原生 uc上没问题了 微信 是这样的 /微笑.
![wechatimg28](https://user-images.githubusercontent.com/22995117/33864346-3d128252-df27-11e7-9707-492423f7800d.jpeg)

![wechatimg28](https://user-images.githubusercontent.com/22995117/33864346-3d128252-df27-11e7-9707-492423f7800d.jpeg)

**Comment by ydcss** [comment]
![qq 20171212103742](https://user-images.githubusercontent.com/5517400/33864651-b6fa17be-df28-11e7-8354-32386a346c97.png)
请问这部分样式是怎么写的？

**Comment by leeziiAtCn** [comment]
在有scope的style标签内复制你发的样式,生效了,其他样式我没动过

**Comment by leeziiAtCn** [comment]
额 在 yd-cell-group 上加了一个    width: 6.5rem;

**Comment by ydcss** [comment]
你好，组件样式在微信下确实存在问题，下次更新修复。临时解决方法如下(给文本框加个width:1%)：
```html
<yd-cell-item>
    ......
    <input slot="right" style="width: 1%;">
    ......
</yd-cell-item>
```

**Comment by leeziiAtCn** [comment]
好的 辛苦了
