### ISSUE TITLE
关于 Slider 组件的异步挂载问题

### ISSUE THREAD

**Issue by viphchok** [ydcss/vue-ydui#4]
请问我如何在进入页面时候，先异步请求数据，获得 dataList = [ ] 后，再挂载 Slider 呢？我试过，但是好像组件有点问题哦。
`<yd-slider autoplay="3000">
                <yd-slider-item v-for="data in dataList">
                    <a :href="data.href">
                        <img :src="data.img">
                    </a>
                </yd-slider-item>
            </yd-slider>`

**Comment by ydcss** [comment]
你好，经核实，确实存在问题，将尽快修复。

**Comment by viphchok** [comment]
我自己改了一下，在父层定义一个 props 值，异步请求数据 list 完毕，v-for 构建结构完毕回调把 props 传进去， slider 组件通过 watch 监听变化再执行 init 方法，我先这么解决哈，期待优化，嘻嘻

**Comment by ydcss** [comment]
已解决，按照你的思路修改的。谢谢！
