### ISSUE TITLE
yd-input的原生事件

### ISSUE THREAD

**Issue by weixisheng** [ydcss/vue-ydui#401]
#### 问题描述 
yd-input的原生input事件，使用过程出现value长度计算失误的现象，代码如下：
```html
<yd-cell-item>
     <span slot="left">消费会员：</span>
     <yd-input slot="right" v-model="mobile" placeholder="请输入会员手机号" type="tel" regex="mobile" @input.native="aa"></yd-input>
      <!-- <input type="tel" slot="right" v-model="mobile" placeholder="请输入会员手机号" @input="aa"> -->
</yd-cell-item>
```

```javascript
methods: {
    aa(){
      console.log(this.mobile.length)
    },
}
```
- yd-input
![qq 20171212175000](https://user-images.githubusercontent.com/16042305/33877935-eb9014ba-df64-11e7-9f42-693624945d30.png)
- input
![qq 20171212175158](https://user-images.githubusercontent.com/16042305/33878033-3ca41234-df65-11e7-8e1a-98ac04f20424.png)

 是组件问题吗？ 还是哪里写的不对

**Comment by ydcss** [comment]
你好，这样试试：
```js
methods: {
    aa() {
       this.$nextTick(() => {
           console.log(this.mobile.length);
       })
    }
}
```
