### ISSUE TITLE
时间组件 在ios下 问题

### ISSUE THREAD

**Issue by 160905** [ydcss/vue-ydui#403]
#### 问题描述 
选择时间的 底部弹框 默认日期不是当前 时间 （iOS 上始终是 2007 年）
（尽可能详细地描述一下问题）
![wechatimg34](https://user-images.githubusercontent.com/22002759/33918663-a07f417c-dfef-11e7-9cac-40c746b62a9d.jpeg)

#### 产生环境
<img width="967" alt="wx20171213-102610 2x" src="https://user-images.githubusercontent.com/22002759/33918934-0182de24-dff1-11e7-959a-d22542e673bb.png">

- **使用版本：**
- **设备：**（手机、平板移动设备）
ihpone 手机
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
设置 :init-emit="true" 试试。

**Comment by zhangxiangliang** [comment]
placeholder 和 init-emit 不能同时一起。
有需求是需要，显示placeholder，点击后时间是当前时间

**Comment by ydcss** [comment]
@zhangxiangliang 
```html
<yd-datetime ref="datetime" :initEmit="false" v-model="datetime" style="display: none;"></yd-datetime>

<input type="text" placeholder="请输入XXX" v-model="datetime" readonly @click="open">

open() {
    this.$refs.datetime.open();
}
```
