### ISSUE TITLE
省市县级联，默认地址写在成功之后赋值，不生效，而直接写在created里面就可以

### ISSUE THREAD

**Issue by wu529778790** [ydcss/vue-ydui#404]
#### 问题描述 
省市县级联，默认地址写在成功之后赋值，不生效，而直接写在created里面就可以

#### 产生环境
Chrome
- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 

#### 复现步骤

  created () {
    this.provance = '上海'  // 在这里是生效的
    this.$http.get('/user/address/info', {
      params: {
        id: this.$route.query.id
      }
    })
      .then((res) => {
       this.provance = '上海'  // 这里不生效
      })
      .catch((err) => {
        console.log(err)
      })
  },

**Comment by ydcss** [comment]
你好，异步数据需要设置参数ready。

```html
<template>
    <yd-cityselect :ready="lalala"></yd-cityselect>
</template>

<script type="text/babel">
    export default {
        data() {
            return {
                lalala: false
            }
        }
    }

    //////......
            .then((res) => {
                this.lalala = true; //获取数据后修改这里
                this.provance = '上海'  // 这里不生效
            })
    ///////.....
</script>

```
