### ISSUE TITLE
ProgressBar 进度条按照官方文档方式进行绑值，进度条无法显示，请教下大神该怎么写

### ISSUE THREAD

**Issue by zjc0828** [ydcss/vue-ydui#405]
![image](https://user-images.githubusercontent.com/25951911/33982279-ec8cbf08-e0ea-11e7-85bc-d16390089986.png)
![image](https://user-images.githubusercontent.com/25951911/33982603-0d602f48-e0ec-11e7-819e-100c07a17a47.png)控制台没有错误。

**Comment by ydcss** [comment]
代码呢？

**Comment by ydcss** [comment]
控制台有错误吗？代码不能截完整一点？

**Comment by ydcss** [comment]
你发的代码看不出问题。请将全部代码发出来。另外，不要修改之前的回复了，新回复一个。

**Comment by zjc0828** [comment]
你这个进度条本身就这些代码，item.distRate这个是取数据库里的值，这跟你文档上说的不是一样的吗，而且我也已经有除以100，让他的值范围在0-1之间

**Comment by ydcss** [comment]
照你发的代码，是没有灰色边框的。是不是你底部的红色容器遮住了？

**Comment by ydcss** [comment]
那么请问这个参数 trail-width="2" 你设置在哪里？

**Comment by zjc0828** [comment]
![image](https://user-images.githubusercontent.com/25951911/33984119-7ac88cec-e0f1-11e7-9a2c-13d70e04d03a.png)
去掉红色的背景了

**Comment by zjc0828** [comment]
trail-width="2" 这个我不是有写成4了

**Comment by ydcss** [comment]
那你的浏览器看这个示例是正常的吗？
http://vue.ydui.org/demo/#/progressbar

**Comment by zjc0828** [comment]
是正常的，

**Comment by ydcss** [comment]
你是用那个版本的vue和vue-ydui呢？

**Comment by zjc0828** [comment]
1.1.0-beta-2  但是我看你在往上面的版本没有对这个组件做修改了

**Comment by ydcss** [comment]
确实是很久没改过这个组件。实在看不出哪里的问题。如果可以的话，把项目托管到github上，我调试一下。

**Comment by zjc0828** [comment]
不好意思，我们公司有签署保密协议，所以。。。。

**Comment by zjc0828** [comment]
你可以自己写个demo试试

**Comment by ydcss** [comment]
在你这个页面上加上这个写死的数据的代码，可以正常显示吗？
```html
<div style="width: 120px;height: 120px;">
    <yd-progressbar
            :progress="0.5"
            trail-width="4"
            stroke-color="#B2B2B2"
            trail-color="#FE5D51"
            fill-color="#EAEAEA"
    >xxx</yd-progressbar>
</div>
```

**Comment by zjc0828** [comment]
不行哦，还是一样

**Comment by ydcss** [comment]
那麻烦你新建一个项目，试试看。看看是不是和你项目的什么东西冲突了。其实我的意思是你可以把你公司的业务逻辑删掉，留下主要部分代码，我就可以方便调试了。

**Comment by ydcss** [comment]
怎么样，新建的项目存在问题吗？
