### ISSUE TITLE
咨询一下，调试过程中一直发现有广告存在

### ISSUE THREAD

**Issue by lxalano** [ydcss/vue-ydui#409]
#### 问题描述 

（尽可能详细地描述一下问题）

#### 产生环境

- **使用版本：**1.1.5beta
- **设备：**（安卓手机、本地调试情况）

#### 提示错误信息

1. 右下角会出现广告
2. ...

#### 复现步骤

1. 本地调试情况/手机查看演示情况
2. ...
引用库是否遭到污染/或者有什么情况

**Comment by ydcss** [comment]
为何考虑是vue-ydui的广告？建议自行查看源码。
