### ISSUE TITLE
cityselect组件，单词拼写错误

### ISSUE THREAD

**Issue by zuoyanart** [ydcss/vue-ydui#41]
`methods: {
            result1(ret) {
                this.model1 = ret.provance + ' ' + ret.city + ' ' + ret.area;
            }
        }`

应为： province

**Comment by ydcss** [comment]
你好，好仔细哇！[https://github.com/ydcss/vue-ydui/issues/6](https://github.com/ydcss/vue-ydui/issues/6)，原来也有人提出来了。暂且将错就错吧！

**Comment by zuoyanart** [comment]
哦， 可以在文档里加个说明，免得再有人提

**Comment by ydcss** [comment]
发 issue 前应搜索一下哟！
