### ISSUE TITLE
自定义的icon在tabber无法使用

### ISSUE THREAD

**Issue by 13678460136** [ydcss/vue-ydui#410]
成功自定义icon图标能够在任何页面使用 唯独在tabbar里无法使用
<yd-icon name="xuehua" custom></yd-icon>
这个自定义图标只要不在tabbar就可以显示

**Comment by ydcss** [comment]
注意在yd-tabbar-item中使用需要指定slot="icon"。

**Comment by 13678460136** [comment]
指定slot=“icon” 后 整个yd-tabbar-item 将不会被渲染

**Comment by 13678460136** [comment]
template 代码
<yd-tabbar slot="tabbar" bgcolor="#212121" activeColor="#33749E">
                <yd-tabbar-item title="测试" link="#" :active="index==0"  slot="icon">
                    <yd-icon name="xuehua" custom  size="0.54rem"></yd-icon>
                </yd-tabbar-item>
</yd-layout>

css 代码
@font-face {
  font-family: "iconfont";
  src: url('iconfont.eot?t=1513310354202');
  /* IE9*/
  src: url('iconfont.eot?t=1513310354202#iefix') format('embedded-opentype'), /* IE6-IE8 */
}
.iconfont {
  font-family:"iconfont" !important;
  font-size:16px;
  font-style:normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

[class^="icon-custom-"]:before,
[class*=" icon-custom-"]:before {
  font-family: 'iconfont';
}

[class^="yd-icon-"]:before,
[class*=" yd-icon-"]:before {
  font-family: 'iconfont'!important;
}
.yd-icon-xuehua:before {
  content: "\e66f";
}
.icon-custom-xuehua:before { content: "\e66f"; }

**Comment by ydcss** [comment]
```html
<yd-tabbar slot="tabbar" bgcolor="#212121" activeColor="#33749E">
                <yd-tabbar-item title="测试" link="#" :active="index==0">
                    <yd-icon name="xuehua" custom  size="0.54rem"  slot="icon"></yd-icon>
                </yd-tabbar-item>
</yd-layout>
```

**Comment by 13678460136** [comment]
template的代码 好像消失了 再发一次
<yd-tabbar slot="tabbar" bgcolor="#212121" activeColor="#33749E">
                <yd-tabbar-item title="测试" link="#" :active="index==0"  slot="icon">
                    <yd-icon name="xuehua" custom  size="0.54rem"></yd-icon>
                </yd-tabbar-item>
</yd-tabbar>

**Comment by ydcss** [comment]
slot是指定yd-icon，不是yd-tabbar-item。

**Comment by 13678460136** [comment]
ok  解决了

**Comment by ydcss** [comment]
下次提issues麻烦直接带上代码。几句话看不出问题的。
