### ISSUE TITLE
请问下我在使用datetime的时候怎么让蚊子居右

### ISSUE THREAD

**Issue by tx123456** [ydcss/vue-ydui#411]
#### 问题描述 

（尽可能详细地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤
在使用datetime的时候文字是默认居左的，有什么办法让文字句右吗
在yd-cell-item中用的话设置text-align: right无效

**Comment by ydcss** [comment]
因为是flexbox布局的。text-align是无效的。设置justify-content: flex-end;试试。
