### ISSUE TITLE
请问下有带输入框的对话框吗

### ISSUE THREAD

**Issue by tx123456** [ydcss/vue-ydui#412]
#### 问题描述 

（尽可能详细地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

请问下有带输入框的对话框吗

**Comment by ydcss** [comment]
可以考虑看看yd-popup组件。
