### ISSUE TITLE
左侧弹窗内的联系人列表bug

### ISSUE THREAD

**Issue by yaowenbin** [ydcss/vue-ydui#413]
#### 问题描述 
左侧展开的弹窗内使用了搜索框UI，唤起键盘后，联系人列表的底部被输入法顶起留下了底部空白，输入法关闭后，底部无法还原，
（尽可能详细地描述一下问题）

#### 产生环境
微信浏览器，
- **使用版本：** 版本1.1.5
- **设备：**（手机、平板移动设备） 安卓小米note3，ios设备ok，希望作者能修复
              
- **演示地址：**

#### 提示错误信息

1.   联系人列表在搜索后底部留下和输入法键盘等高的空白
2. ...

#### 复现步骤

1.   左侧弹窗，搜索
2.   取消搜索后，联系人列表留下空白无法还原

**Comment by ydcss** [comment]
没看明白什么意思？发代码来看看。
