### ISSUE TITLE
在使用<yd-layout>ydui 的布局情况下无法使用window.srcoll事件

### ISSUE THREAD

**Issue by 13678460136** [ydcss/vue-ydui#414]
#### 问题描述 
项目在使用<yd-layout>的情况 添加的window.scroll事件无法执行
#### 产生环境
"vue-ydui": "^1.1.5",
chrome浏览器
#### 提示错误信息
无错误信息
#### 复现步骤
<template>
    <yd-layout title="啦啦啦啦" link="#">
        
        <div>乱七八糟的内容在这里，超出容器，将出现滚动条。</div>
        <div>乱七八糟的内容在这里，超出容器，将出现滚动条。</div>
        <div>乱七八糟的内容在这里，超出容器，将出现滚动条。</div>

        <yd-tabbar slot="tabbar">
            <yd-tabbar-item title="首页" link="#">
                <yd-icon name="home" slot="icon"></yd-icon>
            </yd-tabbar-item>
            <yd-tabbar-item title="购物车" link="#" active>
                <yd-icon name="shopcart" slot="icon"></yd-icon>
            </yd-tabbar-item>
            <yd-tabbar-item title="个人中心" link="#">
                <yd-icon name="ucenter-outline" slot="icon"></yd-icon>
            </yd-tabbar-item>
        </yd-tabbar>

    </yd-layout>
</template>
<script>
    export default {
        methods:{
            handleScroll(){
                console.log(1);
            }
        },
        mounted(){
            window.addEventListener('scroll',this.handleScroll())
        }
    }
</script>

#### 以上代码得到实际效果
handleScroll()函数只被调用执行了一次
#### 期望实现效果
handleScroll() 函数能在滚动时被循环调用

**Comment by ydcss** [comment]
组件 yd-layout 预留了一个id（scrollView），可以使用document.getElementById('scrollView').addEventListener('scroll',this.handleScroll());
