### ISSUE TITLE
yd-grids-group中点击yd-grids-item会刷新界面

### ISSUE THREAD

**Issue by tx123456** [ydcss/vue-ydui#416]
#### 问题描述 

（尽可能详细地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

我在使用yd-grids-group的时候发现点击yd-grids-item会刷新界面，我不想让他刷新界面该怎么办

**Comment by ydcss** [comment]
怎么会跳转？你设置yd-grids-item的href是什么？麻烦贴代码出来。

**Comment by tx123456** [comment]
<div class="margin-l-10 margin-r-10">
                <yd-grids-group :rows="4">
                    <yd-grids-item type="a">
                        <div class="padded-3" slot="else">
                            <img class="img_center width-z100" :src="img_jiedie"
                                 onerror="this.src='../../image/img_error.png'">
                        </div>
                    </yd-grids-item>
                    <yd-grids-item type="a" @click.native="add_img('add_jiedie_win')">
                        <div class="padded-3" slot="else">
                            <img class="img_center width-z100"
                                 src="../../image/ic_add.png" >
                        </div>
                    </yd-grids-item>
                </yd-grids-group>
            </div>

我现在这样写点击他的griditems页面会执行刷新操作，
我现在的方法是用jquery移除他的href,请问下有没有更好的方法

**Comment by tx123456** [comment]
<div class="margin-l-10 margin-r-10">
                <yd-grids-group :rows="4">
                    <yd-grids-item type="a">
                        <div class="padded-3" slot="else">
                            <img class="img_center width-z100" :src="img_jiedie"
                                 onerror="this.src='../../image/img_error.png'">
                        </div>
                    </yd-grids-item>
                    <yd-grids-item type="a" @click.native="add_img('add_jiedie_win')">
                        <div class="padded-3" slot="else">
                            <img class="img_center width-z100"
                                 src="../../image/ic_add.png" >
                        </div>
                    </yd-grids-item>
                </yd-grids-group>
            </div>

**Comment by tx123456** [comment]
``<div class="margin-l-10 margin-r-10">
                <yd-grids-group :rows="4">
                    <yd-grids-item type="a">
                        <div class="padded-3" slot="else">
                            <img class="img_center width-z100" :src="img_jiedie"
                                 onerror="this.src='../../image/img_error.png'">
                        </div>
                    </yd-grids-item>
                    <yd-grids-item type="a" @click.native="add_img('add_jiedie_win')">
                        <div class="padded-3" slot="else">
                            <img class="img_center width-z100"
                                 src="../../image/ic_add.png" >
                        </div>
                    </yd-grids-item>
                </yd-grids-group>
            </div>

**Comment by ydcss** [comment]
你看渲染后的DOM就知道了，解决方法如下：
```html
<yd-grids-item type="a" href="javascript:;">
```
