### ISSUE TITLE
yd-popup和yd-cityselect整合错误

### ISSUE THREAD

**Issue by wujay77** [ydcss/vue-ydui#422]
`<yd-popup v-model="seenSearch" position="right" width="90%">
            <yd-cell-group>
                <yd-cell-item arrow>
                    <span slot="left">所在地区：</span>
                    <input slot="right" type="text" @click.stop="showCityselect = true" v-model="cityselectModel"
                           placeholder="请选择地址">
                </yd-cell-item>
                <yd-cityselect
                        v-model="showCityselect"
                        ref="cityselectRef"
                        :callback="cityselected"
                        :items="district"
                        provance="四川"
                        city="成都市"
                        area="锦江区"
                ></yd-cityselect>
            </yd-cell-group>
    </yd-popup>`
yd-popup和yd-cityselect整合一起，且yd-popup的width不是100%时，显示有异常，省被挤到左边突出了。

**Comment by ydcss** [comment]
将 yd-cityselect 组件放置于 yd-popup 组件外层。

**Comment by wujay77** [comment]
谢谢回复

然后确实有yd-cityselect 组件放置于 yd-popup 组件里面的需求情况，我暂时只能用<yd-popup v-model="seenSearch" position="bottom" height="80%">了，宽度只有100%时yd-cityselect才正常
