### ISSUE TITLE
tab组件上面的nav列表怎么修改问题

### ISSUE THREAD

**Issue by lwl8855** [ydcss/vue-ydui#423]
#### 问题描述 
我想修改下tab组件上面导航nav的样式，但是好像不知道在哪里改，请问可以修改吗

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by anjia0532** [comment]
chrome F12 看一下类名，然后写css

**Comment by lwl8855** [comment]
关键是他的那个ul:yd-tab-nav在他的示例代码里面没有啊 
这是示例代码：
<yd-tab>
        <yd-tab-panel label="选项一">土地是以它的肥沃和收获而被估价的；才能也是土地，不过它生产的不是粮食，而是真理。如果只能滋生瞑想和幻想的话，即使再大的才能也只是砂地或盐池，那上面连小草也长不出来的。</yd-tab-panel>
        <yd-tab-panel label="选项二">我需要三件东西：爱情友谊和图书。然而这三者之间何其相通！炽热的爱情可以充实图书的内容，图书又是人们最忠实的朋友。</yd-tab-panel>
        <yd-tab-panel label="选项三">时间是一切财富中最宝贵的财富。</yd-tab-panel>
        <yd-tab-panel label="选项四">真理惟一可靠的标准就是永远自相符合。</yd-tab-panel>
    </yd-tab>
浏览器后台打开：
多了一个<ul class="yd-tab-nav">及里面的li
示例代码里面没有这个ul,我怎么改？

**Comment by lwl8855** [comment]
谢谢！我知道了。
