### ISSUE TITLE
全局引入ydui报错

### ISSUE THREAD

**Issue by tanwenchao** [ydcss/vue-ydui#426]
[Vue warn]: Invalid key "require" in validation rules object for prop "items".
[Vue warn]: Invalid key "require" in validation rules object for prop "trailWidth".
[Vue warn]: Invalid key "defaut" in validation rules object for prop "fullpage".

**Comment by 221022** [comment]
你好 请问你解决了吗  我也出现了你的问题 全局引入报错

**Comment by tanwenchao** [comment]
没有解决。尝试引入1.1.4版本的yd 还是报了这个错

**Comment by ydcss** [comment]
@tanwenchao @221022 问题已修复。

**Comment by zhangbird** [comment]
怎么解决的?重新npm 安装么 @ydcss

**Comment by ydcss** [comment]
@zhangbird 更新vue-ydui至1.1.6即可。
