### ISSUE TITLE
折叠面板右边的三角符号可以替换吗

### ISSUE THREAD

**Issue by Ayana7** [ydcss/vue-ydui#427]

**Comment by YYQ8023** [comment]
目前的三角符号是伪元素加边框实现的，也就是说你看到的三角，不是一个icon，而是边框，可以通过修改背景图片并把原来的伪元素隐藏来实现更换，但是不推荐。
我不是作者！

**Comment by Ayana7** [comment]
@YYQ8023 是的我知道，因为直接引入了安装包 'vue-ydui/dist/ydui.rem.css'，直接去修改源码可以实现，但总感觉不是很好。

**Comment by ydcss** [comment]
@Ayana7 不支持修改。若需修改，正如你们讨论的，覆盖样式。
