### ISSUE TITLE
关于search组件的操作逻辑问题

### ISSUE THREAD

**Issue by 290115231** [ydcss/vue-ydui#429]
#### 问题描述 
您好，我在使用search组件时发现search组件在提交搜索事件后，会将搜索的信息清除。如果索搜框在搜索之后被清空的话会不会让用户对当前数据的来源产生迷惑（当前显示的数据是搜索的数据还是默认的数据？），是不是保持会好一点？如果用户手动清楚了搜索信息，就可以重新将默认数据重新推送给用户，这样是不是更好呢？

**Comment by YYQ8023** [comment]
看了一下源码，确实是这样的：
![image](https://user-images.githubusercontent.com/22813922/34295066-526bef36-e746-11e7-875e-acebb326e05b.png)

**Comment by 290115231** [comment]
嗯，源码确实是这样，只是觉得组件这样使用不是很方便。

**Comment by sky429762423** [comment]
我也想让搜索的词继续保持，目前在:item-click和:on-submit方法里加了保持的代码，可是只显示一次，再次提交搜索就会失去效果，代码：this.$nextTick(function(){this.value2 = item})

**Comment by ydcss** [comment]
@290115231 @YYQ8023 现已修复，搜索后不清空搜索内容
