### ISSUE TITLE
碰到的样式问题

### ISSUE THREAD

**Issue by yajore** [ydcss/vue-ydui#43]
引用 Layout 框架后
```
this.$dialog.notify({
          mes: 'mesage',
          timeout: 2000
        });
```
.m-notify 被layout遮挡
解决方式设置z-index值设大
```
.m-notify {
  z-index: 5;
}
```
.cell-right 下缺少对.cell-right input[type=tel]（移动端输入手机号码作用很大）类型的样式支持

**Comment by ydcss** [comment]
你好，感谢你指出的问题，现已修复。
