### ISSUE TITLE
作者能把 http://vue.ydui.org/demo/#/ 这个示例项目的代码放到GITHUB 吗

### ISSUE THREAD

**Issue by ChangeZhang** [ydcss/vue-ydui#431]
作者能把 http://vue.ydui.org/demo/#/ 这个示例项目的代码放到GITHUB 吗 ？？？

**Comment by ydcss** [comment]
你好，代码都在这里了。
https://github.com/ydcss/vue-ydui/tree/master/example

唯一不同的切换效果这里也有了
http://vue.ydui.org/docs/#/optimize

**Comment by ChangeZhang** [comment]
非常感谢~
