### ISSUE TITLE
安卓手机出现了popup点击穿透问题 

### ISSUE THREAD

**Issue by ZhaoyangRao** [ydcss/vue-ydui#433]
#### 问题描述 

（尽可能详细地描述一下问题）
 <yd-layout>
  <yd-popup v-model="withdraw_popup" position="center" width="80%">
 <div>
<yd-cell-item>
        <input type="text" slot="right" placeholder="请输入验证码" v-model='code'>
            <yd-sendcode slot="right"
                           v-model="start1"
                            @click.native="sendCashCode"
                                type="warning"
                                ></yd-sendcode>
                                    </yd-cell-item>
</div>
  <yd-popup>
 </yd-layout>
#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
华为手机
- **演示地址：**

#### 提示错误信息

1. 
2. ...
大致布局就是这样 ，本来意图是点击外面一层 button跳出popup 然后操作里面的表单  。
在popup并没有触发弹出的时候，在手机上出现了，点击到发送验证码那个位置的时候，触发了发送验证码的按钮
#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
请发完整代码来。
