### ISSUE TITLE
yd-textarea无法设置color

### ISSUE THREAD

**Issue by zx107532** [ydcss/vue-ydui#434]
#### 问题描述 

在使用yd-textarea的时候无法给yd-textarea设置color颜色

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 在div里面放置yd-textarea
2. 在style里面给div设置color或者给div下面的textarea标签设置color都无效，页面上并不能识别设置的color

**Comment by ydcss** [comment]
你好，问题已修复。使用： 
```html
<yd-textarea style="color: #F00"></yd-textarea>
```
