### ISSUE TITLE
关于picker的小细节可以优化一下下~

### ISSUE THREAD

**Issue by deepkolos** [ydcss/vue-ydui#436]
#### 问题描述 

![ldui-picker](https://user-images.githubusercontent.com/12824616/34375129-e51e8d48-eb1f-11e7-8afc-7c00deb8f40c.gif)

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 复现步骤

步骤见gif~

#### 想要的效果

![vc-popup-picker](https://user-images.githubusercontent.com/12824616/34375171-1112f6b4-eb20-11e7-8b75-f8a1ac1ec95e.gif)

还有建议支持点击选择~, 小范围拖动还是有点不方便的~

**Comment by ydcss** [comment]
你好，感谢你的建议。目前不打算支持哦，时间能力有限，可以考虑使用你发的第二张图片的组件哦。
