### ISSUE TITLE
同时使用nav和scrollTab时，yd-scrollTtab高度始终为0，如何解决

### ISSUE THREAD

**Issue by BlackAnWhite** [ydcss/vue-ydui#438]
#### 问题描述 

（尽可能详细地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
代码麻烦发出来。

**Comment by BlackAnWhite** [comment]
已解决，父级容器需要加position:reletive;

**Comment by ydcss** [comment]
@BlackAnWhite 是的，昨天我更新的文档已经添加了。
