### ISSUE TITLE
scrolltab组件不能监听数据变化

### ISSUE THREAD

**Issue by zuoyanart** [ydcss/vue-ydui#44]
` 

       <yd-scrolltab-panel :label="item.text"  v-for="(item,index) in cat">
          <div style="height: 350px;background-color: gray;">
             <yd-badge type="primary" v-for="c in item.child">{{c.text}}</yd-badge>
          </div>
      </yd-scrolltab-panel>
`

如果动态赋值， 则scrolltab左侧的目录显示不出来。建议更换获取子组件scrolltab-panel的方法

**Comment by ydcss** [comment]
你好，问题已修复。将参数ready绑定到一个本地变量 start1(值为false)，再获取数据完毕后，将其设置为true即可。

**Comment by zuoyanart** [comment]
你看是不是这样实现比较好？
在yd-scrolltab-panel的mounted中执行
`this.$parent.$emit('addItem', {label:xxx})`

在scrolltab中定义 addItem函数动态赋值。

**Comment by ydcss** [comment]
太棒了！你的想法，我尽快修复。

**Comment by ydcss** [comment]
你好，问题已修复。

**Comment by zuoyanart** [comment]
谢谢！！
