### ISSUE TITLE
demo 在初始打开时加载的loading 怎么做的

### ISSUE THREAD

**Issue by ruyangit** [ydcss/vue-ydui#440]
#### 问题描述 
实例http://vue.ydui.org/demo/#/ 在打开时有个初始的loading效果  我代码下载下来运行却没有这个效果，
请问一下这个效果时怎么出现的？

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
http://vue.ydui.org/docs/#/optimize
