### ISSUE TITLE
ScrollNav 无法预览

### ISSUE THREAD

**Issue by BlackAnWhite** [ydcss/vue-ydui#441]
#### 问题描述 

官网上的scrollnav不能预览  要么一直显示加载转圈  要么什么也不显示  还会报错

#### 产生环境

- **使用版本：chrome 最新浏览器 PC
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
![image](https://user-images.githubusercontent.com/32764797/34432775-6da82ae8-ecb5-11e7-946e-591e5622179e.png)

2. 
![image](https://user-images.githubusercontent.com/32764797/34432779-76c718c8-ecb5-11e7-816c-80b29a1adaaa.png)

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
麻烦清理浏览器缓存后再试试。
