### ISSUE TITLE
yd-datetime 1.1.8beta版  全局引入 的 报错 

### ISSUE THREAD

**Issue by ericssonon** [ydcss/vue-ydui#443]
#### 问题描述 
yd-datetime 1.1.8beta版  全局引入 的 报错 
- **设备：**电脑 工具是微信开发工具

#### 提示错误信息
初始化时
1：Cannot set property 'reloadMonth' of undefined(…)
2：点击控件时 报  Cannot read property 'open' of null

**Comment by ydcss** [comment]
麻烦发使用代码出来看看。

**Comment by ericssonon** [comment]
我引入的是 项目里面的example下面的datetime.vue  代码没有任何改动

**Comment by ydcss** [comment]
http://runjs.cn/code/qgb3lmwz
无法重现。
