### ISSUE TITLE
yd-tab组件,当选项过多一行放不下,超出的选项卡支持左右滚动

### ISSUE THREAD

**Issue by ForMyMore** [ydcss/vue-ydui#444]
你好,ydui非常好用,谢谢作者的辛苦付出.
现在在使用过程中发现yd-tab组件有一个改进建议,希望采纳
当选项卡过多的时候,比方说7,8个的时候,每个选项的文字会被挤成竖排
可不可以做成这样的效果:当选项卡比较多,一行放不下的时候,选项卡可以左右滚动,这样每个选项卡的样式都能保持正常.
第一次提建议,有什么不对的地方请多包涵

**Comment by ydcss** [comment]
@ForMyMore  你好，问题已经修复，具体请参看文档哦。我先关闭issues，若还存在问题，麻烦重新开启。

**Comment by ForMyMore** [comment]
谢谢辛苦啦
