### ISSUE TITLE
建议：

### ISSUE THREAD

**Issue by gong135** [ydcss/vue-ydui#445]
<yd-popup v-model="show1" position="center" width="90%"  height ="90%">
   
 </yd-popup>
使用这个组件的时候 ，如果位置是center  height="..",这个高度是不生效的。我建议您开放这个高度。有很多时候 我是需要这个弹出框有足够的高度 ，并且上下左右居中。 比如 height ="90%" 就办不到

**Comment by ydcss** [comment]
你好，感谢你的建议。下次更新添加。

**Comment by ydcss** [comment]
你好，问题已修复。文档稍后更新。
