### ISSUE TITLE
yd-infinitescroll 的 $refs.xxx.$emit 中 '$emit' of undefined

### ISSUE THREAD

**Issue by felixFjing** [ydcss/vue-ydui#446]
#### 问题描述 

Uncaught (in promise) TypeError: Cannot read property '$emit' of undefined

使用yd-infinitescroll时出现上述问题

根据条件做一个搜索功能，下拉加载更多
book-list： 是一个自定义组件
页面初始状态下 books 是一个空数组 
searchBooksHandler：是搜索事件

`<yd-infinitescroll v-bind:callback="searchBooksHandler" ref="scrollBooks">
         <book-list :books="books" @selectBookemit="selectBook"></book-list>       
          <span slot="doneTip">喵，已经全部加载完毕</span>
 </yd-infinitescroll>`

`if (res.start === ERR_OK) {
            _that.books = [..._that.books, ..._that._normalizeBook(res.books)]
            console.log(_that.books)
            if (res.total <= _that.count) {
              /* 所有数据加载完毕 */
              _that.$refs.scrollBooks.$emit('ydui.infinitescroll.loadedDone')
              return
            }
            /* 单次请求数据完毕 */
            _that.$refs.scrollBooks.$emit('ydui.infinitescroll.finishLoad')
            _that.count += 20
          }`

console.log(_that.books) 出来是有值的

是不是在页面初始状态下 books 数组里面就必须有值才能使用yd-infinitescroll
还是其他原因？？？

请指教
 

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
调试一下“_that.$refs.scrollBooks” 这个是什么值

**Comment by felixFjing** [comment]
undefined
________________________________
发件人: Ooo_My_God <notifications@github.com>
发送时间: 2018年1月5日 9:06
收件人: ydcss/vue-ydui
抄送: 傅晶; Author
主题: Re: [ydcss/vue-ydui] yd-infinitescroll 的 $refs.xxx.$emit 中 '$emit' of undefined (#446)


调试一下“_that.$refs.scrollBooks” 这个是什么值

―

**Comment by felixFjing** [comment]
console.log(_that.$refs)

Object:{
scrollBooks:VueComponent
}

**Comment by ydcss** [comment]
请把完整代码发来。还有是什么方式引入的？

**Comment by felixFjing** [comment]
[cid:ebce4677-b5a1-4ea5-9e68-7537e050ec00][cid:cfdfcb04-220b-4ae4-a434-989ada712fbc]

以上就是这个功能的全部代码
book-list 是我自己定义的组件
里面只是循环读取数据 然后会分发出一个事件
其他复杂的逻辑没有


引用方式是 main.js全局引用的

[cid:2a4823a0-db7e-422b-8e75-530a276f723a]
________________________________
发件人: Ooo_My_God <notifications@github.com>
发送时间: 2018年1月5日 10:04
收件人: ydcss/vue-ydui
抄送: 傅晶; Author
主题: Re: [ydcss/vue-ydui] yd-infinitescroll 的 $refs.xxx.$emit 中 '$emit' of undefined (#446)


请把完整代码发来。还有是什么方式引入的？

―

**Comment by felixFjing** [comment]
找到原因了 list 组件 没有加 slot="list"  非常感谢

**Comment by xiaochegnzi0** [comment]
你好，我想问下，你是怎么使用yd-infinitescroll组件自定义布局的？？

**Comment by felixfjing** [comment]
你只要把组件包裹在yd-infinitescroll里面不就可以了吗？里面组件怎么布局都可以呀。

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: xiaochegnzi0 <notifications@github.com>
发送时间: Friday, August 17, 2018 1:52:50 PM
收件人: ydcss/vue-ydui
抄送: 傅晶; Author
主题: Re: [ydcss/vue-ydui] yd-infinitescroll 的 $refs.xxx.$emit 中 '$emit' of undefined (#446)


你好，我想问下，你是怎么使用yd-infinitescroll组件自定义布局的？？

―
