### ISSUE TITLE
actionsheet产生的值无法传给父组件

### ISSUE THREAD

**Issue by csdudu** [ydcss/vue-ydui#449]
actionsheet组件内的callback无法获取到this。我console了this的值，它并不是一个Vue对象。因此actionsheet产生的值我虽然可以拿到，但是无法传给父组件。
我是用<script>的传统方式开发的。

#### 产生环境
vue2.2.1/ydui1.1.5

- **演示地址：**
http://irhfuwu.com:6699/test_actionsheet.html

`
<div id="app" v-cloak >
          <yd-button @click.native="show2 = true" size="large" type="warning">不带取消</yd-button>

          <yd-actionsheet :items="myItems2" v-model="show2" @change="changeH"></yd-actionsheet>
        </div>
...
myItems2: [
        {
            label: '示例菜单二 - 自动关闭',
            val: '333',
            callback: (target) => {
                console.log(target.val);
                console.log(this);
                this.$emit('change',target.val);
            }
        },
        {label: '示例菜单三 - 自动关闭'},
        {label: '示例菜单四 - 自动关闭'}
    ]
`

**Comment by ydcss** [comment]
一、你发出来的代码不完整，看你示例才知道错误所在。
二、方法有二：
1、console.log(vm);
2、
```js
data: function () {
  return {
    show2: false,
    myItems2: [
        {
            label: '示例菜单二 - 自动关闭',
            val: '333',
            callback: (target) => {
                console.log(vm, this);
            }
        },
        {label: '示例菜单三 - 自动关闭'},
        {label: '示例菜单四 - 自动关闭'}
    ]
  }
}
```

**Comment by csdudu** [comment]
追问：请问这个myItems2能够动态绑定么？他的结构、长度都不固定。
