### ISSUE TITLE
yd-sendcode的bug

### ISSUE THREAD

**Issue by RoseEnd** [ydcss/vue-ydui#45]
使用yd-sendcode组件时，会提示yd-button未注册，不能正确显示按钮的样式

**Comment by RoseEnd** [comment]
![01ormeb0iqo3uq n6a7o2 w](https://cloud.githubusercontent.com/assets/19225061/25080167/f60f49f8-2374-11e7-93ce-9d3b1506ff8f.png)

**Comment by ydcss** [comment]
是的，sendcode继承于button，按需加载yd-sendcode组件时，得额外引入yd-button组件。文档未注明，稍后我修复。

**Comment by RoseEnd** [comment]
我额外引入也不行，依然报yd-button未注册

**Comment by RoseEnd** [comment]
![d dfl27u0ec2hsyc_4 0 0](https://cloud.githubusercontent.com/assets/19225061/25081670/401b768a-237e-11e7-98d1-3fb285972342.png)

**Comment by ydcss** [comment]
`import {Button, ButtonGroup} from 'vue-ydui/dist/lib.rem/button';<br /><br />Vue.component(Button.name, Button);<br />Vue.component(ButtonGroup.name, ButtonGroup);`

**Comment by RoseEnd** [comment]
我使用的是局部注册组件，不是使用全局注册组件，局部注册组件时不可以
![d dfl27u0ec2hsyc_4 0 0](https://cloud.githubusercontent.com/assets/19225061/25082627/9b5a9ed0-2384-11e7-94be-16b32f4bd3ff.png)

**Comment by RoseEnd** [comment]
使用局部组件时不行，怪我没表达清楚，另外使用的是rem样式单位
