### ISSUE TITLE
yd-search 建议

### ISSUE THREAD

**Issue by felixFjing** [ydcss/vue-ydui#450]
#### 问题描述 

建议yd-search全屏模式的时候可以自定义结果列表

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
现在不是自定义吗？

**Comment by felixFjing** [comment]
不是呀，现在result的格式是固定的。我的意思是整个展示列表可以自己自定义，就像滚动加载的list一样。

From Mr_Fujing
祝：生活愉快！


在 2018年1月8日，13:57，Ooo_My_God <notifications@github.com<mailto:notifications@github.com>> 写道：


现在不是自定义吗？

**Comment by ydcss** [comment]
你好，列表样式不支持自定义样式。

**Comment by felixFjing** [comment]
好呢，感谢。

From Mr_Fujing
祝：生活愉快！


在 2018年1月9日，15:29，Ooo_My_God <notifications@github.com<mailto:notifications@github.com>> 写道：


你好，列表样式不支持自定义样式。
