### ISSUE TITLE
轮播图组件问题

### ISSUE THREAD

**Issue by moRanou** [ydcss/vue-ydui#451]
#### 问题描述 
为什么轮播图组件把官方的图片换成自己的图片不能自适应了，会产生空白
#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
一、一句话谁看得出问题所在！
二、可以尝试如下方法：
   1、查看样式图片宽度是否100%；
   2、不是你的图片本身就有白边？
