### ISSUE TITLE
省市级三级联动，iPhone6s会出现横向滚动条

### ISSUE THREAD

**Issue by wu529778790** [ydcss/vue-ydui#452]
#### 问题描述 

（尽可能详细地描述一下问题）

省市级三级联动，iPhone6s点击之后会出现横向滚动条
，直接复制的您的代码也会出现，http://vue.ydui.org/demo/#/cityselect       ，而您的这个例子不会出现，不知道是不是做了其他处理，

#### 产生环境

- **使用版本：**  最新的
vue-cli 生成项目之后，直接复制您的代码，就会在6s上面出现点击放大的问题，不知道是不是scale或者transition的问题，PC端安卓，都不会出现，方便的话可以加扣扣，529778790

**Comment by ydcss** [comment]
head内添加了这个meta吗？
```html
<meta content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0" name="viewport"/>
```

**Comment by wu529778790** [comment]
<meta name="viewport" content="width=device-width, initial-scale=1.0">
好了，谢谢了，我的是编辑器自动生成的，竟然少了几个，O(∩_∩)O谢谢
