### ISSUE TITLE
搜索组件回显label问题

### ISSUE THREAD

**Issue by leeziiAtCn** [ydcss/vue-ydui#454]
#### 问题描述 

使用简单类型数组 [1,2,3,4,5]作为搜索结果result没有问题
使用 复杂类型 [{label:1,id:1}] 在clickitem 之后 搜索栏 显示问题如图 
只重写了一下官方文档的实例代码的 getResult 函数  请看
#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息
回显问题 类型出错
![jietu20180109-114729](https://user-images.githubusercontent.com/22995117/34704260-eb58c4f4-f532-11e7-8f9e-acf9def6e4c5.png)
#### 复现步骤
```
 getResult (val) {
        if (!val) return []
        return [
          {
            label: 1,
            id: 1
          },
          {
            label: 2,
            id: 2
          }
        ].filter(value => +val === value.id)
      },
```

**Comment by ydcss** [comment]
你好，问题已修复。文档稍后更新。
