### ISSUE TITLE
scrollnav 滑动偶尔不触发callback

### ISSUE THREAD

**Issue by hello29** [ydcss/vue-ydui#455]
#### 问题描述 
1.18新增的组建scrollnav；

循环内容的时候，如果内容高度比较小，就可能出现这个问题，callback 打印index 1234578 可能就会少一个6

（尽可能详细地描述一下问题）

#### 产生环境

- **使用版本：**
v1.1.8 
- **设备：**（手机、平板移动设备）
ios 跟chrome一样
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
你好，请问内容高度大概多小，无法重现啊。
