### ISSUE TITLE
【cityselect】当第一个省市无县级数据时，即使之后的省市有县级，也不展示县级了

### ISSUE THREAD

**Issue by arbing** [ydcss/vue-ydui#456]
#### 问题描述 

自定义数据，当第一省市无县级数据时，即使之后的省市有县级，也不展示县级了。
演示地址：https://jsfiddle.net/vsLu5093/1/

只有当第一个省市有县级，县级数据才展示正确。
演示地址：https://jsfiddle.net/uuu791qa/1/

#### 产生环境

- **使用版本：**
1.1.8

- **设备：**（手机、平板移动设备）
Chrome 63

- **演示地址：**
第一个省市无县级: https://jsfiddle.net/vsLu5093/1/
第一个省市有县级: https://jsfiddle.net/uuu791qa/1/

**Comment by ydcss** [comment]
你好，问题已收到。正在修改当中。默认读取第一级的数据来判断层级。https://github.com/ydcss/vue-ydui/issues/417

**Comment by arbing** [comment]
暂时这么处理了
`
this.$refs.cityselectDemo.getColumsNum = d => {
   this.$refs.cityselectDemo.columnNum = 3
 }
`

**Comment by ydcss** [comment]
@arbing 你好，问题已经修复。我先关闭issues，若还存在问题，麻烦重新开启。
