### ISSUE TITLE
建议search组件增加autofocus属性

### ISSUE THREAD

**Issue by g-u-a-n** [ydcss/vue-ydui#457]

**Comment by g-u-a-n** [comment]
当search为fullpage模式时，点击文本框进入全屏模式，此时文本框并没有获取到焦点，需要再次点击文本框才能获取焦点、弹出键盘输入；建议点击点击文本框直接获取焦点，而不是需要重复点击。

望越做越好，感谢付出！

**Comment by g-u-a-n** [comment]
补充：
pc chrome未见此问题，默认直接焦点；ios safari会出现上述问题，很奇怪

**Comment by ydcss** [comment]
你好，IOS默认是不支持 autofocus 属性的，一直没有找到解决办法。你有什么好的解决办法吗？

**Comment by struggle-fish** [comment]
同求解决方案

**Comment by g-u-a-n** [comment]
@ydcss @struggle-fish 
我尝试在yd-search非全屏模式下的文本框点击事件增加调用focus函数，测试，点击搜索文本框，进入全屏搜索模式，此时全屏模式下的文本框默认有焦点、弹出软键盘；
ios11 safari、微信测试通过，其它环境尚不明确。
这样做不知道是否合理，但确实能够满足我的需求。
> src/components/search/src/search.vue

`
methods: {
    open() {
        if (this.fullpage) {
            this.show = true;
            this.$refs.search.setFocus(); // 调用focus
        }
    }
    // ..........
}
`

**Comment by ydcss** [comment]
@g-u-a-n 感谢提供方法。下次更新修复。

**Comment by ydcss** [comment]
@g-u-a-n 你好，问题已经修复。我先关闭issues，若还存在问题，麻烦重新开启。
