### ISSUE TITLE
请问下yd-datetime怎么设置开始日期为今天，结束日期为后天

### ISSUE THREAD

**Issue by tx123456** [ydcss/vue-ydui#458]
#### 问题描述 

（尽可能详细地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

请问下yd-datetime怎么设置开始日期为今天，结束日期为后天
我看文档只支持那种2018-1-1这种日期格式的

**Comment by litielongxx** [comment]
可以通过设置设置 start-date和 end-date 即可。
