### ISSUE TITLE
ydtab 切换时字的颜色没有改变

### ISSUE THREAD

**Issue by tx123456** [ydcss/vue-ydui#459]
#### 问题描述 

（尽可能详细地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息
这是我的代码
 <yd-tab active-color="#eaba63">
                <yd-tab-panel  label="普通房" active >111111</yd-tab-panel>
                <yd-tab-panel label="贵宾房">222222设置初始激活项</yd-tab-panel>
            </yd-tab>

#### 复现步骤

一开始加载的时候字的颜色是正确的，然后切换之后字的颜色就不会改变了，请问这是什么原因

**Comment by ydcss** [comment]
你好，你给的代码我运行是正常呀！
