### ISSUE TITLE
滚动选项卡的label标题

### ISSUE THREAD

**Issue by moRanou** [ydcss/vue-ydui#461]
#### 问题描述 

（尽可能详细地描述一下问题）
滚动选项卡的label标题是不能动态生成，只能放死的数据
#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
是的
