### ISSUE TITLE
导航和布局问题

### ISSUE THREAD

**Issue by liaochente** [ydcss/vue-ydui#464]
#### 问题描述 

1.我在index.vue中使用<yd-layout>包裹了2个.vue 分别是header.vue、footer.vue；
2.header.vue、footer.vue的代码就是从官网示例中的代码直接COPY过来的，最后的展示结果header和footer没有分别置顶和制底；
3.而且当中间有内容时且内容超出容器，是整个屏幕滚动，不像布局的DEMO中描述的一样只有中间部分滚动

#### 最终结果
最后我发现我的输出结果是一个id="scrollView" 的selection标签包裹了3个部分，而不是DEMO中的一个selection只包裹内容区，顶部和底部是在外面的

**Comment by ydcss** [comment]
1、个人认为你发段代码出来更容易知道问题所在。
2、我的猜测：是不是用了yd-layout组件，然后header.vue和footer.vue没有指定slot。

**Comment by liaochente** [comment]
不好意思，是个乌龙，safari的模拟手机展示和实际手机展示结果不一致，之前一直拿的浏览器访问的；
不过我渲染出来的最终代码确实和DEMO是有差异，主要就是最外层多了个id="scrollView" 的selection 手机端展示效果一致

**Comment by jinhongpop** [comment]
布局问题，tabbar，无法固定在底部，slot已设置 始终无法达到demo的效果，已全局引入ydui，望解答，急

<template>
    <yd-layout>
        <yd-navbar slot="navbar" title="Tab">
            <router-link to="/tabs" slot="left">
                <yd-navbar-back-icon></yd-navbar-back-icon>
            </router-link>
        </yd-navbar>

        
        
        <yd-tabbar slot="tabbar">
        <yd-tabbar-item title="首页" link="#">
            <yd-icon name="home-outline" slot="icon" size="0.54rem"></yd-icon>
        </yd-tabbar-item>
        <yd-tabbar-item title="购物车" link="#" dot>
            <yd-icon name="shopcart-outline" slot="icon" size="0.54rem"></yd-icon>
        </yd-tabbar-item>
        <yd-tabbar-item title="个人中心" link="#" active>
            <yd-icon name="ucenter" slot="icon" size="0.54rem"></yd-icon>
            <yd-badge slot="badge" type="danger">2</yd-badge>
        </yd-tabbar-item>
    </yd-tabbar>
    
    </yd-layout>
</template>

**Comment by hownet** [comment]
楼上，需要加  fixed="True"
