### ISSUE TITLE
LightBox组件一直显示加载动画？

### ISSUE THREAD

**Issue by lxiaosky** [ydcss/vue-ydui#466]
#### 问题描述 

如果是在百度上找的图片地址，预览的时候加载动画是正常的，
但是如果是上传七牛的图片，预览的时候图片预览正常，但是加载动画会一直转

#### 产生环境

- **使用版本：**vue2.x 最新版
- **设备：** 所有设备
- **演示地址：**
[http://101.236.43.25:6608/#/friend](url)
第一个列表和第三列表里的两个图片预览的时候加载动画就会一直转
第二个列表和最后一个列表的图片就不会出现这种情况
#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
你好，这段时间忙，我上次看的时候，记得是因为png透明引起的吧。

**Comment by lxiaosky** [comment]
哦，明白了，那我暂时先给'yd-slider-item'加上一个黑色背景，暂时能解决问题了，不过这个loading这个我看他是一直都在转，希望能改成加载完成后，隐藏掉loading

**Comment by ydcss** [comment]
@lxiaosky 你好，问题已经修复。我先关闭issues，若还存在问题，麻烦重新开启。
