### ISSUE TITLE
VUE YDUI 文档滚动选项卡API问题

### ISSUE THREAD

**Issue by JasonYadi** [ydcss/vue-ydui#467]
文档将callback介绍在yd-scrolltab-panel上面了 ， 应该是在yd-scrilltab上面

**Comment by JasonYadi** [comment]
![image](https://user-images.githubusercontent.com/24763020/35029579-979121da-fb96-11e7-99f5-0861957d75a0.png)

**Comment by ydcss** [comment]
你好，非常感谢指出问题。现已修复。
