### ISSUE TITLE
关于citySelect接地气的建议

### ISSUE THREAD

**Issue by RoseEnd** [ydcss/vue-ydui#47]
这个组件效果很好但是有一个问题：
各级地区只有名字没有对应的id，但是后端数据库存的基本上是id,无法与后端对接
建议地区数据源可以传递，定义相对的数据格式如：{name:'北京', id : '1'},这样就很方便与后端对接
望采纳

**Comment by ydcss** [comment]
你好，原来设计的时候，我考虑过了这个问题。但是cityselect直接加载整个数据文件，如果加上ID，该数据文件会很大。过后我再重新考虑下吧。谢谢你提的建议。

**Comment by hhiew** [comment]
如果打包文件过大，是否可以制定数据格式标准。由使用人自己提供？

**Comment by ydcss** [comment]
@RoseEnd @hhiew 组件yd-cityselect现已支持传入自定义数据。省市县数据源将由用户提供，为此 ydui 提供了另外一个项目（[ydui-district](https://github.com/ydcss/ydui-district)）供用户使用，其提供两种数据源8个版本。具体请参看[这里](http://vue.ydui.org/docs/#/iupdate)
