### ISSUE TITLE
dateTime组件type等于month在手机上会默认显示成2008-1，在pc浏览器上可以显示指定的日期。

### ISSUE THREAD

**Issue by zjc0828** [ydcss/vue-ydui#470]

**Comment by litielongxx** [comment]
手机上生成的数值识别错误吧
getDate() {
 var date = new Date();
                var seperator1 = "-";
                var seperator2 = ":";
                var month = date.getMonth() + 1;
                var strDate = date.getDate();
                if (month >= 1 && month <= 9) {
                    month = "0" + month;
                }
                if (strDate >= 0 && strDate <= 9) {
                    strDate = "0" + strDate;
                }
                var currentdate = date.getFullYear() + seperator1 + month + seperator1 + strDate;
                return currentdate;
}
用法：this.d1=this.getDate();

**Comment by xybin1990** [comment]
我也出现同样的情况，跟例子是一样的代码，但是在IOS上显示的就是2008-01，不是自己初始化的日期

**Comment by xybin1990** [comment]
@ydcss 没有解释？

**Comment by wuxiaolan91** [comment]
这个问题为啥被 close 了?
我看到 issue 里都有3个人遇到了这个问题了呢.
