### ISSUE TITLE
tabbar无法象demo固定在底部，求解

### ISSUE THREAD

**Issue by jinhongpop** [ydcss/vue-ydui#471]
布局问题，tabbar，无法固定在底部，slot已设置 始终无法达到demo的效果，已全局引入ydui，其他正常的，望解答，急

    <yd-tabbar slot="tabbar">
    <yd-tabbar-item title="首页" link="#">
        <yd-icon name="home-outline" slot="icon" size="0.54rem"></yd-icon>
    </yd-tabbar-item>
    <yd-tabbar-item title="购物车" link="#" dot>
        <yd-icon name="shopcart-outline" slot="icon" size="0.54rem"></yd-icon>
    </yd-tabbar-item>
    <yd-tabbar-item title="个人中心" link="#" active>
        <yd-icon name="ucenter" slot="icon" size="0.54rem"></yd-icon>
        <yd-badge slot="badge" type="danger">2</yd-badge>
    </yd-tabbar-item>
</yd-tabbar>

</yd-layout>

**Comment by jinhongpop** [comment]
用了 <yd-layout>

**Comment by jinhongpop** [comment]
yd-layout

**Comment by xcsweb** [comment]
fixed不行吗

**Comment by jinhongpop** [comment]
fixed，可是可以，但是固定后，在电脑浏览器上，宽就变百分百了 ,而官网给出的example中的，tabbar案例，就只用了slot="tabbar" 就可以固定住，而不用fixed ,想知道原因
