### ISSUE TITLE
手机的验证正则需要更新啦

### ISSUE THREAD

**Issue by BlackAnWhite** [ydcss/vue-ydui#472]
#### 问题描述 

input输入框组件 自带的手机验证规则 不能正确验证19x号段的号码

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by Venus-WXP** [comment]
16段同样不能验证，我查看了正则，只支持13,14，15，17,18段的。今年移动新出16手机号

**Comment by litielongxx** [comment]
手动验证var reg = /^0?(13[0-9]|15[012356789]|18[012346789]|14[57]|17[678]|170[059]|14[57]|166|19[89])[0-9]{8}$/;

**Comment by ydcss** [comment]
@BlackAnWhite 你好，问题已经修复。我先关闭issues，若还存在问题，麻烦重新开启。
