### ISSUE TITLE
关于滚动加载的问题

### ISSUE THREAD

**Issue by RoseEnd** [ydcss/vue-ydui#48]
再做滚动加载的时候出现这样的问题，loadList方法只能触发一次，无法触发第二次

**Comment by RoseEnd** [comment]
![3](https://cloud.githubusercontent.com/assets/19225061/25267621/0d577820-26a8-11e7-8c36-b20a76fa3f2a.png)

**Comment by RoseEnd** [comment]
我在想难道是我代码的问题，到第二次加载的时候console.log(11)都无法执行

**Comment by ydcss** [comment]
请问：
1、yd-infinitescroll绑定了:on-infinite="loadList"吗？
2、第二次滚动的时候，是否达到了加载条件（滚动条大于内容90%）？

**Comment by RoseEnd** [comment]
这些条件我都满足，我是每次请求10条数据，一共23条数据，按道理可以滚动加载两次，但是第二次无法触发loadList

**Comment by ydcss** [comment]
你好，console.log(11)；一共输出了多少次？

**Comment by RoseEnd** [comment]
就一次

**Comment by ydcss** [comment]
调试一下 ，是不是进入了 window.$yduiBus.$emit... 这里了。

**Comment by ydcss** [comment]
哦，我知道了，你少了一句话啊！麻烦你看看示例代码！

**Comment by RoseEnd** [comment]
看到了，单次数据请求完毕，尴尬，不好意思啊

**Comment by ydcss** [comment]
没事哟！
