### ISSUE TITLE
yd-slider show-pagination布尔值传值

### ISSUE THREAD

**Issue by php360** [ydcss/vue-ydui#481]
#### 问题描述 

yd-slider show-pagination布尔值传值，文档中说的是show-pagination传递布尔值，如果仅仅这样写
show-pagination="false" 不是以布尔值传递，而是以字符串"false"传递
需要使用 v-bind，从而让它的值被当作JS表达式计算。
要这样写： v-bind:show-pagination="false"  或者 :show-pagination="false"  才可以传递布尔值。
文档没有标注出来

#### 产生环境

- **使用版本：**
ydui：1.2.0
vue：2.5.13

**Comment by php360** [comment]
loop也是一样的传值，文档中没有标注。这里容易产生问题。

**Comment by ydcss** [comment]
如果这都看不懂，建议先好好学学vue。
