### ISSUE TITLE
TextArea组件 表单绑定v-model时 无法回显手动设置的值

### ISSUE THREAD

**Issue by Tadini** [ydcss/vue-ydui#486]
#### 问题描述 

TextArea组件 在使用 v-model 关联一个 对象下的属性值时（暂定a.b，a为数据对象，b为属性值），我手动赋值 a.b 等于某个值时  页面中textarea的值未发生变化。

**Comment by ydcss** [comment]
你好，请问你是用哪个版本的ydui？未能重现。
http://runjs.cn/code/gkeditfh

**Comment by CalmHarbin** [comment]
我这边也刚刚也遇到了这个问题,ydui版本1.2.6
组件
 <yd-textarea slot="right" ref="textarea" v-model="reason" placeholder="请输入社团简介" maxlength="30"></yd-textarea>
<p>哈哈哈{{reason}}</p>

初始值     reason:'1111',
在created设置一个3000ms定时器定时器,
setTimeout(() => {
                this.reason='2';
                console.log(this.$refs.textarea);
            },3000)

效果
3000ms之后
textarea显示1111,
p标签显示2,

监听reason
输出新值为2,旧值为1111,

console.log(this.$refs.textarea);输出结果

maxlength: "30"
mlstr: "1111"   (这里值未改变的)
num: 4
placeholder: "请输入社团简介"
readonly: false
showCounter: true
value: "2"   (这里值是对的)

希望修改为视图可以自动刷新

我的解决方法
this.$refs.textarea.mlstr = this.reason;
直接修改值未我想要的值
