### ISSUE TITLE
上拉菜单求增加长按延时的api，就是长按才弹出菜单

### ISSUE THREAD

**Issue by zghuan** [ydcss/vue-ydui#487]
#### 问题描述 

（尽可能详细地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
你好，弹出关闭菜单是由用户控制v-model的值实现的，不由组件控制。
