### ISSUE TITLE
数字加减最小值无法设置为0，有没有方法解决？

### ISSUE THREAD

**Issue by NightLin92** [ydcss/vue-ydui#490]
#### 问题描述 

数字加减最小值无法设置为0，有没有方法解决？

#### 产生环境

本地环境，chrome调试

#### 提示错误信息

![image](https://user-images.githubusercontent.com/21329182/36629433-a32c90ca-1990-11e8-8e93-f64ad5b55a2b.png)

**Comment by ydcss** [comment]
你好，设置min参数不就好了吗？
```html
<yd-spinner min="0"></yd-spinner>
```

**Comment by li9269391** [comment]
最大值只能为1
