### ISSUE TITLE
infinitScroll的回调函数只触发两次

### ISSUE THREAD

**Issue by ee07b577** [ydcss/vue-ydui#494]
#### 问题描述 
加载的回调函数只会触发两次，之后加载图片显示，但是不触发请求

#### 产生环境

- **使用版本：1.1.8**
- **设备：pc chrome 模拟都有问题**（手机、平板移动设备）
- **演示地址：**

#### 复现步骤

<template>
  <div class="wraper" style="z-index: 0;margin-top: 0px">
    <div class="news-box" style="margin-top: 0px">
      <yd-pullrefresh :callback="loadUpperList" ref="pullRefresh">
        <yd-infinitescroll :callback="loadDownerList" ref="infiniteScroll">
          <div slot="list" v-for="item in list" class="mb news">
            <p class="news-tips clearfix" style="padding-bottom: 3px">
              <label class="fr gray">{{item.createTime}}</label>
            </p>
            <p class="news-title" style="padding-bottom: 3px">
              {{item.content}}
            </p>
          </div>
          <span slot="doneTip">没有更多消息了</span>
          <img slot="loadingTip" src="http://static.ydcss.com/uploads/ydui/loading/loading10.svg"/>
        </yd-infinitescroll>
      </yd-pullrefresh>
    </div>
  </div>
</template>

<script>
  import request from 'utils/request'
  import dateFormat from 'dateformat'
  export default {
    data () {
      return {
        newestId: null,
        oldestId: null,
        pageSize: 10,
        list: []
      }
    },
    created () {
      this.loadDownerList()
    },
    methods: {
      loadUpperList () {
        request.flashNews({
          indexId: this.newestId,
          pageSize: this.pageSize,
          direct: 0 // 向下，0表示向上
        })
          .then(request.checkStatus)
          .then(request.checkData)
          .then(data => {
            if (data.length > 0) {
              this.list = [...data(item => {
                console.log(new Date(item.createTime))
                item.createTime = dateFormat(new Date(item.createTime), 'yyyy-mm-dd HH:MM')
                return item
              }), ...this.list]
              this.newestId = this.list[0].tid
            }
            this.$dialog.notify({
              mes: data.length > 0 ? '为您更新了' + data.length + '条内容' : '已经是最新内容了',
              timeout: 5000
            })
            /* 单次请求数据完毕 */
            this.$refs.pullRefresh.$emit('ydui.pullrefresh.finishLoad')
          })
          .catch(request.noticeFail)
      },
      loadDownerList (isInit) { // 加载较旧的数据
        request.flashNews({
          indexId: this.oldestId,
          pageSize: this.pageSize,
          direct: 1 // 向下，0表示向上
        })
          .then(request.checkStatus)
          .then(request.checkData)
          .then(data => {
            if (data.length > 0) {
              this.list = [...this.list, ...data.map(item => {
                item.createTime = dateFormat(new Date(item.createTime), 'yyyy-mm-dd HH:MM')
                return item
              })]
              if (isInit) { // 初次加载
                this.newestId = this.list[0].tid
              }
              this.oldestId = data[data.length - 1].tid
            }
            if (data.length < this.pageSize) {
              /* 所有数据加载完毕 */
              this.$refs.infiniteScroll.$emit('ydui.infiniteScroll.loadedDone')
              return
            }
            /* 单次请求数据完毕 */
            this.$refs.infiniteScroll.$emit('ydui.infiniteScroll.finishLoad')
          })
          .catch(request.noticeFail)
      }
    }
  }
</script>
<style scoped lang="less">
  .wraper {
    padding: 7px 5px;
  }

  .news-box {
    margin-bottom: 40px;
  }

  .news {
    display: inline-block;
    width: 100%;
    margin-bottom: 10px;
    padding: 16px 16px 16px 20px;
    border-radius: 6px;
    font-size: 14px;
    color: #000;
    background-color: rgb(255, 255, 255);
    box-shadow: 0px 3px 13px 0px rgba(0, 0, 0, 0.11);
    .mark {
      display: inline-block;
      border-radius: 2px;
      color: white;
      padding: 2px 8px;
      margin-right: 10px;
    }
  }

  .news .mark-gonggao {
    background-color: #00a0e9;
  }

  .news .mark-celue {
    background-color: #8fc31f;
  }

  .news .mark-import {
    background-color: #fa4e4e;
  }

  .news .mark-likong {
    border: 1px solid #1ABC9D;
    color: #1ABC9D;
  }

  .news .mark-liduo {
    border: 1px solid #fa4e4e;
    color: #fa4e4e;
  }

  .news .news-tips {
    padding-bottom: 8px;
    border-bottom: 1px solid #d9d9d9;
    margin-bottom: 8px;
  }

  .news .news-tips .peo-head {
    width: 25px;
    height: 25px;
    border-radius: 25px;
    border: 1px solid #ccc;
  }

  .news .news-tips .peo-name {
    margin-left: 5px;
    color: #222;
  }

  .news .news-tips .gray {
    color: #808080;
  }

  .news .news-title {
    padding-bottom: 16px;
  }

  .news .ask-box {
    padding: 10px;
    background: #ffead1;
  }

  .news .ask-box .ask-info {
    color: #575554
  }

  .news .ask-box .ask-user {
    color: #9c9b9b;
    margin-top: 5px;
  }

  .news img {
    width: 100%;
  }
</style>

**Comment by ee07b577** [comment]
我大概调试了一下，是这段代码中，把loading设置成了true. if (tagOffsetTop > offsetTop && tagOffsetTop - (distance + offsetTop) * this.num <= contentHeight && this.$el.offsetHeight > scrollviewHeight) {
                    this.isLoading = true;
                    // TODO 参数更名，即将删除
                    if (this.onInfinite) {
                        this.onInfinite();
                        console.warn('From VUE-YDUI: The parameter "onInfinite" is destroyed, please use "callback".');
                    }
                    this.callback && this.callback();
                    this.num++;
                }

**Comment by ydcss** [comment]
你好，没看出来代码出了什么问题。请求数据中会将isLoading设置为true，数据请求完毕后需手动调用this.$refs.infiniteScroll.$emit('ydui.infiniteScroll.finishLoad')，这样存在什么问题吗？
