### ISSUE TITLE
老大，原来的YDUI不搞了吗，能不能把这个整整支持下jq啊！~~

### ISSUE THREAD

**Issue by indiboy** [ydcss/vue-ydui#495]
原来的不更新下有点小郁闷啊！~~

**Comment by makenum** [comment]
是啊，jQuery版的GitHub地址都没有了

**Comment by indiboy** [comment]
可怜啊！~~~~

**Comment by ydcss** [comment]
@indiboy 你好， jQuery是一个类库，vue是一个框架。简单说jQuery能实现的vue都能实现，而且更简洁，所以个人觉得用了没必要再引入jQuery了。具体得看你项目需求。

**Comment by wk297090323** [comment]
@ydcss 你好！现在的前端生态发展太猛了，想像jquery一样用一下vue，还需要node、webpack、es6这些技术栈的支持，学习成本太高了。

**Comment by indiboy** [comment]
学习成本倒不是很高，就是觉得VUE不是很方便,后端不好做，我都是一个人玩。另外，搜索引擎收录也需要Jq啊，请老大考虑一下。

**Comment by ydcss** [comment]
@wk297090323 你好，学习成本高，总不能把你的懒惰强加给别人吧？jQuery优秀框架不是有很多吗？mui,weui,sui....

**Comment by ydcss** [comment]
@indiboy nuxt.js

**Comment by ydcss** [comment]
@makenum https://github.com/aloncai/ydui

**Comment by wk297090323** [comment]
@ydcss 大哥你说的对，不能把懒惰强加给别人，我也已经在努力学了，希望这个优秀的项目能继续维护下去！祝好运！
