### ISSUE TITLE
dialog 的一点建议

### ISSUE THREAD

**Issue by Grewer** [ydcss/vue-ydui#496]
```
                this.$dialog.toast({
                    mes: '一个没有任何图标的提示！',
                    timeout: 1500
                });
```
比如这个 dialog ,能否添加一个参数,可以让其点击出现的msg来关闭,仍然能够点击页面上的其他东西(原来是点击任何地方关闭);
作为一个简单的消息提示,需要点击一下,再点击下一步的按钮,感觉比较麻烦;

**Comment by ydcss** [comment]
你好，个人觉得toast就是一个简单的提示信息，如果不满足需求可以考虑自行写一个组件哦。
