### ISSUE TITLE
你好，进度条可以显示最大值、最小值以及当前位置的数字吗

### ISSUE THREAD

**Issue by tr-text** [ydcss/vue-ydui#499]
#### 问题描述 

（尽可能详细地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
你好，最大值不是就100%吗？最小值不是0吗？当前值就是v-model绑定的值呀！
