### ISSUE TITLE
请问rem 在哪里设置 就是html根目录的rem

### ISSUE THREAD

**Issue by wjj5728** [ydcss/vue-ydui#5]

**Comment by ydcss** [comment]
你好，rem相对根元素<html>的字体大小变化而变化的css单位。根元素<html>是不需要设置rem的，引入ydui.flexible.js会根据页面宽度，计算适合的字体大小(px)并赋值给根元素<html>，从而样式里面rem会随着跟元素<html>字体变化而变化。具体请参看[http://www.ydui.org/flexible](url)
