### ISSUE TITLE
使用infinitescroll的一些问题

### ISSUE THREAD

**Issue by ymjdev** [ydcss/vue-ydui#50]
使用infinitescroll做项目的时候有用到tab，每个tab-panel-item加载的infinitescroll都不一样，但infinitescroll会同时触发，当有列表的数据为空时其他列表也不加载了。

**Comment by ydcss** [comment]
你好，问题已修复。支持同一页面调用多个infinitescroll。两个地方需要修改：
1、原 window.$yduiBus.$emit() 已改为 this.$refs.XXXX.$emit()。
2、每个infinitescroll组件不能使用同一个父级（含有css属性overflow-y: auto;或scroll）。
像这样：
`&lt;template&gt;
    &lt;yd-tab&gt;
        &lt;yd-tab-panel label=&quot;选项一&quot;&gt;
            &lt;div style=&quot;height: 800px;overflow-y: auto&quot;&gt;
                &lt;yd-infinitescroll :on-infinite=&quot;loadList111&quot; ref=&quot;lsdemo111&quot;&gt;
                    ...
                &lt;/yd-infinitescroll&gt;
            &lt;/div&gt;
        &lt;/yd-tab-panel&gt;
        &lt;yd-tab-panel label=&quot;选项四&quot;&gt;
            &lt;div style=&quot;height: 800px;overflow-y: auto&quot;&gt;
                &lt;yd-infinitescroll :on-infinite=&quot;loadList222&quot; ref=&quot;lsdemo222&quot;&gt;
                    ...
                &lt;/yd-infinitescroll&gt;
            &lt;/div&gt;
        &lt;/yd-tab-panel&gt;
    &lt;/yd-tab&gt;
&lt;/template&gt;`

**Comment by ymjdev** [comment]
感谢

**Comment by YaoGuaiWang** [comment]
更新后 window.$yduiBus.$emit()  是否还能使用啊？

**Comment by ydcss** [comment]
你好，不能使用了，原来设计的方法存在巨大问题。
