### ISSUE TITLE
yd-popup modal 希望增加 透明度参数

### ISSUE THREAD

**Issue by myxingke** [ydcss/vue-ydui#500]
#### 问题描述 

yd-popup modal 希望增加 透明度参数。默认的0.4有点太白了。希望可以自己传入参数去改变这个值！看了下代码是通过style来改变的! 希望能改地！

**Comment by ydcss** [comment]
你好，问题已经修复，具体请参看文档。我先关闭issues，若还存在问题，麻烦重新开启。
