### ISSUE TITLE
使用yd-button组件时，传入type总是报错。。custom validator check failed for prop "type"。麻烦解决一下。谢谢

### ISSUE THREAD

**Issue by tr-text** [ydcss/vue-ydui#504]
#### 问题描述 

（尽可能详细地描述一下问题）

#### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **演示地址：**

#### 提示错误信息

1. 
2. ...

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
解决什么问题？提示很清楚了，你传入的type类型不对。

**Comment by tr-text** [comment]
不好意思，是我给type定义了指定值之外的值，希望button的颜色可以多配置几种，或者设置成可以自己配置的吧



------------------ 原始邮件 ------------------
发件人: "Ooo_My_God"<notifications@github.com>;
发送时间: 2018年3月9日(星期五) 下午5:36
收件人: "ydcss/vue-ydui"<vue-ydui@noreply.github.com>;
抄送: "45°的天空"<1115463794@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ydcss/vue-ydui] 使用yd-button组件时，传入type总是报错。。custom validator check failed for prop "type"。麻烦解决一下。谢谢 (#504)




解决什么问题？提示很清楚了，你传入的type类型不对。

**Comment by ydcss** [comment]
yd-button是支持自定义颜色的。具体请参看文档中“黑色按钮”。
http://vue.ydui.org/docs/#/button
