### ISSUE TITLE
倒计时组件的建议

### ISSUE THREAD

**Issue by ymjdev** [ydcss/vue-ydui#51]
关于使用倒计时组件，开发中后端给到的接口一般为秒，建议支持time=秒，感谢

**Comment by ydcss** [comment]
建议收到，确实是有这样的需求，尽快完善，感谢你提出的建议。

**Comment by ydcss** [comment]
你好，已添加支持传入剩余时间为秒的参数，具体请参看文档。

**Comment by ymjdev** [comment]
感谢
