### ISSUE TITLE
滚动加载和返回顶部问题

### ISSUE THREAD

**Issue by ruanxuefeng** [ydcss/vue-ydui#511]
#### 问题描述 

返回顶部不显示，而下拉加载移动到最下面不出发callback事件

#### 产生环境

使用版本：1.2.0
设备：谷歌，Safari
演示地址：https://jsfiddle.net/mmx38qxw/702/

#### 提示错误信息
无

#### 复现步骤

1. 
2. ...

**Comment by ydcss** [comment]
最下方“特别注意”：http://vue.ydui.org/docs/#/layout 
```html
<div id="app" style="height: 100%;">
```
