### ISSUE TITLE
popup中怎么修改默认圆角

### ISSUE THREAD

**Issue by chenjiecloud** [ydcss/vue-ydui#512]

**Comment by johnsonGong** [comment]
没代码，看不懂你的问题。

**Comment by chenjiecloud** [comment]
<yd-popup v-model="canBuy" position="center" width="70%" class="canbuy_pop" max-width="420px" :close-on-masker="false">
      <div class="canbuy_pop_top">
        <h4>无法行权</h4>
      </div>
      <div class="canbuy_pop_content">
        <p>最短行权期限为3个交易日</p>
      </div>
      <div @click="canBuy = false" class="canbuy_pop_button">确认</div>
</yd-popup>

我需要给这个弹窗加圆角覆盖默认圆角，但是我加不上

**Comment by chenjiecloud** [comment]
`<yd-popup v-model="canBuy" position="center" width="70%" class="canbuy_pop" max-width="420px" :close-on-masker="false">
      <div class="canbuy_pop_top">
        <h4>无法行权</h4>
      </div>
      <div class="canbuy_pop_content">
        <p>最短行权期限为3个交易日</p>
      </div>
      <div @click="canBuy = false" class="canbuy_pop_button">确认</div>
    </yd-popup>`

**Comment by ydcss** [comment]
@chenjiecloud 感谢指出问题。目前确实不支持修改。只能通过重置样式.yd-popup-center实现。尽快修复。

**Comment by chenjiecloud** [comment]
好的，谢谢给出解答，等待你们的修复

**Comment by ydcss** [comment]
@chenjiecloud 你好，问题已经修复。默认是没有圆角了，背景色需用户自定设置。我先关闭issues，若还存在问题，麻烦重新开启。
