### ISSUE TITLE
请问一下 Jquery版的YDUI不能够定制化下载，是因为不再支持下载了吗？谢谢

### ISSUE THREAD

**Issue by s952787097** [ydcss/vue-ydui#514]
请问一下 Jquery版的YDUI不能够定制化下载，是因为不再支持下载了吗？谢谢

**Comment by makenum** [comment]
同问，谢谢。

**Comment by indiboy** [comment]
确实，vue有vue的好处，但是jq的也很有需求啊！~

**Comment by ydcss** [comment]
@s952787097 @makenum @indiboy 不好意思，前几天我的服务器宕机了，重启服务不完整，现已恢复下来。

**Comment by makenum** [comment]
@ydcss  你好，请问能否分享一下jQuery版未编译的源码呢？打扰了，谢谢。

**Comment by ydcss** [comment]
@makenum https://github.com/aloncai/ydui

**Comment by s952787097** [comment]
@ydcss 谢谢
