### ISSUE TITLE
CitySelect 组件里面的汉字不能自己设置

### ISSUE THREAD

**Issue by thunderwin** [ydcss/vue-ydui#519]
CitySelect 组件里面的汉字不能自己设置？

要做多语言不是很尴尬？

<img width="400" alt="a690df53-82c2-4e54-a66b-72c15c30fbaa" src="https://user-images.githubusercontent.com/2757750/37863894-1ae81d2a-2fa1-11e8-977c-d425f9ecbc20.png">

**Comment by ydcss** [comment]
请问你不看文档的吗？
