### ISSUE TITLE
我就想问下，jquery版本的那个ydui还继续维护么。

### ISSUE THREAD

**Issue by wk297090323** [ydcss/vue-ydui#520]
我是做后端开发的，喜欢做前端，但是现在的前端生态发展太迅猛，一时撵不上，还停留在jquery的阶段，希望jquery版本的能继续维护下去，给我们这些业余前端一点点喘气的时间。

**Comment by indiboy** [comment]
咱俩相反，我是后端还停留在使用帝国之类的，简单整一下可以，一些东西后端玩不来。

**Comment by ydcss** [comment]
不维护了。不是有提示了吗？
