### ISSUE TITLE
spinner数据改变问题

### ISSUE THREAD

**Issue by kouchao** [ydcss/vue-ydui#525]
#### 问题描述 

尊敬的作者你好，我在使用spinner想触发change事件，用于更新购物车数据，我应该怎么做？

#### 产生环境

- **使用版本：1.2.1-
- **引入方式：NPM
- **演示地址：无-

**Comment by kouchao** [comment]
watch 已解决。

**Comment by wangguoquan123** [comment]
watch怎么拿到上面遍历出来的值？
