### ISSUE TITLE
dev和build展现的页面不一样

### ISSUE THREAD

**Issue by SCzfdf** [ydcss/vue-ydui#526]
#### 问题描述 

dev和build展现的页面不一样
检查过后发现是一些样式没有覆盖原版的ydui样式

请问应该如何修改原版ydui样式

现在的修改方法(在vue页面直接修改渲染后的class)
![image](https://user-images.githubusercontent.com/30040164/38018154-af36d324-32a6-11e8-89f7-dc28809af4b1.png)

main文件
![image](https://user-images.githubusercontent.com/30040164/38018238-e76ffc20-32a6-11e8-8a04-299ca1ffb64a.png)

**Comment by ydcss** [comment]
你好，组件未提供的样式，请覆盖样式原形式修改。

**Comment by SCzfdf** [comment]
我就是覆盖样式修改的啊

**Comment by SCzfdf** [comment]
例如这个yd-navbar 的伪类  可是就是不生效
![image](https://user-images.githubusercontent.com/30040164/38023831-d5d48828-32b5-11e8-9e73-73016187c629.png)

**Comment by ydcss** [comment]
加个important试试。
```css
.yd-navbar:after {
     border-bottom: 0!important;
}
```

**Comment by SCzfdf** [comment]
抱歉最近有事没有及时回复,
加!important 是可以可是感觉治标不治本...
请问还有什么解决方案吗0.0
谢谢

**Comment by SCzfdf** [comment]
好像找到解决方案了...把main中的ydui样式在app前引入就好了0.0
![image](https://user-images.githubusercontent.com/30040164/38120763-4fa76998-33fd-11e8-8d37-2417f7d7023e.png)
