### ISSUE TITLE
tabbar组件，fixed定位固定底部后，会遮挡住正文的内容，需手动设置padding-bottom。

### ISSUE THREAD

**Issue by wk297090323** [ydcss/vue-ydui#529]
tabbar组件，fixed定位固定底部后，会遮挡住正文的内容，需手动设置padding-bottom。

**Comment by ydcss** [comment]
你好，因为yd-tabbar高度不固定，fixed定位是需要手动设置的内容下边距或者yd-tabbar父级容器高度的，我看看有什么好的解决办法。

**Comment by wk297090323** [comment]
谢谢回复，该用layout后，效果很完美！
