### ISSUE TITLE
List组件报错,引起移动端无法显示

### ISSUE THREAD

**Issue by FonHen** [ydcss/vue-ydui#53]
只要引用了List组件就会报错,PC上显示无问题,但是手机上引起页面不显示.
错误提示如下
`(Emitted value instead of an instance of Error) <yd-list-item v-for="item in list">: component lists rendered with v-for should have explicit keys. See https://vuejs.org/guide/list.html#key for more info.`

**Comment by ydcss** [comment]
你看看错误不在组件啊！小哥！你可以看看你发的链接https://vuejs.org/guide/list.html#key，
或者看看这里https://github.com/vuejs/vue/releases/tag/v2.2.0。
