### ISSUE TITLE
省市县级联

### ISSUE THREAD

**Issue by yanningH16** [ydcss/vue-ydui#534]
#### 问题描述 

   export default {
        data() {
            return {
                show1: false,
                model1: '',
                district: District
            }
        },
        methods: {
            result1(ret) {
                this.model = ret.itemName1 + ' ' + ret.itemName2 + ' ' + ret.itemName3;
            }
        }
    }

#### 产生环境

- **使用版本：-
- **引入方式：CDN | NPM
- **演示地址：-

#### 提示错误信息

1. 数据绑定上的变量名错误methods里面 应该为model1，应同上定义变量一致，请查阅
2. ...

#### 代码区域

```html
<script>
    alert('作者是个菜鸟！');
</script>
```

**Comment by ydcss** [comment]
你好，问题已修复。感谢指出问题。
