### ISSUE TITLE
关于yd-input组件无法绑定v-model

### ISSUE THREAD

**Issue by RoseEnd** [ydcss/vue-ydui#54]
yd-input动态的绑定v-model的时候，无法检测到数据变化

**Comment by RoseEnd** [comment]
![3](https://cloud.githubusercontent.com/assets/19225061/25514875/97a348dc-2c12-11e7-80d2-f6cf8c8474d3.png)

**Comment by RoseEnd** [comment]
我在路由钩子获取数据之后，yd-input的v-model无法显示相应的数据

**Comment by ydcss** [comment]
没看明白你的意思？

**Comment by RoseEnd** [comment]
我的意思是数据变化后v-model无法检测到

**Comment by ydcss** [comment]
你先试试动态绑定<input />能监听到数据吗？

**Comment by RoseEnd** [comment]
动态绑定普通input框是可以的，动态绑定yd-input就不行，数据变化后无法检测到

**Comment by ydcss** [comment]
贴你使用<yd-input/>的代码看看吧。

**Comment by RoseEnd** [comment]
![11](https://cloud.githubusercontent.com/assets/19225061/25519320/e4e19970-2c29-11e7-88c3-8ca16891725b.png)
![22](https://cloud.githubusercontent.com/assets/19225061/25519324/e97a617e-2c29-11e7-97b2-d5c16685ac99.png)

**Comment by RoseEnd** [comment]
给info附初始值可以正常显示，另外我单独写方法改变info，没有任何反应

**Comment by ydcss** [comment]
你好，我知道问题所在了，尽快修复。感谢你指出的问题。

**Comment by RoseEnd** [comment]
好的

**Comment by ydcss** [comment]
你好，问题已修复。

**Comment by RoseEnd** [comment]
神速啊，给个赞
