### ISSUE TITLE
输入框中按键盘上的输入的时候就会调用上拉菜单，我觉得这是个bug, 希望作者能够解决

### ISSUE THREAD

**Issue by chenjiecloud** [ydcss/vue-ydui#543]
#### 问题描述 

（作者是个菜鸟，请详细地描述问题，不要一句话带过，根据情况贴上使用代码）

#### 产生环境

- **使用版本：- 最新版本
- **引入方式：CDN | NPM
- **演示地址：-

#### 提示错误信息

1. 
2. ...

#### 代码区域

```html
<script>
    alert('作者是个菜鸟！');
</script>
```

**Comment by ydcss** [comment]
看不懂说什么？有没有代码？

**Comment by chenjiecloud** [comment]
我简单说下，一个input输入框，下面是个上拉菜单，在手机的键盘上有个相当于回车的按键，先把焦点点在input输入框的时候，按下回车键，会调用上拉菜单

<https://maas.mail.163.com/dashi-web-extend/html/proSignature.html?iconUrl=http://mail-online.nosdn.127.net/sma961fd8df6d8ad6ccae8b1bc8352b609.jpg&name=chenjiecloud&uid=chenjiecloud%40outlook.com&ftlId=3&items=%5B%22%E9%82%AE%E7%AE%B1%EF%BC%9Achenjiecloud%40outlook.com%22%5D>
[http://mail-online.nosdn.127.net/sma961fd8df6d8ad6ccae8b1bc8352b609.jpg]
chenjiecloud
邮箱：chenjiecloud@outlook.com


签名由 网易邮箱大师<https://mail.163.com/dashi/dlpro.html?from=mail88> 定制

在2018年04月04日 16:28，Ooo_My_God<mailto:notifications@github.com> 写道：

看不懂说什么？有没有代码？
