### ISSUE TITLE
这项目比vux和mint-ui都要强多了

### ISSUE THREAD

**Issue by kson34** [ydcss/vue-ydui#553]
建议作者把项目也git到oschina 码云上，让中国更多人知道，oschina官网的人说可以放到首页推荐一下呢。你这项目理应过万star的。

**Comment by ydcss** [comment]
你好，vue-ydui相比高大上的vux、mint-ui还是有很大差距，仍需努力啊~ 
之所以没有托管到osc，懒，无他。

**Comment by kson34** [comment]
你的兼容性强，个人测试过他们人兼容性比不上你，vux（IOS7，8，9大部分变形），mint IOS7,8小部分变形（而且文档差）

**Comment by airyland** [comment]
iOS 下的变形原因是 autoprefix 配置问题和组件没什么关系。

**Comment by ydcss** [comment]
@airyland 第一次离大神那么近，膜拜大神！
