### ISSUE TITLE
yd-input的required问题

### ISSUE THREAD

**Issue by RoseEnd** [ydcss/vue-ydui#56]
你好，貌似yd-input的required也不支持动态赋值，而且有个建议仅仅当required为true的时候再进行其它的验证如regex, min等等，这样会好很多

**Comment by ydcss** [comment]
你好，required是必填的，有些需求是可以为空，输入的话需符合规则。

**Comment by RoseEnd** [comment]
![33](https://cloud.githubusercontent.com/assets/19225061/25601881/d496732e-2f21-11e7-85f2-d7d26752b2ae.png)
