### ISSUE TITLE
popup 组件 close-on-masker 报错

### ISSUE THREAD

**Issue by myxingke** [ydcss/vue-ydui#564]
#### 问题描述 

Invalid prop: type check failed for prop "closeOnMasker". Expected Boolean, got String.
bool 当成字符串了

#### 提示错误信息

1. Invalid prop: type check failed for prop "closeOnMasker". Expected Boolean, got String.

#### 代码区域

```html
    <yd-popup v-model="loginPopupStatus" position="center" width="100%" height="100%" masker-opacity="1" close-on-masker="true">
      <div style="display: flex; flex: 1;">
        查看用户协议
      </div>
    </yd-popup>
```

**Comment by ydcss** [comment]
提示很清楚了啊：Expected Boolean, got String.
:close-on-masker="true"
