### ISSUE TITLE
yd-button 的 click 事件在特定场景下会误触发

### ISSUE THREAD

**Issue by vfasky** [ydcss/vue-ydui#565]
#### 问题描述 

重现： https://jsfiddle.net/eywraw8t/36975/
步骤： 点击 "show" => "1.key"
绑在 yd-button 的事件会误触发

#### 产生环境

- **使用版本：1.2.2 beta
- **引入方式：CDN
- **演示地址：https://jsfiddle.net/eywraw8t/36975/

**Comment by ydcss** [comment]
你好，我看了你pr的代码，并未解决此问题，原因是由 yd-cell-item 渲染后的label所致。
个人解决办法：
将 yd-cell-item 的type设置为div。
或 将 yd-popup 移到 yd-cell-group 外部。

**Comment by ericz9** [comment]
<yd-cell-item type="radio" v-for="item in categories" :key="item.Id" @click.native="chooseCategory(item)">

type为radio，点击时会出现触发两次的情况（版本1.2.6）
