### ISSUE TITLE
yd-input属性

### ISSUE THREAD

**Issue by suclu** [ydcss/vue-ydui#57]
required和min属性不支持动态赋值（其他属性还没试）

**Comment by ydcss** [comment]
你好，具体是怎么使用不行呢？

**Comment by suclu** [comment]
![a](https://cloud.githubusercontent.com/assets/20769006/25647001/cf843e64-2ff0-11e7-9b2e-68c6e1914346.png)

**Comment by suclu** [comment]
就是这样的，当我改变isEdit的boolean时，不起作用

**Comment by ydcss** [comment]
你好，问题已经修复。

**Comment by suclu** [comment]
你好   好像还是不行啊   另外  tab_pannel的active也不支持动态赋值

**Comment by suclu** [comment]
![2](https://cloud.githubusercontent.com/assets/20769006/25652301/1a7763d2-301a-11e7-8dbd-a67b070155f7.png)
就是把isEdit取反不生效

**Comment by ydcss** [comment]
![11](https://cloud.githubusercontent.com/assets/5517400/25652741/4339fc9c-301c-11e7-86dc-4afd7723e554.png)
![qq 20170503161531](https://cloud.githubusercontent.com/assets/5517400/25652662/e4f2df46-301b-11e7-8002-aa49478f01d2.png)
没毛病啊，小哥。

**Comment by suclu** [comment]
我单独写了个事件改变isEdit的值不起作用

**Comment by ydcss** [comment]
把你的完整的代码贴出来咯！

**Comment by suclu** [comment]
![aa](https://cloud.githubusercontent.com/assets/20769006/25653404/4f3d40a0-301f-11e7-8175-3b7777cdebe8.jpg)

**Comment by suclu** [comment]
![bb](https://cloud.githubusercontent.com/assets/20769006/25653420/5c6d1a16-301f-11e7-866a-1fe8fe0db56e.jpg)

**Comment by suclu** [comment]
我在路由钩子里改变它的值（初始值为false，改变后为true，取反之后应该为false，但是表现为true）

**Comment by ydcss** [comment]
我测试依旧没问题啊！ 你确定已经进入 if(data.status) { }这个判断里面了吗？

**Comment by suclu** [comment]
![cc](https://cloud.githubusercontent.com/assets/20769006/25654533/fe8621a4-3023-11e7-8cd2-5e6dc4ed8bac.jpg)
![dd](https://cloud.githubusercontent.com/assets/20769006/25654534/fea85468-3023-11e7-9de9-09f4400fde6e.jpg)

**Comment by suclu** [comment]
的确是进入了if的真区间

**Comment by ydcss** [comment]
![22222](https://cloud.githubusercontent.com/assets/5517400/25655218/c4a00bc8-3026-11e7-8c0e-cbf9f2b533c1.png)
![222](https://cloud.githubusercontent.com/assets/5517400/25655235/d3dfeaea-3026-11e7-85a2-8c6885fb2966.png)
四秒后必填，还是没看出哪里出问题？
另外你是怎么判断是否必填呢？

**Comment by suclu** [comment]
![ee](https://cloud.githubusercontent.com/assets/20769006/25655690/5db75252-3028-11e7-8e19-f0bd4e9ec810.jpg)

**Comment by ydcss** [comment]
确定组件用的是最新的吗？
如果是帮我排查一下吧，我重现不了，很麻烦。

**Comment by suclu** [comment]
组件是最新的刚更新过的

**Comment by ydcss** [comment]
整理一个能重现问题的小示例发我邮箱吧！
surging2@qq.com
谢谢了！

**Comment by suclu** [comment]
我昨天已经发过你邮箱了

**Comment by ydcss** [comment]
你好，我已经收到邮件了，已发现问题所在，正在修复中....

**Comment by ydcss** [comment]
你好，问题已经修复。确实是我的代码的问题。感谢你帮助我解决问题。

**Comment by suclu** [comment]
亲  那个active的还没解决

**Comment by suclu** [comment]
嗯  但是那个active还不支持

**Comment by ydcss** [comment]
好的，我现在有点忙，过后我修复哟。

**Comment by ydcss** [comment]
你好，已修复。
