### ISSUE TITLE
下拉刷新组件一直报Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined的错误

### ISSUE THREAD

**Issue by wtg0122** [ydcss/vue-ydui#58]
下拉刷新组件一直报Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined的错误

**Comment by ydcss** [comment]
贴你使用的代码出来看看吧。

**Comment by wtg0122** [comment]
------------问题描述----------
列表页点到详细页，然后再后退到列表页，会出现如上错误。   
 
    <yd-infinitescroll :on-infinite="loadList">
    <yd-list theme="1" slot="list">
    <div class="container-fluid">
    
    <div class="mi-fall " id="fall-left">
        
        <div class="mi-node-item" v-for="item in left_data">
            <router-link :to="{name:'diary',params:{id:item.ID}}" tag="div" class="mi-pic-box">
                <img src="http://img1.shikee.com/try/2016/06/23/14381920926024616259.jpg" alt="">
            </router-link>
            
              <div class="mi-node-overview">
                    <router-link :to="{name:'diary',params:{id:item.ID}}" tag="div"  class="mi-node-title">
                       {{item.title}}
                    </router-link>
                    <router-link :to="{name:'diary',params:{id:item.ID}}" tag="div"  class="mi-node-sketch">
                       {{item.content}}
                    </router-link>`
                    <div class="mi-node-head rel">
                        <img class="head-img vam" :src="item.avatar" :alt="item.user_name">
                        <div class="head-name vam">{{item.user_name}}</div>
                        <span class="mi-node-like" ><i class="icon-like-outline"></i> <span class="color6">{{item.likes}}</span></span>
                    </div> 
                </div>
        </div>
    </div>
    
        <div class="mi-fall " id="fall-right">
             <div class="mi-node-item" v-for="item in right_data">
                <router-link :to="{name:'diary',params:{id:item.ID}}" tag="div"  class="mi-pic-box">
                    <img src="http://img1.shikee.com/try/2016/06/23/14381920926024616259.jpg" alt="">
                </router-link>
                
                <div class="mi-node-overview">
                    <router-link :to="{name:'diary',params:{id:item.ID}}" tag="div"  class="mi-node-title">
                       {{item.title}}{{item.ID}}
                    </router-link>
                    <router-link :to="{name:'diary',params:{id:item.ID}}" tag="div"  class="mi-node-sketch">
                       {{item.content}}
                    </router-link>
                    <div class="mi-node-head rel">
                        <img class="head-img vam" :src="item.avatar" :alt="item.user_name">
                        <div class="head-name vam">{{item.user_name}}</div>
                        <span class="mi-node-like" ><i  class="icon-like-outline"></i> <span class="color6">{{item.likes}}</span></span>
                    </div> 
                </div>
            </div>
        </div>
         
    </div>
      </yd-list>
        
        <span slot="doneTip">啦啦啦，啦啦啦，没有数据啦~~</span>
        
        
    </yd-infinitescroll>
----------------------------------------方法-----------------------------
       loadList:function() {
            this.axios({method:'get',url:'/API/Notes/getList',params:{type :this.type,tagID :this.tagID,lastid :this.lastid,num:this.num}}).then(res => {
                  if(res.data.code==10000){
                            this.lastid = res.data.data.lastid;
                            let data = res.data.data.list;
                            for (let i=0; i<data.length; i++){
                                if(data[i].ID%2==0) {
                                    this.left_data.push(data[i])
                                } else {
                                    this.right_data.push(data[i])
                                } 
                            }
                            this.more==res.data.data.more
                    }
                    // 请求为空说明全部加载完毕
                    if (res.data.code==10801) {
                         window.$yduiBus.$emit('ydui.infinitescroll.loadedDone');
                    }
                // /* 单次请求数据完毕 */
                window.$yduiBus.$emit('ydui.infinitescroll.finishLoad');
              
            })
        }
----------------------截图一直传不了，只能复制代码。见谅------------

**Comment by ydcss** [comment]
一个页面使用两个下拉加载吗？请更新至最新版尝试（使用方法有变动，请参看文档）。

**Comment by ydcss** [comment]
你好，问题解决了吗？
