### ISSUE TITLE
您好，能否新增上传图片并裁剪图片上传的组件

### ISSUE THREAD

**Issue by greenmonking** [ydcss/vue-ydui#580]
#### 问题描述 

（作者是个菜鸟，请详细地描述问题，不要一句话带过，根据情况贴上使用代码）

#### 产生环境

- **使用版本：-
- **引入方式：CDN | NPM
- **演示地址：-

#### 提示错误信息

1. 
2. ...

#### 代码区域

```html
<script>
    alert('作者是个菜鸟！');
</script>
```

**Comment by ydcss** [comment]
否
