### ISSUE TITLE
可以增加一个图片上传的组件吗？

### ISSUE THREAD

**Issue by misskter** [ydcss/vue-ydui#581]
在使用的过程中 有个业务是上传用户头像，需要有个图片是显示用户的头像，这个图片上放着+号 点击这个可以进行选择图片进行上传  ，上传完成以后 这个图片框显示的是用户上传的图片，这个功能大神可以实现吗 ？

**Comment by hlbj105** [comment]
定义一个空数组，把回调的图片push进去，上面v-for循环就行了
