### ISSUE TITLE
六位密码安全键盘组件,无法自动弹出

### ISSUE THREAD

**Issue by congzi97** [ydcss/vue-ydui#59]
在本地数据设置为 true 的时候无法自动弹出键盘，但通过点击能弹出
截图这种情况，无法自动弹出键盘
![2017-05-02 11 26 46](https://cloud.githubusercontent.com/assets/28304722/25625337/d9ace13c-2f8e-11e7-87da-0a418a7f36a1.png)

**Comment by ydcss** [comment]
你好，问题已经修复。感谢你指出的问题。
