### ISSUE TITLE
yd-lightbox图片预览，通过数据绑定添加的数据图片不能预览

### ISSUE THREAD

**Issue by zhouwei0046** [ydcss/vue-ydui#594]
#### 问题描述 

（作者是个菜鸟，请详细地描述问题，不要一句话带过，根据情况贴上使用代码）

#### 产生环境

- **使用版本：-
- **引入方式：CDN | NPM
- **演示地址：-

#### 提示错误信息

1. 
2. ...

#### 代码区域

```html
<script>
    alert('作者是个菜鸟！');
</script>
```

**Comment by ydcss** [comment]
注意：若图片数据为异步时，需出入num 的props。
