### ISSUE TITLE
使用yd-layout组件，并通过 slot="navbar" 和 slot="tabbar" 定制页头和页尾，此时中间的内容部分首尾都被挡住了部分内容。

### ISSUE THREAD

**Issue by udoinglike** [ydcss/vue-ydui#601]
#### 问题描述 

     使用yd-layout组件，并通过 slot="navbar" 和 slot="tabbar" 定制页头和页尾，此时中间的内容部分首尾都被挡住了部分内容。

我在内容部分循环显示了50行，结果1~3行被navbar挡住了，滚动到最底下，49，50行被tabbar挡住了。

请问我需要怎么调整？YDUI学习中。感谢！

#### 产生环境

- **使用版本：1.2.2
- **引入方式：NPM

#### 提示错误信息

没有报错。
 
![tim 20180518105327](https://user-images.githubusercontent.com/9944270/40213784-e14852f6-5a89-11e8-8626-f70ff6b177f3.png)

#### 代码区域

```html
<template>
    <yd-layout >
        <yd-navbar slot="navbar" title="NavBar" fixed>
            <router-link to="#" slot="left">
                <yd-navbar-back-icon></yd-navbar-back-icon>
            </router-link>
        </yd-navbar>

        <div v-for="n in 50" :key="n">{{n}}乱七八糟的内容在这里，超出容器，将出现滚动条。</div>

        <!-- fixed可以将导航栏固定到屏幕底部 -->
        <yd-tabbar slot="tabbar" fixed>
            <yd-tabbar-item title="首页" link="#" active>
                <yd-icon name="home" slot="icon"></yd-icon>
            </yd-tabbar-item>
            <yd-tabbar-item title="购物车" link="#">
                <yd-icon name="shopcart-outline" slot="icon"></yd-icon>
            </yd-tabbar-item>
            <yd-tabbar-item title="个人中心" link="#">
                <yd-icon name="ucenter-outline" slot="icon"></yd-icon>
            </yd-tabbar-item>
        </yd-tabbar>

    </yd-layout>

</template>
<script>
export default {

}
</script>
```

**Comment by ydcss** [comment]
你好，设置 &lt;div id="app" style="height: 100%"&gt; 这样试试

**Comment by udoinglike** [comment]
试过了，我在index.html和App.vue 里都添加了height：100%。
<div id="app" style="height: 100%"></div>
仍然没效果。
![tim 20180521155151](https://user-images.githubusercontent.com/9944270/40296342-ee0956b6-5d0e-11e8-88cd-d0f6658ecf17.png)

**Comment by udoinglike** [comment]
![tim 20180521155151](https://user-images.githubusercontent.com/9944270/40296384-01d2b07a-5d0f-11e8-9920-e4d7e3dae915.png)

**Comment by ydcss** [comment]
不好意思，看错了。yd-tabbar 和 yd-navbar 去掉fixed.

**Comment by ydcss** [comment]
同时 &lt;div id="app" style="height: 100%"&gt;

**Comment by udoinglike** [comment]
感谢指导，在App.vue里```<div id="app" style="height: 100%">```， 且去掉组件的fixed属性，解决了。非常感谢！ 这个问题可以关闭了。
