### ISSUE TITLE
官网layout资料关于bottom写错了。

### ISSUE THREAD

**Issue by udoinglike** [ydcss/vue-ydui#604]
#### 问题描述 

官网layout资料关于bottom写错了。正确应该是name="bottom"
 
![tim 20180521160345](https://user-images.githubusercontent.com/9944270/40296918-b44a0e64-5d10-11e8-87e7-42d3ef58dd72.png)

#### 产生环境

- **使用版本：-
- **引入方式：CDN | NPM
- **演示地址：-

#### 提示错误信息

1. 
2. ...

#### 代码区域

``` 
原代码<slot name="top“></slot>

正确的应该是<slot name="bottom“></slot>

```

**Comment by ydcss** [comment]
感谢，尽快修复。

**Comment by ydcss** [comment]
你好，已修复。

**Comment by udoinglike** [comment]
非常感谢，有看到更新了，还贴心的加上提示：不要在组件上添加fixed属性（我就是犯了这个错）。不过好像写错单词了。#_#

![tim 20180522091516](https://user-images.githubusercontent.com/9944270/40337252-0c5967ae-5da1-11e8-9689-950d3d25c893.png)
