### ISSUE TITLE
关于InfiniteScroll能不能提供在执行所有数据请求完成事件之后初始化的事件

### ISSUE THREAD

**Issue by RoseEnd** [ydcss/vue-ydui#61]
因为在业务中有特殊的需求，当执行this.$refs.infinitescrollDemo.$emit('ydui.infinitescroll.loadedDone');之后通过某些操作之后需要重新加载数据，希望可以提供可以初始化的事件，使其可以重新加载，万分感谢

**Comment by ydcss** [comment]
之后执行location.reload();不就好了？
