### ISSUE TITLE
checkbox 在 yd-navbar 中显示有问题

### ISSUE THREAD

**Issue by 1847211504** [ydcss/vue-ydui#616]
#### 问题描述 

 我的应用场景想在 yd-navbar 中引用 checkbox，但是在目前的版本中似乎不能正常工作
请见场景复现：https://jsfiddle.net/3pabujhz/5/

#### 产生环境

- **使用版本：- v1.2.2 beta
- **引入方式：CDN
- **演示地址：- https://jsfiddle.net/3pabujhz/5/

**Comment by ydcss** [comment]
你好，已修复。
