### ISSUE TITLE
按需加载使用textarea组件 ，双向绑定未生效

### ISSUE THREAD

**Issue by wenyuking** [ydcss/vue-ydui#618]
#### 按需加载使用textarea组件 ，双向绑定未生效

在按需加载使用textarea组件时，发现双向绑定未生效，在查看`node_modules`中的`ydui`包内的`vue-ydui/dist/lib.rem/textarea/index.js`，

```javascript
watch: {
	mlstr: function(e) {
		this.$emit("input", e), "function" == typeof this.change && this.change(), this.showCounter && (this.num = e.length);
	}
}
```

对比了`github`中`src`里面的源码，发现缺少以下代码

```javascript
value: function (e) {
       this.mlstr = e
}
```
修改`dist`文件夹内代码，问题得以解决，应该是`dist`目录内`textarea`文件版本过老

#### 产生环境

- **使用版本：1.2.2
- **引入方式：NPM
- **演示地址：-

**Comment by ydcss** [comment]
你好，已修复。感谢！
