### ISSUE TITLE
关于InfiniteScroll能不能提供在执行所有数据请求完成事件之后初始化的事件

### ISSUE THREAD

**Issue by RoseEnd** [ydcss/vue-ydui#62]
![12](https://cloud.githubusercontent.com/assets/19225061/25649917/c2402e82-300b-11e7-8a09-f43594f6be49.png)

刚刚不小心关掉了issures, 使用location.reload()会刷新页面，目前登陆状态保存在vuex中，刷新会导致登陆状态丢失，上图中多次操作共享一个滚动加载容器，根据状态获取不同的数据，此时当全部订单执行this.$refs.infinitescrollDemo.$emit('ydui.infinitescroll.loadedDone');之后获取其它的状态的时候，无法重新触发加载

**Comment by RoseEnd** [comment]
所以需要有初始化的事件让其可以重新加载数据，如果不共享加载容器，由于模板都是一样，代码过于臃肿，所以才会出现这样的需求

**Comment by ydcss** [comment]
好的，我明白你的需求，确实会出现这样的需求，我尽快完善。

**Comment by RoseEnd** [comment]
好的，万分感谢

**Comment by ydcss** [comment]
你好，问题已经修复。
重新初始化：this.$refs.infinitescrollDemo.$emit('ydui.infinitescroll.reInit');

**Comment by RoseEnd** [comment]
好的，谢谢，已生效
