### ISSUE TITLE
如何在spinner加减按钮上绑定click事件

### ISSUE THREAD

**Issue by lxiaosky** [ydcss/vue-ydui#620]
#### 问题描述 

我需要在加减按钮上绑定事件,比如做购物车,我需要在用户点击后提交给后端,用户连续点击我需要做函数防抖,现在无法在按钮上绑定事件,如果用计算属性监听值的变化,无法满足我的需求

#### 产生环境

- **使用版本：-
- **引入方式：CDN | NPM
- **演示地址：-

#### 提示错误信息

1. 
2. ...

#### 代码区域

```html
<script>
    alert('作者是个菜鸟！');
</script>
```

**Comment by ydcss** [comment]
你好，已修复。通过给yd-spinner绑定callback方法。文档稍后更新
