### ISSUE TITLE
yd-countdown回调函数无限调用

### ISSUE THREAD

**Issue by 13678460136** [ydcss/vue-ydui#625]
#### 问题描述 

在使用yd-countdown组件时 回调函数会被无限调用，无法停止，暂时不知道发生该问题的原因

#### 产生环境

- **使用版本：-
- **引入方式：NPM
- **演示地址：-

#### 提示错误信息

浏览器无限打印 1

####  
yd-countdown time="5" :callback="countdown" /yd-countdown

methods: {
            countdown() {
                console.log(1)
            }
        }

**Comment by 13678460136** [comment]
<template>
        <yd-countdown time="5" :callback="countdown" timetype="second" format="{%m}分{%s}秒"> 
        </yd-countdown>
</template>

<script>
    export default {
        methods: {
            countdown() {
                console.log(1)
            }
        }
    }
</script>

浏览器会无限打印 1

**Comment by 13678460136** [comment]
在created里面用axios.then 改变countdown绑定的时间，就会出现无限回调的情况

**Comment by ydcss** [comment]
你好，已修复。
