### ISSUE TITLE
YDUI yd-countup的endnum属性报错

### ISSUE THREAD

**Issue by FancyOrNot** [ydcss/vue-ydui#640]
#### 问题描述 

YDUI yd-countup的endnum属性报错，[Vue warn]: Invalid prop: custom validator check failed for prop "endnum".页面数据正常

#### 产生环境

- **使用版本：-
- **引入方式：NPM
- **演示地址：-

#### 提示错误信息

1.vue.esm.js?efeb:591 [Vue warn]: Invalid prop: custom validator check failed for prop "endnum".

found in

---> <YdCountup>
       <Index> at src\pages\index.vue
         <App> at src\App.vue
           <Root>

#### 代码区域

<yd-countup :endnum="result1.column9 ? result1.column9 : 0" suffix="%" decimals="2" :start="start"></yd-countup>
<script>
    alert('能否去掉这个警告，爱你哟！');
</script>
```

**Comment by ydcss** [comment]
你好，endnum格式为/^([0]|[1-9]\d*)(\.\d*)?$/ 看看你传入的是否符合规则哦。
