### ISSUE TITLE
滚动加载调用初始化的一个问题

### ISSUE THREAD

**Issue by 290115231** [ydcss/vue-ydui#65]
我在调用infinitescroll组件的reinit事件后，发现一个问题，就是如果我在调用这个事件之前将滚动条拉离顶端，那么调用初始化事件就会自动触发一次on-infinite绑定的函数。如果滚动条在顶端则不会。
不知道是我调用的该事件的方法不对，还是其他原因？

**Comment by ydcss** [comment]
你好，问题已收到。确定是存在问题。尽快修复。

**Comment by ydcss** [comment]
你好，问题已经修复。
