### ISSUE TITLE
表单预览文档有误 yd-preview

### ISSUE THREAD

**Issue by IBAS0742** [ydcss/vue-ydui#650]
## [Preview](http://vue.ydui.org/docs/#/preview)
![ydui](http://www.sunibas.cn/files/ydui.png)

## [Tabbar](http://vue.ydui.org/docs/#/tabbar)
![ydui](http://www.sunibas.cn/files/ydui-tabbar.png)

**Comment by ydcss** [comment]
你好，已修复。
