### ISSUE TITLE
请教打包问题，那位知道的指教一下，我还是菜鸟！！！

### ISSUE THREAD

**Issue by ccq502849336** [ydcss/vue-ydui#656]
用npm run build 打包后，请问打包后的文件在什么位置？？？ 我看了dist 文件，里面没有index.html文件，放在服务器上无法访问，是否我的操作错误了？？？ 请指教

**Comment by YYQ8023** [comment]
你可以用vue-cli生成项目，而且最新的vue-cli是有GUI的，应该很方便，而且文档也有中文的，很快就能上手。
建议新手一步一步跟着文档来。
