### ISSUE TITLE
滚动加载问题

### ISSUE THREAD

**Issue by congzi97** [ydcss/vue-ydui#66]
问题:在我的电脑测试，无法预览效果，在官网DEMO可以
看一下截图，发现官网 生成了 <section></section> ，在我的电脑却没有，是否是这个原因？
![2017-05-07 10 33 34](https://cloud.githubusercontent.com/assets/28304722/25777587/eba67578-3313-11e7-9b8a-1f1b0f289a17.png)
![2017-05-07 10 37 32](https://cloud.githubusercontent.com/assets/28304722/25777588/ebf313c4-3313-11e7-86ae-6cc87d486ece.png)

**Comment by ydcss** [comment]
麻烦发你使用的代码上来哟！

**Comment by congzi97** [comment]
我把文档的代码复制下来了，滑动到底部没有自动加载...

![Uploading 屏幕快照 2017-05-09 上午12.38.18.png…]()
![Uploading 屏幕快照 2017-05-09 上午12.43.35.png…]()
![Uploading 屏幕快照 2017-05-09 上午12.43.56.png…]()

**Comment by congzi97** [comment]
<template>
  <yd-infinitescroll :on-infinite="loadList" ref="infinitescrollDemo">

    <yd-list theme="1" slot="list">
      <yd-list-item v-for="item in list">
        <img slot="img" :src="item.img">
        <span slot="title">{{item.title}}</span>
        <yd-list-other slot="other">
          <div>
            <span class="list-price"><em>¥</em>{{item.marketprice}}</span>
            <span class="list-del-price">¥{{item.productprice}}</span>
          </div>
          <div>content</div>
        </yd-list-other>
      </yd-list-item>
    </yd-list>

    
    <span slot="doneTip">啦啦啦，啦啦啦，没有数据啦~~</span>

    
    <img slot="loadingTip" src="http://static.ydcss.com/uploads/ydui/loading/loading10.svg"/>

  </yd-infinitescroll>
</template>

<script type="text/babel">
  export default {
    data() {
      return {
        page: 1,
        pageSize: 10,
        list: [
          {
            img: "http://img1.shikee.com/try/2016/06/23/14381920926024616259.jpg",
            title: "标题标题标题标题标题",
            marketprice: 56.23,
            productprice: 89.36
          },
          {
            img: "http://img1.shikee.com/try/2016/06/21/10172020923917672923.jpg",
            title: "骆驼男装2016夏装男士短袖T恤 圆领衣服 印花男装体恤 半袖打底衫",
            marketprice: 56.23,
            productprice: 89.36
          },
          {
            img: "http://img1.shikee.com/try/2016/06/23/15395220917905380014.jpg",
            title: "条纹短袖T恤男士韩版衣服大码潮流男装夏季圆领体恤2016新款半袖",
            marketprice: 56.23,
            productprice: 89.36
          },
          {
            img: "http://img1.shikee.com/try/2016/06/25/14244120933639105658.jpg",
            title: "夏季青少年衣服男生潮牌t恤 男士 夏秋学生 日系棉短袖半袖男小衫",
            marketprice: 56.23,
            productprice: 89.36
          },
          {
            img: "http://img1.shikee.com/try/2016/06/26/12365720933909085511.jpg",
            title: "2016夏装新款时尚潮流短袖T恤男纯棉V领日系青少年韩版夏季上衣服",
            marketprice: 56.23,
            productprice: 89.36
          },
          {
            img: "http://img1.shikee.com/try/2016/06/19/09430120929215230041.jpg",
            title: "男装衣服男夏t恤 男士短袖t恤圆领夏季潮牌宽松原宿风半截袖男",
            marketprice: 56.23,
            productprice: 89.36
          }
        ]
      }
    },
    methods: {
      loadList() {
          console.log('到这里了')
          this.$refs.infinitescrollDemo.$emit('ydui.infinitescroll.finishLoad');
          this.page++;
      }
    }
  }
</script>

**Comment by ydcss** [comment]
1、“到这里了”，你要请求相应数据，附加给this.list啊，不然没有数据，滚动不了的啊！
2、另外针对“问题:在我的电脑测试，无法预览效果，在官网DEMO可以”这个问题，官网用了yd-layout组件，滚动容器是#scrollView，你的是滚动容器是window，HTML渲染当然是不一样的啊，但是都是可以的哟。

**Comment by ydcss** [comment]
你好，问题解决了吗？

**Comment by congzi97** [comment]
昨天电脑坏了，今天下午测试一下。。

**Comment by congzi97** [comment]
OK,感谢你的回答，谢谢
