### ISSUE TITLE
请问下怎么将这个库打包后浏览？

### ISSUE THREAD

**Issue by policymakers** [ydcss/vue-ydui#661]
#### 问题描述 
请问下怎么将这个库打包后浏览？麻烦作者大哥教下。

#### 产生环境

- **使用版本：-
- **引入方式：CDN | NPM
- **演示地址：-

#### 提示错误信息

1. 
2. ...

#### 代码区域

```html
<script>
    alert('作者是个菜鸟！');
</script>
```

**Comment by ydcss** [comment]
你好，这个是webpack的知识哦，打包后会根据你的配置生成对应的js，新建一个页面引入就好啦。看看这里吧。https://www.webpackjs.com/
