### ISSUE TITLE
yd-infinitescroll中循环数据样式没办法通过字段去选择对应要显示的布局

### ISSUE THREAD

**Issue by xiaochegnzi0** [ydcss/vue-ydui#663]
#### 问题描述 
你好，yd-infinitescroll组件中循环内容无法在外层添加div，想要实现的效果为，在循环时，通过字段判断需要显示的布局

#### 产生环境

- **使用版本：-
- **引入方式：CDN | NPM
- **演示地址：-

#### 提示错误信息

1. 
2. ...

#### 代码区域

<yd-infinitescroll :callback="loadList" ref="infinitescrollDemo">

        <yd-list theme="1" slot="list">
            <yd-list-item v-for="(item, key) in list" :key="key" :hh="item.type" v-show="item.type == 0">
          //在这无法添加div包裹整个循环内容
                    <img slot="img" :src="item.img">
                    <span slot="title">{{item.title}}</span>
                    <yd-list-other slot="other">
                        <div>
                            <span class="list-price">{{item.marketprice}}评论</span>
                            <span class="list-del-price">{{item.productprice}}</span>
                        </div>
                        
                    </yd-list-other>
            </yd-list-item>
        </yd-list>

        
        <span slot="doneTip">没有更多</span>

        
        <img slot="loadingTip" src="http://static.ydcss.com/uploads/ydui/loading/loading10.svg"/>

    </yd-infinitescroll>

**Comment by xiaochegnzi0** [comment]
有人帮我解决下吗？

**Comment by ydcss** [comment]
@xiaochegnzi0 
```html
<yd-list theme="1" slot="list">
    <yd-list-item v-for="(item, key) in list" :key="key">
        //在这无法添加div包裹整个循环内容
        <template v-if="item.type === 0">
            布局1
        </template>
        <template v-else>
            布局2
        </template>
    </yd-list-item>
</yd-list>
```
