### ISSUE TITLE
cityselect的默认“省市区"不能动态绑定

### ISSUE THREAD

**Issue by 15521054523** [ydcss/vue-ydui#665]
#### 问题描述 

（作者是个菜鸟，请详细地描述问题，不要一句话带过，根据情况贴上使用代码）

#### 产生环境

- **使用版本：- 1.2.2
- **引入方式：NPM
- **演示地址：-

#### 提示错误信息

1. cityselect的默认“省市区"不能动态绑定，写成静态就可以
2. ...

#### 代码区域

![image](https://user-images.githubusercontent.com/19297519/44070427-60dbe520-9fb6-11e8-9ea2-249883aebc44.png)
![image](https://user-images.githubusercontent.com/19297519/44070429-62c9c3f2-9fb6-11e8-90fc-54d4ae840cba.png)

---------------------------------------分割线----------------------------------------------
 
![image](https://user-images.githubusercontent.com/19297519/44070434-6dda7728-9fb6-11e8-9a35-12ff5ecda586.png)
![image](https://user-images.githubusercontent.com/19297519/44070435-6fc807da-9fb6-11e8-98ed-6a860f2d3b56.png)

**Comment by ydcss** [comment]
:provance="cityBox.cityBox" 你确定没写错？
