### ISSUE TITLE
倒计时结束后的回调函数会重复触发

### ISSUE THREAD

**Issue by wujianrong** [ydcss/vue-ydui#669]
#### 问题描述 
倒计时结束后的回调函数会重复触发，请问结束后如果需要重新再开始倒计时要怎么实现？
 
 

#### 代码区域
<yd-countdown :callback="endUp"   :time="30" timetype="second"></yd-countdown>
 
endUp(){
 
        alert()
 
      }

**Comment by ydcss** [comment]
你好，问题已修复。
