### ISSUE TITLE
rem适配

### ISSUE THREAD

**Issue by EnoughLove** [ydcss/vue-ydui#673]
如果将ydui.rem.js单独引入，我写一个宽为200px的块    和宽为2rem的块   应该是一样大的  为啥宽度差距很大

**Comment by ydcss** [comment]
1、请确认你的设计图文档宽度是否和ydui.rem.js一致。
2、确定浏览器模拟手机是否跟设计图一致。

**Comment by ydcss** [comment]
假设你设计图是2x的，200px应该写是的100px。
