### ISSUE TITLE
【疑惑】采用rem方式，引入ydui.flexible.js之后，html为50px，body也为50px，但是

### ISSUE THREAD

**Issue by hchlw** [ydcss/vue-ydui#681]
#### 问题描述 

采用rem方式，引入ydui.flexible.js之后，html为50px，body也为50px，但是引入ydui.rem.js，看到里面代码强制将body设置为font-size:12px。请问为何是这种设计，疑惑小白

**Comment by ydcss** [comment]
rem是根据html元素的字体大小来决定。
