### ISSUE TITLE
CheckList多选列表使用v-for循环遍历列表的时候val值用index代替不能解析为数字

### ISSUE THREAD

**Issue by MrMrZ** [ydcss/vue-ydui#685]
#### 问题描述 
CheckList多选列表，想请问一下，循环遍历列表的时候，使用v-for进行遍历，checkList中的每一项有一个val值，这个值用v-for循环中的index代替的时候为什么不能解析为数字呢？还是index，导致我选择单项的时候变成全选了，因为循环遍历处理的每一个项的val值都是字符串index，而不是对应的数组下标，求解释
 作者是个菜鸟，请详细地描述问题，不要一句话带过（特别是将描述放在标题上的），根据情况贴上代码

 处理 issue 是件很耗精力的事，请提交 issue 前考虑一下是否把问题说清楚了

#### 产生环境

- **使用版本：-
- **引入方式：CDN | NPM
- **演示地址：-

#### 提示错误信息

1. 
2. ...

#### 代码区域

```html
 <yd-checklist v-model="checklist3" ref="checklistDemo" :callback="change" class="list">
            <yd-checklist-item val="index" class="single" v-for="(item,index) in msg"> 
                <div class="msg">
                    <div class="left">
                        <img src="../image/group1@3x.png" alt="">
                   </div>
                   <div class="right">
                     <div class="description">{{item.txt}}</div>
                     <div class="time">{{item.time}}</div>
                   </div>
                 </div>
            </yd-checklist-item>
        </yd-checklist>
```

**Comment by ydcss** [comment]
:val="index"

**Comment by MrMrZ** [comment]
好的好的，明白了，现在发现一个问题，全选的那个按钮在文档上的案例上是可以全选的，但是我把案例copy下来，在手机端上，发现点击全选没有效果，但是可以触发点击，就是没有实现全选的功能，不知道 是为什么呢，代码如下，全选按钮没有效果
` <yd-checkbox v-model="isCheckAll" shape="circle" :change="checkAll" class="selectAll">全选</yd-checkbox>
        <yd-checklist v-model="checklist3" ref="checklistDemo" :callback="change" class="list">
            <yd-checklist-item :val="index" class="single" v-for="(item,index) in msg"> 
                <div class="msg">
                    <div class="left">
                        <img src="../image/group1@3x.png" alt="">
                   </div>
                   <div class="right">
                     <div class="description">{{item.txt}}</div>
                     <div class="time">{{item.time}}</div>
                   </div>
                 </div>
            </yd-checklist-item>
        </yd-checklist>`
