### ISSUE TITLE
编辑状态下值无法回填到input中

### ISSUE THREAD

**Issue by wtg0122** [ydcss/vue-ydui#69]
## 问题描述 
eg:地址列表点击编辑，跳转到编辑页面，正常是要在input中回填原来的地址，试了下用yd-input 不能显示，普通的input显示就没问题，switch复选框也是出现这问题。status已经是true状态了，switch还是关闭状态
（简明扼要地描述一下问题）

## 产生环境

- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
chrome
- **演示地址：**

## 复现步奏

1.
2.
...

**Comment by ydcss** [comment]
用的是哪个版本的？更新至最新版本试试。

**Comment by wtg0122** [comment]
0.4.5

**Comment by ydcss** [comment]
更新至最新版。你说的问题已经修复过了。

**Comment by wtg0122** [comment]
好的

**Comment by ydcss** [comment]
你好，问题解决了吗？

**Comment by wtg0122** [comment]
input 框问题是解决了，滚动加载还是有问题，
滚动加载偶尔会出现 Can't find the refs.tag!
http://www.megongshe.com/列表页采用滚动加载
http://www.megongshe.com/me_diary/diary/29详细页评论也采用滚动加载
列表页点到详细页鼠标上下拖动。偶尔会出现，概率事件
![tim 20170511140924](https://cloud.githubusercontent.com/assets/17006272/25935110/f3ad2d32-3653-11e7-86bb-e9c06d4f6cc7.png)

**Comment by ydcss** [comment]
问题收到，经核实，确实存在这个问题。尽快修复。

**Comment by ydcss** [comment]
你好，该报错问题已经修复。感谢你指出的问题。

**Comment by wtg0122** [comment]
好的，我升级到最新版本看看，解决问题速度很高效，给个赞

**Comment by wtg0122** [comment]
期待出时间控件

**Comment by ydcss** [comment]
关于时间组件，一直没想到良好的操作体验，一直搁置。你有什么好的想法么？

**Comment by wtg0122** [comment]
年月日格式可以定制，有些人不喜欢xx年xx月xx日这种形式的，那可以去掉年月日中文。然后回调函数分别获取年、月、日，参考你省区市三级联动插件，：done.
一直发不了图片，样式参考京东个人信息中的年月日。

**Comment by ydcss** [comment]
![qq 20170515161815](https://cloud.githubusercontent.com/assets/5517400/26048491/f89ceb82-3989-11e7-9e35-d8f9731e2c8d.jpg)
这样的样式么？这个好像是调用系统默认样式的。

**Comment by wtg0122** [comment]
他这个是调用默认样式。iPhone不是长这样， 他可能只用了<input type="date"/>
![tim 20170515155755_](https://cloud.githubusercontent.com/assets/17006272/26048624/7a040408-398a-11e7-9636-4bc5e720ef53.png)

**Comment by ydcss** [comment]
好的，我知道，谢谢你提的建议。

**Comment by wtg0122** [comment]
为什么不能new issue了？，更新到0.6.2了，下拉加载问题好像解决了。赞！！！
