### ISSUE TITLE
下拉刷新遇到的问题

### ISSUE THREAD

**Issue by lxzjsj** [ydcss/vue-ydui#70]
http://www.dlxc6.com:8088/m/index.php?mod=category&catid=4&cityid=1
在浏览器手机模式下测试的，
1.console.log(vue.$refs);打印是空，不知道为什么?
2.如何把下拉刷新和滚动加载结合起来? 
谢谢!

**Comment by ydcss** [comment]
发的什么鬼链接？

**Comment by lxzjsj** [comment]
在chrome浏览器手机模式下测试的

**Comment by ydcss** [comment]
![qq 20170510111737](https://cloud.githubusercontent.com/assets/5517400/25881928/5b48d438-3572-11e7-8eb8-4406a5b00341.png)
报错的
