### ISSUE TITLE
关于滚动加载有多个滚动容器的时候，不管滚动加载哪一个容器，第一次的时候所有的滚动加载方法都会被触发，第二次及以后都是正常的

### ISSUE THREAD

**Issue by RoseEnd** [ydcss/vue-ydui#71]

**Comment by RoseEnd** [comment]
补充：这个是和选项卡配合使用的时候会出现这样的问题

**Comment by ydcss** [comment]
个人建议使用同一个滚动容器。令选项卡内容为空，切换时控制列表变量。像这样：
![1](https://cloud.githubusercontent.com/assets/5517400/25887590/4fb52996-3595-11e7-897f-14320ae651ba.png)
![2](https://cloud.githubusercontent.com/assets/5517400/25887594/551ffc08-3595-11e7-92f4-6e905d582851.png)
关于tabkey参数，请更新至最新版本。

**Comment by RoseEnd** [comment]
好的

**Comment by RoseEnd** [comment]
已解决
