### ISSUE TITLE
下拉刷新问题

### ISSUE THREAD

**Issue by lxzjsj** [ydcss/vue-ydui#73]
在chrome浏览器切换手机模式下打开下面地址测试的，从控制台能看到错误
http://www.dlxc6.com:8088/m/index.php?mod=category&catid=4&cityid=1

1.console.log(vue.$refs);打印是空，不知道为什么?
2.如何把下拉刷新和滚动加载结合起来?
谢谢!

**Comment by ydcss** [comment]
1、问题一
&lt;script&gt;<br />&nbsp;&nbsp;var vm = new Vue({<br />&nbsp;&nbsp; &nbsp;&nbsp;el: '#app',<br />&nbsp;&nbsp; &nbsp;&nbsp;mounted: function() {<br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;console.log(this.$refs.prdemo);<br />&nbsp;&nbsp;&nbsp;&nbsp; }<br />&nbsp;&nbsp; });<br />&nbsp;&nbsp;console.log(vm.$refs.prdemo);<br />&lt;/script&gt;
2、问题二
目前不支持结合起来。
