### ISSUE TITLE
关于下拉加载组件调用问题

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#74]
我是一个下拉列表可以通过，选择不同的城市，切换到不同的城市数据，但是下拉列表，在切换后，必须刷新页面才能往下拉，不刷新就不可以，请问有什么办法解决这个问题
而且其他页面会报这个错误 
ydui.js?445b:4 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined

**Comment by ydcss** [comment]
问题一：请更新至最新版本。切换后调用this.$refs.infinitescrollDemo.$emit('ydui.infinitescroll.reInit');
问题二：还是更新至最新版本。
