### ISSUE TITLE
关于$dailog.alert的回调函数问题

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#75]
this.$dialog.alert({
                        mes:'核销成功',
                        callback: () => {
                          self.$router.push({ name: 'myactivity'})
                        }
                      })
这样添加回调函数会报alert，undefined,但是回调函数可以执行

**Comment by ydcss** [comment]
下次问这样的问题，请麻烦带上完整使用代码。

**Comment by xcsweb** [comment]
tongxun(){
          let self=this;
        this.httpget(commonUrl+'/weixin/common/socket_user_auth',{}, function(data){
            if(data.data.status==0){
              var socket = io(data.data.data.url);
              // 连接后登录
              socket.on('connect', function(){
                socket.emit('login',data.data.data.auth);
              });
              // 后端推送来消息时
              socket.on('msg', function(msg){
                if(msg.type!=undefined){
                    if("activity_apply"==msg.type&&msg.id==self.$route.query.ap_id&&parseInt(msg.status)==2){
                      self.$dialog.alert({
                        mes:'核销成功',
                        callback: () => {
                          self.$router.push({ name: 'myactivity'})
                        }
                      })
                    }
                }
              });
            }
          }
        )
      }

**Comment by ydcss** [comment]
tongxun() {<br />    this.$dialog.alert({<br />        mes: '核销成功',<br />        callback: () =&gt; {<br />            alert('fdsjklfjdsfl');<br />        }<br />    });<br />}
这样的代码能执行吗？

**Comment by xcsweb** [comment]
可以执行，没报错，我那个是后端推送消息后出的问题，会不会因为动态创建的问题
