### ISSUE TITLE
官网被提示恶意软件了

### ISSUE THREAD

**Issue by chekun** [ydcss/vue-ydui#754]
#### 问题描述 

官网被拦截了，提示恶意软件了

#### 产生环境

- **使用版本：latest
- **引入方式：NPM
- **演示地址：无

#### 提示错误信息

1. 无错误

#### 代码区域

![image](https://user-images.githubusercontent.com/1967804/55269647-f47cb700-52d0-11e9-9fa6-e29bb6a91557.png)

**Comment by jfyear1994** [comment]
我的也是，什么情况啊
![image](https://user-images.githubusercontent.com/21995695/55270359-c69b7080-52d8-11e9-9e88-0a4cc6a7cb95.png)
