### ISSUE TITLE
关于yd-tab组件 change  prop问题

### ISSUE THREAD

**Issue by RoseEnd** [ydcss/vue-ydui#78]
##### 问题描述 

yd-tab   在切换的时候change的回调会被触发两次

**Comment by RoseEnd** [comment]
补充：有时回调会被触发3次，以前的版本好像没有这个问题

**Comment by ydcss** [comment]
你好，麻烦贴出你使用的代码吧。使用哪个版本的哟

**Comment by RoseEnd** [comment]
![14](https://cloud.githubusercontent.com/assets/19225061/26042078/dca60f32-3964-11e7-9c97-5fe805a11708.png)
![15](https://cloud.githubusercontent.com/assets/19225061/26042079/dcaa1f64-3964-11e7-91d0-416806ea9942.png)
![16](https://cloud.githubusercontent.com/assets/19225061/26042080/dcab2378-3964-11e7-9ee7-9f453180fc1c.png)
我使用的是0.62版本，也就是最新的

**Comment by RoseEnd** [comment]
我每切换一次，会执行多次show方法

**Comment by ydcss** [comment]
你好，注释 tabkey == 'all' ? this.status = '' : this.status = tabkey; 能解决你说的问题。

**Comment by RoseEnd** [comment]
的确是这样，为什么会出现这样的问题，我需要记录当前的tabkey

**Comment by RoseEnd** [comment]
有一种情况是在使用了onchange事件的元素或组件上使用v-model的时候onchange事件会被触发三次

**Comment by ydcss** [comment]
因为监听了active，导致切换时多次调用；
若要记录当前的tabkey，只需将 yd-tab-panel的 :active="status == '...'"全部去掉，组件会自动添加高亮；
若是这样使用，该组件确实存在很大问题。目前我没有想到什么好的解决办法。求PR

**Comment by RoseEnd** [comment]
嗯，我也发现了，去掉active就没问题了

**Comment by RoseEnd** [comment]
貌似还是有点问题，初始化页面的时候也会触发yd-tab的change回调
