### ISSUE TITLE
请问怎么自定义rem的样式？

### ISSUE THREAD

**Issue by ymjdev** [ydcss/vue-ydui#8]
请问怎么自定义rem的样式？

**Comment by ydcss** [comment]
没明白你的问题。举例说明吧。

**Comment by ymjdev** [comment]
比如我要修改主题色，修改tabbar的高度，npm install 下来的直接是打包好的

**Comment by ydcss** [comment]
有些组件提供的props参数可以修改颜色等样式，你所说的Tabbar高度/颜色确实是我遗漏了，将尽快修复。
其他组件请参看文档参数哟。

**Comment by ymjdev** [comment]
我的意思是是否可以自定义主题？直接设置less的var

**Comment by ydcss** [comment]
你好，Vue版本的YDUI暂时不支持自定义LESS变量。

1、情况一：通过NPM安装，是从npmjs.org下载的包，理论上是不能实现的。
2、情况二：通过CDN安装，以常规方式引入，本身可以实现，但是意义不大。

结论：若需自行修改LESS变量，请clone源码修改。
