### ISSUE TITLE
yd-input组件初始化后未显示必填图片,需鼠标点击后才显示

### ISSUE THREAD

**Issue by hhiew** [ydcss/vue-ydui#80]
##### 问题描述 
yd-input组件初始化后未显示必填图片,需鼠标点击后才显示

##### 产生环境

- **使用版本：**0.62
- **设备：**（手机、平板移动设备）:pc
- **操作系统及版本：**win10
- **浏览器及版本：**chrome 58
相关代码

 <template>
  <yd-layout>

    <yd-navbar slot="navbar">
      <router-link :to="redirect_url" slot="left">
        <yd-navbar-back-icon></yd-navbar-back-icon>
      </router-link>
      <span slot="center" class="nav-bar-font">充值</span>
    </yd-navbar>
    <div id="nbdata-createRecharge">
      <div class="nav-bar-margin"></div>
      
      <yd-cell-group>
        <yd-cell-item>
          <span slot="left">充值金额</span>
          <yd-input slot="right" required v-model='amount' placeholder="请输入充值金额"></yd-input>
        </yd-cell-item>
        <yd-cell-item>
          <span slot="left">转帐银行</span>
          <yd-input slot="right" required placeholder="转帐银行" v-model="bank"></yd-input>
        </yd-cell-item>
        <yd-cell-item>
          <span slot="left">转帐帐号名称</span>
          <yd-input slot="right" required placeholder="转帐帐号名称" v-model="acctcode"></yd-input>
        </yd-cell-item>
        <yd-cell-item>
          <span slot="left">转帐帐号</span>
          <yd-input slot="right" required placeholder="转帐帐号" v-model="acctname"></yd-input>
        </yd-cell-item>
        <yd-cell-item>
          <span slot="left">转帐日期</span>
          <yd-input slot="right" required placeholder="转帐日期" v-model="transfer_time"></yd-input>
        </yd-cell-item>
      </yd-cell-group>

    </div>
    <div slot="tabbar">
      <yd-button class="radius-none" size="large" bgcolor="#f00" color="#fff">充值</yd-button>
    </div>
  </yd-layout>
</template>

> 

<script>
  import {NavBar, NavBarBackIcon, NavBarNextIcon} from 'vue-ydui/dist/lib.rem/navbar';
  import {CellGroup, CellItem} from 'vue-ydui/dist/lib.rem/cell';
  import {Layout} from 'vue-ydui/dist/lib.rem/layout';
  import {Input} from 'vue-ydui/dist/lib.rem/input'
  import nAxios from '../../lib/nAxios';
  let components = {};
  components[Layout.name] = Layout;
  components[CellGroup.name] = CellGroup;
  components[CellItem.name] = CellItem;
  components[NavBar.name] = NavBar;
  components[NavBarBackIcon.name] = NavBarBackIcon;
  components[NavBarNextIcon.name] = NavBarNextIcon;
  components[Input.name] = Input;
  export default {
    components: components,
    data () {
      return {
        redirect_url: '/asset',
        objcode: 115,
        amount: '',
        base: '/static/bank',
        show: false,
        bank:'',
        type: 'offline',
        selfbank: {},
        selfbank_id: null,
        surecode: '',
        acctname: '',
        acctcode: '',
        transfer_time: '',
        baseid: null,
        objcode_name: '充值'
      }
    }
  }
</script>
`

**Comment by ydcss** [comment]
是的，我是这样设计的。这样有什么弊端么？

**Comment by hhiew** [comment]
如果一个界面存在必填和非必填的输入框,用户就不知道哪些是必填的,哪些是非必填的.需要一个一个点一下或着我们自己另作别的提示符.但这样又等组件提示符显示出来后会显的乱

**Comment by ydcss** [comment]
所言极是，我尽快完善。

**Comment by ydcss** [comment]
你好，已添加必填提示图标。感谢你的建议。
