### ISSUE TITLE
用自定义的字体图标

### ISSUE THREAD

**Issue by 18210092010** [ydcss/vue-ydui#81]
##### 问题描述 

（简明扼要地描述一下问题）

##### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

##### 复现步奏

1. 我想问下，我想用自定义的字体图标，该怎么添加
2.  
...

**Comment by ydcss** [comment]
你好，自定义图标还请自行定义css哟！

**Comment by 18210092010** [comment]
我已经引入了，在index.html中用cdn引入的，然后在 
<yd-tabbar :fixed="isFixed">
        <yd-tabbar-item title="首页" link="#">
            <span class="iconfont icon-tixian1" slot="icon" ></span>
        </yd-tabbar-item>
    </yd-tabbar>
这样引入的，结果不对，不是出不来，就是显示不对

**Comment by 18210092010** [comment]
![image](https://cloud.githubusercontent.com/assets/19968933/26229353/c61c2f8c-3c73-11e7-8f91-c4a99184db11.png)

**Comment by ydcss** [comment]
请把问题描述详细一点，完整使用代码贴出来。有没有报错信息。
