### ISSUE TITLE
infinitescroll组件报错

### ISSUE THREAD

**Issue by ChenSunMoon** [ydcss/vue-ydui#82]
##### 问题描述 

Cannot read property 'getBoundingClientRect' of undefined

##### 产生环境

- **使用版本：** vue-ydui: ^0.5.9
- **设备：**（手机、平板移动设备）
- **操作系统及版本：** window 10 
- **浏览器及版本：** chrome 版本 56.0.2924.87 m
- **演示地址：**

##### 复现步奏

1. 将示例代码复制到我的代码中
2.  运行查看控制台时发生上面的错误
3. 没有“回到顶部”这个功能
...

**Comment by ydcss** [comment]
http://vue.ydui.org/docs/#/updatelogs

**Comment by ydcss** [comment]
请更新至最新版本哟！
