### ISSUE TITLE
yd-input的regex内置银行卡正则不起作用

### ISSUE THREAD

**Issue by RoseEnd** [ydcss/vue-ydui#83]
##### 问题描述 

内置的银行卡正则四位一隔没有效果

##### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

##### 复现步奏

1. 
2.  
...

**Comment by ydcss** [comment]
你好，问题已经修复。感谢你指出的问题。

**Comment by RoseEnd** [comment]
嗯嗯，好的还有我想问时间选择组件什么时候能出来，因为项目快接近尾声了，但是涉及到时间选择的还没有做，我就是想问问，啥时候能出，如果时间来不及我们单独想办法

**Comment by ydcss** [comment]
你好，我一直都在捣腾这个时间组件，一直没有做出满意的效果。近期怕是不能完成了。

**Comment by RoseEnd** [comment]
get 收到
