### ISSUE TITLE
yd-infinitescroll 无限下拉时, 在微信中会有不流畅的情况

### ISSUE THREAD

**Issue by iqfu321** [ydcss/vue-ydui#84]
yd-infinitescroll 目前是下拉到底部时, 才触发on-infinite. 这样在微信中有时会导致拉不动的情况,因为on-infinite还没有触发, 已经触发微信本身的下拉了. 很多UI是设置一个距离值,在到底部多少距离内就触发on-infinite事件. 如Framework7 的infinite-scroll 有一个 data-distance 属性.用来配置页面滚动到离底部多远时触发无限滚动事件

**Comment by ydcss** [comment]
目前是到达滚动容器的9/10就触发加载，理论上都会加载的呀,。的确其他UI确定会提供一个阈值，我尽快加上吧。

**Comment by ydcss** [comment]
你好，问题已经修复，添加了distance参数。
