### ISSUE TITLE
yd-input type为password时，min和max没有启作用，错误图标没有显示

### ISSUE THREAD

**Issue by shawnBackup** [ydcss/vue-ydui#85]
<yd-cell-item>
        <span slot="left">支付密码：</span>
        <yd-input
        slot="right"
        type="password"
        required
        placeholder="请输入支付密码"
        :showRequiredIcon="false"
        v-model="title"
        min="8"
        max="16"
        ref="type"></yd-input>
    </yd-cell-item>

**Comment by ydcss** [comment]
你好！
1、min和max是启作用的，可以使用this.$refs.type.errorMsg查看。
2、因password已有一个显示隐藏密码的图标，所以在设计的时候就不显示错误正确图标。
3、这样设计会存在什么弊端么？

**Comment by shawnBackup** [comment]
我希望会显示，因为这样其他都有报错标志，就password没有，感觉很怪，而且用户也不能马上明白是否正确

**Comment by ydcss** [comment]
你好，问题已经修复，密码框也会显示错误图标了。

**Comment by shawnBackup** [comment]
帅气！
