### ISSUE TITLE
数字加减spinner错误

### ISSUE THREAD

**Issue by y19942026** [ydcss/vue-ydui#86]
##### 问题描述 

手动输入数字然后直接点加出错，比如文档第一个例子输入3再点加变成33

##### 产生环境

- **使用版本：0.6.3
- **设备：电脑
- **操作系统及版本：win10
- **浏览器及版本：Chrome58
- **演示地址：http://vue.ydui.org/docs/#/spinner

##### 复现步奏

1. 第一个例子输入3
2.  再点加号
...

**Comment by ydcss** [comment]
你好，问题收到，确实存在这样的问题。尽快修复。

**Comment by ydcss** [comment]
你好，问题已经修复，感谢你指出的问题。
