### ISSUE TITLE
建议添加日历控件

### ISSUE THREAD

**Issue by xcsweb** [ydcss/vue-ydui#88]
日历控件可以在某个具体的日期添加备注项等

**Comment by ydcss** [comment]
这个是你们项目的需求吧？<(￣3￣)> !
近期将会添加时间组件，当然也包含了年月日选择。
另外已经有人提过这个issues了。

**Comment by xcsweb** [comment]
对啊

**Comment by hhiew** [comment]
要加功能肯定要提通用性的吧。要加日历可以理解，在点日历加备注这个不具有通用性，感觉要求不合理

**Comment by ydcss** [comment]
你好，时间组件已上线。关于日历组件没有计划做。
