### ISSUE TITLE
使用yd-infinitescroll 和yd-pullrefresh时TypeError: Cannot read property '$on' of undefined

### ISSUE THREAD

**Issue by 631887934** [ydcss/vue-ydui#9]
你好，如题使用滚动加载和下拉刷新时'$on'和$'emit'都是 undefined，原因是this.$yduiBus是undefined，这是什么原因，求教

**Comment by ydcss** [comment]
你好，请问this指向谁？

**Comment by 631887934** [comment]
<template>
	<yd-layout>
		<v-navbar slot="navbar"></v-navbar>
		<yd-pullrefresh :on-infinite="loadLists">
			<v-slider></v-slider>
			<v-service></v-service>
		</yd-pullrefresh>
		<v-tabbar slot="tabbar"></v-tabbar>
	</yd-layout>
</template>

<script>
	import vTabbar from '@common/Tabbar'
	import vNavbar from '@page/index/Navbar'
	import vSlider from '@page/index/Slider'
	import vService from '@page/index/Service'

	export default {
		components: {
			'vNavbar': vNavbar,
			'vSlider': vSlider,
			'vTabbar': vTabbar,
			'vService': vService
		},
		methods: {
			loadLists() {
				console.info(this);
				console.info(this.$yduiBus);
			}
		}
	}
</script>

**Comment by 631887934** [comment]
this指向的是当前组件吧，我是在入口文件中Vue.use(YDUI)

**Comment by ydcss** [comment]
可否看看你的代码呢？

**Comment by 631887934** [comment]
![Uploading image.png…]()

**Comment by 631887934** [comment]
`<template>
	<yd-layout>
		<v-navbar slot="navbar"></v-navbar>
		<yd-pullrefresh :on-infinite="loadLists">
			<v-slider></v-slider>
			<v-service></v-service>
		</yd-pullrefresh>
		<v-tabbar slot="tabbar"></v-tabbar>
	</yd-layout>
</template>

<script>
	import vTabbar from '@common/Tabbar'
	import vNavbar from '@page/index/Navbar'
	import vSlider from '@page/index/Slider'
	import vService from '@page/index/Service'

	export default {
		components: {
			'vNavbar': vNavbar,
			'vSlider': vSlider,
			'vTabbar': vTabbar,
			'vService': vService
		},
		methods: {
			loadLists() {
				console.info(this);
				console.info(this.$yduiBus);
			}
		}
	}
</script>`

**Comment by 631887934** [comment]
不好意思我是新手不太会用github

**Comment by 631887934** [comment]
我把文档示例代码放到.vue组件里面是一样的效果，Error in mounted hook: (found in <YdPullrefresh>)
TypeError: Cannot read property '$on' of undefined

**Comment by 631887934** [comment]
import Vue from 'vue'
import Router from 'vue-router'

Vue.use(Router)

export default new Router({
	mode: 'history',
	routes: [{
		path: '/',
		redirect: '/home'
	}, {
		path: '/home',
		component: resolve => require(['@page/index/Home'], resolve)
	}]
})

**Comment by ydcss** [comment]
你好，感谢你提出的问题，现文字已经修复，但稍微改动下原来的调用方法。原 this.$yduiBus.$emit() 改为 window.$yduiBus.$emit()。

**Comment by 290115231** [comment]
`<template>
    <div>
        <yd-button @click.native="show1 = true" size="large">带取消</yd-button>
    
        <yd-actionsheet :items="myItems1" v-model="show1" cancel="取消"></yd-actionsheet>
    </div>
</template>

<script type="text/babel">
    export default {
        data() {
            return {
                show1: false,
                myItems1: [
                    {
                        label: '拍照',
                        method: () => {
                            this.$dialog.toast({mes: '咔擦，此人太帅！'});
                            /* 注意： method: function() {} 和 method() {}  这样是无法正常使用当前this的 */
                        }
                    },
                    {
                        label: '从相册中偷取',
                        method: () => {
                            this.$dialog.toast({mes: '看到了不该看到的东西！'});
                        }
                    }
                ]
            }
        }
    }
</script>`
你好，我在调用这个组件的时候，调用item的method时会报错this是未定义的。
以下是我的webpack的配置文件
`module.exports = {
    entry: "./entry.js",
    output: {
        path: __dirname,
        filename: "bundle.js"
    },
    module: {
        loaders: [
            { test:/\.css$/, loader: "style-loader!css-loader"},
            { test:/\.vue$/, loader: "vue-loader"}
        ],
    },
    resolve: {
        alias: {
            vue: 'vue/dist/vue.js'
        }
    }
}`
请问我是什么地方出错了呢，谢谢！

**Comment by ydcss** [comment]
你好，单独引用dialog组件正常吗？
`export default {
        mounted() {
            this.$dialog.toast({mes: '咔擦，此人太帅！'});
        }
    }`

**Comment by 290115231** [comment]
不行哦，Uncaught TypeError: Cannot read property 'toast' of undefined，这是报错的信息。

这是我打印出来的this。
![qq 20170327172339](https://cloud.githubusercontent.com/assets/4362958/24350313/4feae412-1314-11e7-836c-1e90b4a24f06.png)

**Comment by ydcss** [comment]
同学们注意啦！官方示例代码中“yd-actionsheet”组件调用了“this.$dialog”组件，若为按需引用组件需另引入dialog组件。
