### ISSUE TITLE
是否可以加一个返回历史浏览位置呢

### ISSUE THREAD

**Issue by starm328** [ydcss/vue-ydui#90]
##### 问题描述 

是否可以加一个返回，返回到之前浏览时的位置，不要返回到顶部？这个可以加强用户体验

##### 产生环境

- **使用版本：**
- **设备：**（手机、平板移动设备）
- **操作系统及版本：**
- **浏览器及版本：**
- **演示地址：**

##### 复现步奏

1. 
2.  
...

**Comment by ydcss** [comment]
你好，这个可以通过vue-router的beforeEach和afterEach实现，用组件形式不好实现吧！

**Comment by chuchur** [comment]
Vue.use(Router)

export default new Router({
....
scrollBehavior (to, from, savedPosition) {
        if (savedPosition) {
          return savedPosition
        } else {
          return { x: 0, y: 0 }
        }
      },
....
})
 vue 的文档里面写的很清晰。
