### ISSUE TITLE
关于webpack 编译失败的问题

### ISSUE THREAD

**Issue by chuchur** [ydcss/vue-ydui#94]
##### 问题描述 

（简明扼要地描述一下问题）
 webpack 无法构建的问题

##### 产生环境  

- **使用版本：** v0.6.6
- **设备：**（手机、平板移动设备） 
- **操作系统及版本：** 
- **浏览器及版本：**
- **演示地址：**
 
1.  
我是这么引用的。
import YDUI from 'vue-ydui'
import {Alert} from 'vue-ydui/dist/lib.rem/dialog'
本地（mac环境）调试和构建都没有问题。  
2. 到服务器构建 编译不过去。上面那2处老是提示缺少 vue 模块。vue当然是不会缺的，我以为是node版本的问题。 把node 从6.4 到8.0 挨个的试了遍。 然后又把ydui 从0.5.5 到0.6.6 挨个试了遍，我想没人像我这样爱折腾。
3. 那么一定就是 ydui的 原因了。 终于找到了。 我发现ydui组件 引入vue 的时候 ，「vue」第一个字母是大写的酱紫：require('Vue') ..,我在想是不是linux 构建的时候大小写敏感了呢， 然后我就把源代码中Vue 改为 vue。果然。成功的构建完成。
4.希望能帮到 卡在这里的人。

**Comment by ydcss** [comment]
你太棒了，这个问题困扰我好久了，一直没解决，太感谢你的“折腾”了。
问题在于使用webpack编译后将vue转成了Vue，%>_<%，尽快修复，再次感谢！
![qq 20170608094047](https://user-images.githubusercontent.com/5517400/26908696-ded5d59e-4c2e-11e7-8ef8-5752eeb3142c.png)

现问题已经修复，非常感谢！！！
